<style type="text/css">
body {
    font-family: sans-serif;
    font-size: 15.4px;
}
table {
    background-color: #f9f9f9;
    border-collapse: collapse;
    font-size: 14px;
}
table th {
    background-color: #f2f2f2;
    border: 1px solid #aaaaaa;
    padding: 5px 10px;
}
table td {
    border: 1px solid #aaaaaa;
    padding: 5px 10px;
}
a.added:link { color: #14681E; }
a.added:visited { color: #66836A; }
a.subtracted:link { color: #AF180D; }
a.subtracted:visited { color: #AF534D; }
a.changed:link { color: #B19523; }
a.changed:visited { color: #D8C471; }

body.dark {
    background-color: #002b36;
    color: #93a1a1;
}
body.dark table { background-color: #073642; }
body.dark table th { background-color: #1C454F; }
</style>
