<style type="text/css">
body { font-family: sans-serif; }
table {
    background-color: #f9f9f9;
    border-collapse: collapse;
}
table th {
    background-color: #f2f2f2;
    border: 1px solid #aaaaaa;
    padding: 5px 10px;
}
table td {
    border: 1px solid #aaaaaa;
    padding: 5px 10px;
}
a.added:link { color: #14681E; }
a.added:visited { color: #66836A; }
a.subtracted:link { color: #AF180D; }
a.subtracted:visited { color: #AF534D; }
a.changed:link { color: #B19523; }
a.changed:visited { color: #D8C471; }
</style>
