<style type="text/css">
body {
    font-family: sans-serif;
    font-size: 15.4px;
}
table {
    background-color: #f9f9f9;
    border-collapse: collapse;
    font-size: 14px;
}
table th {
    background-color: #f2f2f2;
    border: 1px solid #aaaaaa;
    padding: 5px 10px;
}
table td {
    border: 1px solid #aaaaaa;
    padding: 5px 10px;
}
a:link { color: #0066cc; }
a:visited { color: #551a8b; }
a.added:link { color: #14681E; }
a.added:visited { color: #66836A; }
a.subtracted:link { color: #AF180D; }
a.subtracted:visited { color: #AF534D; }
a.changed:link { color: #B19523; }
a.changed:visited { color: #D8C471; }

body.dark {
    background-color: #002b36;
    color: #93a1a1;
}
body.dark a:link { color: rgb(83,173,247); }
body.dark a:visited { color: rgb(167,149,210); }
body.dark a.added:link { color: rgb(64,176,78); }
body.dark a.added:visited { color: #66836A; }
body.dark a.subtracted:link { color: rgb(247,67,15); }
body.dark a.subtracted:visited { color: #AF534D; }
body.dark a.changed:link { color: rgb(205,210,13); }
body.dark a.changed:visited { color: #D8C471; }
body.dark table { background-color: #073642; }
body.dark table th { background-color: #1C454F; }
</style>
