insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
('Mark Xu', 'Alignment Research Center', 'Research staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/mark-xu', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Jacob Hilton', 'Alignment Research Center', 'Research staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/jacob-hilton', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Eric Neyman', 'Alignment Research Center', 'Research staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/eric-neyman', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Dávid Matolcsi', 'Alignment Research Center', 'Research staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/david-matolcsi', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Victor Lecomte', 'Alignment Research Center', 'Research staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/victor-lecomte', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('George Robinson', 'Alignment Research Center', 'Research staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/george-robinson', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Kyle Scott', 'Alignment Research Center', 'Operations staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/kyle-scott', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Kris Chari', 'Alignment Research Center', 'Operations staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/kris-chari', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Rebecca Baron', 'Alignment Research Center', 'Operations staff member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/rebecca-baron', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Paul Christiano', 'Alignment Research Center', 'Founder', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/paul-christiano', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Jacob Hilton', 'Alignment Research Center', 'President', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/jacob-hilton', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Kyle Scott', 'Alignment Research Center', 'Treasurer', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/kyle-scott', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Kyle Scott', 'Alignment Research Center', 'Secretary', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/kyle-scott', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Buck Shlegeris', 'Alignment Research Center', 'Board Member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/buck-shlegeris', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/
,('Ben Hoskin', 'Alignment Research Center', 'Board Member', NULL, NULL, NULL, NULL, 'https://www.alignment.org/team/ben-hoskin', NULL, 'Full-time', 'AI safety') /*Reviewed on 2024-10-09*/ /*current position*/

 
 ,('Amanda She', 'Alignment Research Center', 'Executive Assistant (ARC Evals)', '2023-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/amandarshe/', NULL, 'Full-time', 'AI safety') /*Reviewed on 2023-09-12*/ /*current position*/
  ,('Aryan Bhatt', 'Alignment Research Center', 'SERI MATS Research Scholar', '2022-11-01', 'month', '2023-02-01', 'month', 'https://www.linkedin.com/in/aryanbhatt17/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-14*/ 
  ,('Aryan Bhatt', 'Alignment Research Center', 'Visiting Researcher', '2023-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/aryanbhatt17/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-14*/ /*current position*/ 
  ,('Chris Painter', 'Alignment Research Center', 'Member of Technical Staff (ARC Evals)', '2023-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cpainter1/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
  ,('Elizabeth Barnes', 'Alignment Research Center', 'Project Lead (ARC Evals)', '2022-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/elizabethmbarnes/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
  ,('Emma Abele', 'Alignment Research Center', 'Chief of Staff (ARC Evals)', '2023-03-01', 'month', NULL, NULL, 'https://web.archive.org/web/20230301170836/https://evals.alignment.org/team/ https://www.linkedin.com/in/emma-abele-00147493/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
  ,('Eric Neyman', 'Alignment Research Center', 'Researcher', '2023-09-14', 'month', NULL, NULL, 'https://web.archive.org/web/20230914171025/https://www.alignment.org/theory/ ', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
  ,('Hjalmar Wijk', 'Alignment Research Center', 'Member of Technical Staff', '2023-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/hjalmar-wijk/ https://web.archive.org/web/20230301170836/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', 'Machine Learning Researcher. He works on the ARC evals team evaluating the capabilities and safety of machine learning systems, trying to reduce worst-case risks from future models.', 'Full-time', 'AI safety')  /*Reviewed on 2023-09-17*/ /*current position*/
  ,('Haoxing Du', 'Alignment Research Center', 'Member of Technical Staff (ARC Evals)', '2023-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/haoxing-du-796963247/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
  ,('Jacob Hilton', 'Alignment Research Center', 'Researcher', '2023-06-05', 'year', NULL, NULL, 'https://web.archive.org/web/20230605061745/https://www.alignment.org/theory/ https://web.archive.org/web/20230914171025/https://www.alignment.org/theory/', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
   ,('Josh Jacobson', 'Alignment Research Center', 'Interim Operations Lead (Evals), Formerly Interim Operations Lead (Theory)', '2022-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/joshmjacobson/', NULL, 'contractor', 'AI safety')  /*Reviewed on 2023-09-17*/ /*current position*/
  ,('Kyle Scott', 'Alignment Research Center', 'Operations Manager', '2021-07-01', 'month', '2023-05-01', 'month', 'https://www.linkedin.com/in/kdbscott/', NULL, 'part-time', 'AI safety')  /*Reviewed on 2023-09-12*/  
  ,('Kyle Scott', 'Alignment Research Center', 'Operations Manager', '2023-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kdbscott/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, 'full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
  ,('Lawrence Chan', 'Alignment Research Center', 'Member of Technical Staff', '2022-11-01', NULL, NULL, NULL, 'https://www.linkedin.com/in/lawrencechan2/ https://web.archive.org/web/20230301170836/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-17*/ /*current position*/
  ,('Lucas Sato', 'Alignment Research Center', 'Member of Technical Staff (ARC Evals)', '2023-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/satojk/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, 'Full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Luke Miles', 'Alignment Research Center', 'Member of Technical Staff', '2023-03-01', NULL, NULL, NULL, 'https://web.archive.org/web/20230301170836/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/ 
    ,('Mark Xu', 'Alignment Research Center', 'Researcher', '2021-08-01', 'month', NULL, NULL, 'https://web.archive.org/web/20230605061745/https://www.alignment.org/theory/ https://web.archive.org/web/20230914171025/https://www.alignment.org/theory/ https://www.linkedin.com/in/xu-mark/', NULL, 'full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Max Hasin', 'Alignment Research Center', 'Model Evaluator', '2022-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/max-hasin-886b2587/', NULL, 'Contractor', 'AI safety')  /*Reviewed on 2023-09-17*/ /*current position*/
    ,('Megan Kinniment', 'Alignment Research Center', 'Member of Technical Staff', '2023-03-01', 'month', NULL, NULL, 'https://web.archive.org/web/20230301170836/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/ https://www.linkedin.com/in/megan-kinniment-513355177/', NULL, 'full-time', 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Paul Christiano', 'Alignment Research Center', 'Researcher', '2021-04-26', 'month', NULL, NULL, 'https://ai-alignment.com/announcing-the-alignment-research-center-a9b07f77431b https://web.archive.org/web/20230605061745/https://www.alignment.org/theory/ https://web.archive.org/web/20230914171025/https://www.alignment.org/theory/', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Quentin Feuillade-Montixi', 'Alignment Research Center', 'Model Evaluator', '2023-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/quentin101010/', 'Remote work with the ARC eval team. Skilled in prompt engineering', 'Contractor', 'AI safety')  /*Reviewed on 2023-09-17*/ /*current position*/
    ,('Rae She', 'Alignment Research Center', 'Executive Assistant', '2023-09-12', 'month', NULL, NULL, 'https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Rebecca Baron', 'Alignment Research Center', 'Member of Operations Staff', '2023-09-12', 'month', NULL, NULL, 'https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Tao Lin', 'Alignment Research Center', 'Member of Technical Staff', '2023-05-29', 'year', NULL, NULL, 'https://web.archive.org/web/20230529225539/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Ted Suzman', 'Alignment Research Center', 'Member of Technical Staff', '2023-08-20', 'year', NULL, NULL, 'https://web.archive.org/web/20230820073018/https://evals.alignment.org/team/ https://web.archive.org/web/20230912013151/https://evals.alignment.org/team/', NULL, NULL, 'AI safety')  /*Reviewed on 2023-09-12*/ /*current position*/
    ,('Timothy Kokotajlo', 'Alignment Research Center', 'Contractor', '2022-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/timothy-kokotajlo-087666b7/', NULL, 'Contractor', 'AI safety')  /*Reviewed on 2023-09-17*/ /*current position*/
 