INSERT INTO `positions` (`person`, `organization`, `title`, `start_date`, `start_date_precision`, `end_date`, `end_date_precision`, `urls`, `ai_safety_relation`, `subject`, `employment_type`, `cause_area`, `notes`) VALUES
('David Manheim', 'Association for Long Term Existence and Resilience', 'Founder, Director Of Policy & Research', '2022-01-01', 'month', NULL, NULL, 'https://alter.org.il https://www.linkedin.com/in/davidmanheim/?originalSubdomain=il https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', 'policy', 'full-time', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Naham Shapiro', 'Association for Long Term Existence and Resilience', 'Operations Manager and Public Health Lead', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', 'general', NULL, 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Vanessa Kosoy', 'Association for Long Term Existence and Resilience', 'Board', '2022-04-01', 'month', '2022-04-01', 'month', 'https://alter.org.il https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', 'technical research', 'board member', 'AI safety', NULL), /*Closed*/
('Vanessa Kosoy', 'Association for Long Term Existence and Resilience', 'Director of AI Research', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'position', 'technical research', NULL, 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Edo Arad', 'Association for Long Term Existence and Resilience', 'Executive Board Member', '2022-04-01', 'month', NULL, NULL, 'https://alter.org.il https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'board member', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Yonatan Cale', 'Association for Long Term Existence and Resilience', 'Executive Board Member', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'board member', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Gidon Kadosh', 'Association for Long Term Existence and Resilience', 'Executive Board Member', '2022-04-01', 'month', NULL, NULL, 'https://alter.org.il https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'board member', 'AI safety', 'Listed as Gidi Kadosh on the 2026-08-06 snapshot.'), /*Last checked Wayback snapshot is from 2026-08-06*/
('Shahar Avin', 'Association for Long Term Existence and Resilience', 'Executive Board Member', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'board member', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Daniel Aronowitz', 'Association for Long Term Existence and Resilience', 'Audit Committee', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'board member', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Joshua Fox', 'Association for Long Term Existence and Resilience', 'Audit Committee', '2022-04-01', 'month', NULL, NULL, 'https://alter.org.il https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'board member', 'AI safety', 'Listed as Yehoshua Fox on the 2026-08-06 snapshot.'), /*Last checked Wayback snapshot is from 2026-08-06*/
('Dima Potekhin', 'Association for Long Term Existence and Resilience', 'Association Member', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'associate', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Ayelet Berman', 'Association for Long Term Existence and Resilience', 'Association Member', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'associate', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Ezra Hausdorff', 'Association for Long Term Existence and Resilience', 'Association Member', '2026-08-06', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', NULL, 'associate', 'AI safety', NULL), /*Last checked Wayback snapshot is from 2026-08-06*/
('Ram Rachum', 'Association for Long Term Existence and Resilience', 'AI Safety Fellow', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'position', 'technical research', NULL, 'AI safety', NULL), /*Closed*/
('Rona Tobolsky', 'Association for Long Term Existence and Resilience', 'Policy Fellow', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', 'policy', NULL, 'AI safety', NULL), /*Closed*/
('Asher Brass', 'Association for Long Term Existence and Resilience', 'Standards Fellow', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20260806214811/https://alter.org.il/about/?lang=en', 'GCR organization', 'policy', NULL, 'AI safety', NULL); /*Closed*/