insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values

/* Reviewed on 2025-05-07 / / Last available Wayback snapshot date is 2025-05-07 */

 ('Kirsty Henderson', 'Anima International', 'President', '2024-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kirsty-henderson/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Jakub Stencel', 'Anima International', 'Executive Director & co-funder', '2017-11-01', 'month', NULL, NULL, 'https://web.archive.org/web/20200216013728/https://animainternational.org/about/team/ https://www.linkedin.com/in/jakub-stencel/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare') /* Reviewed on 2025-05-11 / / Last available Wayback snapshot date is 2025-05-11*/
,('Jan Sorgenfrei', 'Anima International', 'Director of Global Impact', '2019-03-01', 'month', NULL, NULL, 'https://web.archive.org/web/20200216013728/https://animainternational.org/about/team/ http://linkedin.com/in/jan-sorgenfrei-386641196/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare') /* Reviewed on 2025-05-11 / / Last available Wayback snapshot date is 2025-05-11*/
,('Lina Lind Christensen', 'Anima International', 'General Manager, Denmark', '2021-09-01', 'month', NULL, NULL, 'https://web.archive.org/web/20200216013728/https://animainternational.org/about/team/ https://www.linkedin.com/in/lina-lind-christensen-748b553a/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'part-time', 'Animal welfare') /* Reviewed on 2025-05-11 / / Last available Wayback snapshot date is 2025-05-11*/
,('Joh Vinding', 'Anima International', 'Executive Director, Denmark', '2021-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/joh-vinding-675b0431/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'part-time', 'Animal welfare')
,('Paweł Rawicki', 'Anima International', 'President, Campaigns Director, Poland', '2019-08-01', 'month', NULL, NULL, 'https://web.archive.org/web/20200216013728/https://animainternational.org/about/team/ https://www.linkedin.com/in/pawe%C5%82-rawicki-9310a7136/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare') /* Reviewed on 2025-05-11 / / Last available Wayback snapshot date is 2025-05-11*/
,('Ilona Rabizo', 'Anima International', 'Vice-President, Director of Advocacy, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Thorbjørn Schiønning', 'Anima International', 'Director of Communications, Denmark', '2020-02-01', NULL, NULL, NULL, 'https://web.archive.org/web/20200216013728/https://animainternational.org/about/team/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare') /* Reviewed on 2025-05-11 / / Last available Wayback snapshot date is 2025-05-11*/
,('Connor Jackson', 'Anima International', 'Chief Executive, United Kingdom', '2018-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cm-jackson/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Bogna Wiltowska', 'Anima International', 'Director of Investigations, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')

/* Investigations and media compaigns */


,('Bogna Wiltowska', 'Anima International', 'Director of Investigations, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Anna Iżyńska', 'Anima International', 'General Campaigns Manager, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Veo Andersen', 'Anima International', 'Director of Social Media, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Nanna Capion', 'Anima International', 'Communications Manager, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Magda Łapińska', 'Anima International', 'Digital Marketing Manager, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Andrii Osadchyi', 'Anima International', 'UX Designer', '2024-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/andriiosadchyi/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Marta Korzeniak', 'Anima International', 'Communication Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Niels Vogensen', 'Anima International', 'Video Producer, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Simone Poulsen', 'Anima International', 'Content Creator, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Marie-Louise Rasch', 'Anima International', 'Content Creator, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Andrzej Skowron', 'Anima International', 'Investigative Photographer, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Susanne Hindberg', 'Anima International', 'Marketing Manager, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Sara Kjær Rasmussen', 'Anima International', 'Campaign Manager, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Aleksander Kot', 'Anima International', 'Investigations Manager, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')

/* Welfare improvements */

,('Thorbjørn Schiønning', 'Anima International', 'Director of Communications, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Mathias Elrød Madsen', 'Anima International', 'Campaign Manager, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Niels Christian Due Johansen', 'Anima International', 'Corporate Relations Manager, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Maria Madej', 'Anima International', 'Corporate Relations Manager, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Anders Skou Jørgensen', 'Anima International', 'Corporate Relations Manager, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Julia Pająk', 'Anima International', 'Corporate Outreach Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Bartosz Zając', 'Anima International', 'Social Campaigns Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Marte Bjerke', 'Anima International', 'Campaign Coordinator, Norway', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Niklas Fjeldberg', 'Anima International', 'Director of Campaigns in Norway', '2024-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nfjeldberg/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Paul Retallick', 'Anima International', 'Campaigns & Business Relations Manager, United Kingdom', '2024-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/paul-retallick-00a92b153/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')

/* Capacity building */

,('Ania Pierzchała', 'Anima International', 'Human Resources Manager, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Iga Karkoszka', 'Anima International', 'Global Development Manager, Anima International', '2021-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/iga-karkoszka/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Marta Cendrowicz', 'Anima International', 'Director of Global Growth, Anima International', '2019-10-01', 'month', NULL, NULL, 'https://web.archive.org/web/20200216013728/https://animainternational.org/about/team/ https://www.linkedin.com/in/marta-cendrowicz/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare') /* Reviewed on 2025-05-11 / / Last available Wayback snapshot date is 2025-05-11*/
,('Christian Winther', 'Anima International', 'Head of Telemarketing, Denmark', '2017-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/christian-winther-nielsen/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'part-time', 'Animal welfare')
,('Aleksandra Knotz', 'Anima International', 'Development Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Agnieszka Rahela Olszak', 'Anima International', 'Head of IT Projects Management, Anima International', '2020-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/agnieszka-olszak/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Filip Stachnik', 'Anima International', 'Operations Manager, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Jannie Duunkjær', 'Anima International', 'Responsible for member service, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Aleksandra Wierzbiak', 'Anima International', 'Full Stack Developer, Anima International', '2019-12-01', NULL, NULL, NULL, 'https://www.linkedin.com/in/aleksandra-wierzbiak-615510127/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Max Harris', 'Anima International', 'Full Stack Developer, Anima International', '2019-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/max-harris-53435a113/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Jakub Matraszek', 'Anima International', 'Volunteer, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Karolina Centkowska', 'Anima International', 'Individual Outreach Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Pawel Stec', 'Anima International', 'Operations Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Jakub Orłowski', 'Anima International', 'Merchandise and Event Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Aleksandra Bujalska', 'Anima International', 'Fundraiser Specialist, Poland', '2020-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/aleksandra-bujalska-818b7418a/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Piotr Bilik', 'Anima International', 'Donor Management Specialist, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Merijn Borsje', 'Anima International', 'IT resident, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Sabrina de Jong Cini', 'Anima International', 'Social Media Manager, Denmark', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Elena Voronkova', 'Anima International', 'Movement Building Specialist, Anima International', NULL, NULL, NULL, NULL, 'https://www.linkedin.com/in/elena-voronkova-b64614238/ https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, 'full-time', 'Animal welfare')
,('Łukasz Michułka', 'Anima International', 'Plantbased Campaign Manager', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Magdalena Motylińska', 'Anima International', 'Events Planning Manager, Poland', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Teodora Mishineva', 'Anima International', 'Vice Chairman, Bulgaria', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')
,('Siliyana Panova', 'Anima International', 'Telefundraiser, Bulgaria', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20250511142550/https://animainternational.org/about/team/', NULL, NULL, 'Animal welfare')


 
 