insert into positions (person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, ai_safety_relation, subject, employment_type, cause_area, notes) values
('Eric Verdin', 'Buck Institute for Research on Aging', 'President and Chief Executive Officer', '2016-01-01', 'year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'strategy', NULL, 'Longevity', 'Biography says he joined the Buck in 2016.'),
('Meagan Moore', 'Buck Institute for Research on Aging', 'Chief Administrative Officer', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'general', NULL, 'Longevity', NULL),
('Nancy Derr', 'Buck Institute for Research on Aging', 'Vice President and Chief Financial Officer', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'general', NULL, 'Longevity', NULL),
('Chris Sickels', 'Buck Institute for Research on Aging', 'Chief Development Officer', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'strategy', NULL, 'Longevity', NULL),
('Robin Snyder', 'Buck Institute for Research on Aging', 'Vice President, Communications', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'popularization', NULL, 'Longevity', NULL),
('Remy Gross III', 'Buck Institute for Research on Aging', 'Vice President, Business Development and Technology Advancement', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'strategy', NULL, 'Longevity', NULL),
('Gordon Lithgow', 'Buck Institute for Research on Aging', 'Chief Academic Officer', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'strategy', NULL, 'Longevity', NULL),
('Juniper K. Pennypacker', 'Buck Institute for Research on Aging', 'Chief of Staff', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'general', NULL, 'Longevity', NULL),
('Lauren House', 'Buck Institute for Research on Aging', 'Executive Team Administrator', '2019-02-14', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20190214085632/https://www.buckinstitute.org/about/leadership/', 'unrelated', 'general', NULL, 'Longevity', NULL);