insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
('Leo Hyams', 'Cape Institute for Safe AI', 'Co-Founder, Executive Director', '2024-01-01', 'year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'strategy', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Tegan Green', 'Cape Institute for Safe AI', 'Operations Director', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'general', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Benjamin Sturgeon', 'Cape Institute for Safe AI', 'Co-Founder, Strategic Director', '2024-01-01', 'year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html https://www.benjaminsturgeon.com/', NULL, 'position', 'strategy', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Jaco Du Toit', 'Cape Institute for Safe AI', 'Evaluations Lead', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'technical research', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Alexa Blagus', 'Cape Institute for Safe AI', 'Workspace Manager', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'general', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Josh Stein', 'Cape Institute for Safe AI', 'Community Manager', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'popularization', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Isabella Hamilton-Russell', 'Cape Institute for Safe AI', 'Program Manager', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'popularization', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Karabo Mokoena', 'Cape Institute for Safe AI', 'Governance Affiliate', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'policy', 'affiliate', 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Christen Rao', 'Cape Institute for Safe AI', 'Governance Affiliate', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'policy', 'affiliate', 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Claude Formanek', 'Cape Institute for Safe AI', 'Research Affiliate', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'technical research', 'affiliate', 'AI safety'); /*Last checked Wayback snapshot is from 2026-09-21*/