insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
('Leo Hyams', 'Cape Institute for Safe AI', 'Co-Founder, Executive Director', '2024-01-01', 'year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'strategy', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Tegan Green', 'Cape Institute for Safe AI', 'Events & Design', '2025-07-01', 'month', '2025-08-01', 'month', 'https://www.linkedin.com/in/tegan-green/', NULL, 'position', 'popularization', 'part-time', 'AI safety'), /*Closed*/
('Tegan Green', 'Cape Institute for Safe AI', 'Program Manager', '2025-09-01', 'month', '2026-07-01', 'month', 'https://www.linkedin.com/in/tegan-green/', NULL, 'position', 'popularization', 'contractor', 'AI safety'), /*Closed*/
('Tegan Green', 'Cape Institute for Safe AI', 'Operations Director', '2026-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tegan-green/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'general', 'full-time', 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Benjamin Sturgeon', 'Cape Institute for Safe AI', 'Co-Founder, Strategic Director', '2024-01-01', 'year', NULL, NULL, 'https://www.benjaminsturgeon.com/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'strategy', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Jaco Du Toit', 'Cape Institute for Safe AI', 'Research Engineer', '2025-05-01', 'month', '2026-09-21', 'month', 'https://www.linkedin.com/in/jaco-du-toit-a04785208/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'technical research', 'part-time', 'AI safety'), /*Closed*/
('Jaco Du Toit', 'Cape Institute for Safe AI', 'Evaluations Lead', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'technical research', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Alexa Blagus', 'Cape Institute for Safe AI', 'Workspace Manager', '2026-09-21', 'multi-year', NULL, NULL, 'https://www.linkedin.com/in/alexa-blagus-113b9b194/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'general', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Josh Stein', 'Cape Institute for Safe AI', 'Community Manager', '2026-09-21', 'multi-year', NULL, NULL, 'https://www.linkedin.com/in/josh-s-5b4ab869/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'popularization', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Isabella Hamilton-Russell', 'Cape Institute for Safe AI', 'Program Manager', '2026-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/isabella-hamilton-russell-6a582919b/ https://www.linkedin.com/feed/update/urn:li:activity:7498723097928175616/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'popularization', 'part-time', 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Karabo Mokoena', 'Cape Institute for Safe AI', 'Governance Affiliate', '2026-09-21', 'multi-year', NULL, NULL, 'https://www.linkedin.com/in/karabo-is-a-doing-word/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'policy', 'affiliate', 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Christen Rao', 'Cape Institute for Safe AI', 'Governance Affiliate', '2026-09-21', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'policy', 'affiliate', 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-21*/
('Claude Formanek', 'Cape Institute for Safe AI', 'Research Affiliate', '2026-09-21', 'multi-year', NULL, NULL, 'https://www.linkedin.com/in/claude-formanek/ https://web.archive.org/web/20260921191820/https://cisai.co/team.html', NULL, 'position', 'technical research', 'affiliate', 'AI safety'); /*Last checked Wayback snapshot is from 2026-09-21*/