insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
/*................................................................Leadership..................................................................*/
 ('Dan Hendrycks', 'Center for AI Safety', 'Executive and Research Director', '2022-08-13', 'year', NULL, NULL, 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://web.archive.org/web/20251118223803/https://safe.ai/about https://www.linkedin.com/in/dan-hendrycks-04062395/', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-11-18*/  
,('Oliver Zhang', 'Center for AI Safety', 'Managing Director', '2024-11-01', 'month', NULL, NULL, 'https://web.archive.org/web/20251118223803/https://safe.ai/about https://www.linkedin.com/in/oliver-z-30a16812a/', NULL, 'Full-time', 'AI safety') /*Last consulted Wayback snapshot is from 2025-11-18*/
,('Josue Estrada', 'Center for AI Safety', 'Chief Operating Officer', '2025-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/josue-estrada-46a130/ https://web.archive.org/web/20251118223803/https://safe.ai/about', NULL, 'Full-time', 'AI safety') /*Last consulted Wayback snapshot is from 2025-11-18*/

/*.............................................................linkedIn positions below.........................................................*/
,('Corin Katzke', 'Center for AI Safety', 'Lead Writer', '2024-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/corin-katzke-29710b176/', NULL, 'Part-time', 'AI safety') /*Reviewed on 2025-11-18*/
,('Long Phan', 'Center for AI Safety', 'Research Engineer', '2023-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/long-phan-3110/', NULL, 'Full-time', 'AI safety') /*Reviewed on 2025-11-18*/
,('Mantas Mazeika', 'Center for AI Safety', 'Research Scientist', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/mmazeika/', NULL, 'Full-time', 'AI safety')/*Reviewed on 2025-11-18*/
,('Rune Kvist', 'Center for AI Safety', 'Board Member', '2022-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/runekvist/', NULL, 'Board Member', 'AI safety')  /*Reviewed on 2025-11-18*/
,('Steven Basart', 'Center for AI Safety', 'Manager of Research and Development', '2023-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/xksteven/', NULL, 'Full-time', 'AI safety') /*Reviewed on 2025-11-18*/

/*...............................................................Closed positions below.................................................................*/
,('Oliver Zhang', 'Center for AI Safety', 'Chief of Staff', '2023-07-01', 'month', '2024-11-01', 'month', 'https://www.linkedin.com/in/oliver-z-30a16812a/', NULL, 'Full-time', 'AI safety') /*closed*/
,('Oliver Zhang', 'Center for AI Safety', 'Co-founder and Project Manager', '2022-04-01', 'month', '2024-03-01', 'month', 'https://www.linkedin.com/in/oliver-z-30a16812a/', NULL, 'Full-time', 'AI safety') /*closed*/
,('Aidan O''Gara', 'Center for AI Safety', 'Research Engineer', '2023-01-01', 'month', '2024-01-01', 'month', 'https://www.linkedin.com/in/abogara/', NULL, 'Intern', 'AI safety') /*closed*/
,('Anders Edson', 'Center for AI Safety', 'Project Manager', '2022-07-01', 'month', '2023-08-01', 'month', 'https://www.linkedin.com/in/anders-edson-66565b236/ https://web.archive.org/web/20220813150758/https://safe.ai/about', NULL, 'Full-time', 'AI safety') /*Closed*/
,('Thomas Woodside', 'Center for AI Safety', 'Researcher & Project Manager', '2022-01-01', 'month', '2022-08-01', 'month', 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://www.linkedin.com/in/thomas-woodside-20131a145/', 'At the newly established Center for AI Safety, he was the first employee and spent full time working on research and managing projects. Some of his responsibilities included co-writing the Pragmatic AI Safety research agenda, overseeing the Machine Learning Safety Scholars program, and managing communications. He would be continuing with these duties on a part-time basis starting in mid-August 2022.', 'Full-time', 'AI safety')/*closed*/ 
,('Suryansh Mehta', 'Center for AI Safety', 'AI Policy Advisor', '2024-06-01', 'month', '2024-12-01', 'month', 'https://www.linkedin.com/in/suryansh-mehta-576003222/', 'Occasional work with Dan Hendrycks on urgent national-security AI projects; freelance role.', 'Contractor', 'AI safety') /*closed*/ 
,('Suryansh Mehta', 'Center for AI Safety', 'Writer, Editor, and Manager', '2023-05-01', 'month', '2024-06-01', 'month', 'https://www.linkedin.com/in/suryansh-mehta-576003222/', 'Managed 3–5 reports; delivered projects; edited 500+ pages of the textbook "Introduction to AI Safety, Ethics, and Society".', 'Full-time', 'AI safety') /*closed*/ 
,('Suryansh Mehta', 'Center for AI Safety', 'Technical Writer', '2022-12-01', 'month', '2023-05-01', 'month', 'https://www.linkedin.com/in/suryansh-mehta-576003222/', 'Full-time contracting while completing graduate degree; contributed to AI Safety, Ethics, and Society textbook.', 'Full-time', 'AI safety') /*closed*/ 
,('Joshua Clymer', 'Center for AI Safety', 'Project Manager', '2022-07-01', 'month', '2022-12-01', 'month', 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://www.linkedin.com/in/joshua-clymer/', NULL, NULL, 'AI safety') /*Closed*/
,('Jun Shern Chan', 'Center for AI Safety', 'Research Intern', '2023-01-01', 'month', '2023-12-01', 'month', 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://web.archive.org/web/20230315193923/https://www.safe.ai/about https://www.linkedin.com/in/chan-jun-shern/', NULL, 'intern', 'AI safety') /*Closed*/
,('Alex Pan', 'Center for AI Safety', 'Research Intern', '2022-07-01', 'month', '2022-08-01', 'month', 'https://www.linkedin.com/in/alexander-pan-0567a2102/', NULL, 'Intern', 'AI safety')/*Closed*/ 
,('Ayush Panda', 'Center for AI Safety', 'Teaching Assistant', '2023-06-01', 'month', '2023-08-01', 'month', 'https://www.linkedin.com/in/ayushpanda1029/', NULL, 'Part-time', 'AI safety') /*closed*/
,('Ayham Al-Saffar', 'Center for AI Safety', 'AI Safety Research Course Facilitator', '2023-02-01', 'month', '2023-08-01', 'month', 'https://www.linkedin.com/in/ayhamalsaffar/', NULL, 'Part-time', 'AI safety') /*Closed*/
,('David Bau', 'Center for AI Safety', 'Collaborator', '2023-03-26', NULL, '2023-12-31', NULL, 'https://web.archive.org/web/20230326125055/https://www.safe.ai/compute-cluster https://web.archive.org/web/20231231041232/https://www.safe.ai/compute-cluster', NULL, NULL, 'AI safety') /*closed*/
,('David Lambert', 'Center for AI Safety', 'Research and Writing Consultant', '2022-09-01', 'month', '2024-09-01',  'month', 'https://www.linkedin.com/in/davidlklambert/', NULL, 'Contractor', 'AI safety') /*closed*/
,('Isabelle Barrass', 'Center for AI Safety', 'Project Manager', '2023-05-01', 'month', '2025-01-01', 'month', 'https://www.linkedin.com/in/isabelle-barrass-44a36210a/', NULL, NULL, 'AI safety') /*closed*/
,('Marc Carauleanu', 'Center for AI Safety', 'Student Researcher', '2022-11-01', 'month', '2022-12-01', 'month', 'https://www.linkedin.com/in/marc-everin/', NULL, 'full-time', 'AI safety')/*Closed*/ 
,('Madhav Malhotra', 'Center for AI Safety', 'Teaching Assistant', '2022-06-01', 'month', '2023-09-01', 'month', 'https://www.linkedin.com/in/madhav-malhotra/', 'Remote', NULL, 'AI safety')/*Closed*/ 
,('Max Kaufmann', 'Center for AI Safety', 'Research Assistant', '2022-09-01', 'month', '2023-01-01', 'month', 'https://www.linkedin.com/in/max-kaufmann-713286209/', 'Continuing work on adversarial robustness in the image classification setting.', 'Full-time', 'AI safety') /*Closed*/ 
,('Steven Basart', 'Center for AI Safety', 'Research Engineer', '2022-05-01', 'month', '2023-03-01', 'month', 'https://www.linkedin.com/in/xksteven/ https://web.archive.org/web/20220813150758/https://safe.ai/about', NULL, 'Full-time', 'AI safety')/*Closed*/ 
,('Thomas Woodside', 'Center for AI Safety', 'Project Manager & Research Collaborator', '2022-08-01', 'month', '2023-08-01', 'month', 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://www.linkedin.com/in/thomas-woodside-20131a145/', 'He would continue work part time while in school. Working on a research project involving Trojan detection in large language models.', 'Part-time', 'AI safety') /*closed*/
,('Kevin Liu', 'Center for AI Safety', 'Project Manager', '2022-03-01', 'month', '2022-07-01', 'month', 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://www.linkedin.com/in/the-kevin-liu/', NULL, NULL, 'AI safety')/*Closed*/ 
,('Corin Katzke', 'Center for AI Safety', 'Writer', '2022-12-01', 'month', '2024-04-30', 'month', 'https://www.linkedin.com/in/corin-katzke-29710b176/', 'Contributing writer for the AI Safety Newsletter; contributed to *An Introduction to AI Safety, Ethics, and Society*. Remote. Contract role.', 'Contractor', 'AI safety')/*Closed*/ 
,('Nathaniel Li', 'Center for AI Safety', 'Research Engineer', '2023-05-01', 'month', '2025-01-31', 'month', 'https://www.linkedin.com/in/nli0/', 'Research co-lead on Humanity''s Last Exam and WMDP; contributed to biosecurity evaluations for virology protocol troubleshooting.', 'Full-time', 'AI safety')/*Closed*/ 
,('Nathaniel Li', 'Center for AI Safety', 'Undergraduate Researcher', '2022-08-01', 'month', '2023-05-01', 'month', 'https://www.linkedin.com/in/nli0/', NULL, NULL, 'AI safety')/*Closed*/ 
,('Rebecca Rothwell', 'Center for AI Safety', 'Lead Editor', '2023-06-01', 'month', '2024-04-01', 'month', 'https://www.linkedin.com/in/rebeccarothwell/', NULL, NULL, 'AI safety') /*closed*/ 
,('Zifan Wang', 'Center for AI Safety', 'Research Engineer', '2023-04-01', 'month', '2023-11-01', 'month', 'https://www.linkedin.com/in/zifanw/', NULL, NULL, 'AI safety') /*closed*/ 
,('Xuwang Yin', 'Center for AI Safety', 'Research Engineer', '2023-01-01', 'month', '2025-04-01', 'month', 'https://www.linkedin.com/in/xuwangyin/', NULL, 'intern', 'AI safety') /*closed*/ 
,('Sidney Hough', 'Center for AI Safety', 'Project Manager', '2022-08-13', 'year', '2023-03-15', NULL, 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://web.archive.org/web/20230315193923/https://safe.ai/about', NULL, NULL, 'AI safety')/*closed*/ 
,('Andy Zou', 'Center for AI Safety', 'Project Manager & Research Collaborator', '2022-08-13', 'year', '2023-03-15', NULL, 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://web.archive.org/web/20230315193923/https://safe.ai/about', NULL, NULL, 'AI safety')/*closed*/  
,('Scott Emmons', 'Center for AI Safety', 'Research Collaborator', '2022-08-13', 'year', '2023-03-15', NULL, 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://web.archive.org/web/20230315193923/https://safe.ai/about', NULL, NULL, 'AI safety') /*closed*/  
,('Michael Chen', 'Center for AI Safety', 'Research Collaborator', '2022-08-13', 'year', '2023-03-15', NULL, 'https://web.archive.org/web/20220813150758/https://safe.ai/about https://web.archive.org/web/20230315193923/https://safe.ai/about', NULL, NULL, 'AI safety') /*closed*/ 