insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
('Finbarr Murphy', 'Centre for Emerging Risk Studies', 'Founding Member', '2007-01-01', 'year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Martin Mullins', 'Centre for Emerging Risk Studies', 'Founding Member', '2007-01-01', 'year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Raymond J Friel', 'Centre for Emerging Risk Studies', 'Member', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Barry Sheehan', 'Centre for Emerging Risk Studies', 'Contributing Member', '2020-11-26', 'multi-year', '2020-12-09', 'month', 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20201209063554/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20210619161342/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Closed*/
('Barry Sheehan', 'Centre for Emerging Risk Studies', 'Senior Member', '2021-06-19', 'month', NULL, NULL, 'https://web.archive.org/web/20210619161342/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Darren Shannon', 'Centre for Emerging Risk Studies', 'PhD Researcher', '2020-11-26', 'multi-year', '2021-10-06', 'month', 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20211006000729/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20220121180957/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Closed*/
('Darren Shannon', 'Centre for Emerging Risk Studies', 'Researcher', '2022-01-21', 'month', NULL, NULL, 'https://web.archive.org/web/20220121180957/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Martin Cunneen', 'Centre for Emerging Risk Studies', 'Member', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Florian David-Spickermann', 'Centre for Emerging Risk Studies', 'Postgraduate', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Fabian Pütz', 'Centre for Emerging Risk Studies', 'PhD Student and Research Assistant', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Cian Ryan', 'Centre for Emerging Risk Studies', 'PhD Student', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Irini Furxhi', 'Centre for Emerging Risk Studies', 'PhD Scholar', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Tim Jannusch', 'Centre for Emerging Risk Studies', 'PhD Student', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Arash Negahdari Kia', 'Centre for Emerging Risk Studies', 'Research Fellow', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'postdoc', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Wei Xu', 'Centre for Emerging Risk Studies', 'PhD Student', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Leandro Masello', 'Centre for Emerging Risk Studies', 'PhD Student', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Mahsa Mirzaei', 'Centre for Emerging Risk Studies', 'PhD Student', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Juliane Ressel', 'Centre for Emerging Risk Studies', 'PhD Student', '2020-11-26', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20201126075725/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Frank Cremer', 'Centre for Emerging Risk Studies', 'PhD Student', '2021-06-19', 'month', NULL, NULL, 'https://web.archive.org/web/20210619161342/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Kevin McDonnell', 'Centre for Emerging Risk Studies', 'PhD Student', '2021-06-19', 'month', NULL, NULL, 'https://web.archive.org/web/20210619161342/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Emer Owens', 'Centre for Emerging Risk Studies', 'Risk Management and Insurance Researcher', '2023-11-23', 'month', NULL, NULL, 'https://web.archive.org/web/20231123055544/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, NULL, NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Aisling Owen', 'Centre for Emerging Risk Studies', 'PhD Student', '2023-11-23', 'month', NULL, NULL, 'https://web.archive.org/web/20231123055544/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Niall O’Donnell', 'Centre for Emerging Risk Studies', 'PhD Student', '2023-11-23', 'month', NULL, NULL, 'https://web.archive.org/web/20231123055544/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL), /*Last checked Wayback snapshot is from 2026-09-22*/
('Eamon Leonard', 'Centre for Emerging Risk Studies', 'PhD Student', '2024-03-03', 'month', NULL, NULL, 'https://web.archive.org/web/20240303102916/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting https://web.archive.org/web/20260922003535/https://www.ul.ie/business/kbs-research/research-clusters/emerging-risk-assessment-and-underwriting', NULL, 'graduate student', NULL); /*Last checked Wayback snapshot is from 2026-09-22*/