insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
 
     ('Angus Mercer', 'The Centre for Long-Term Resilience', 'Founder and Chief Executive', '2019-11-01', 'month', NULL, NULL, 'https://web.archive.org/web/20210720215028/https://www.longtermresilience.org/team https://www.linkedin.com/in/angusmercer/?originalSubdomain=uk https://www.linkedin.com/in/angusmercer/?originalSubdomain=uk', NULL, NULL, 'Longtermism')
    ,('Cassidy Nelson', 'The Centre for Long-Term Resilience', 'Board member', '2021-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20210720215028/https://www.longtermresilience.org/team', NULL, 'Board member', 'Longtermism')
    ,('Emma Lawsen', 'The Centre for Long-Term Resilience', 'Team Executive Assistant', '2022-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/emmalawsen/?locale=sv_SE', NULL, 'Full-time', 'Longtermism')/*Updated as of 2023-01-06*/
    ,('Gabriella Overödder', 'The Centre for Long-Term Resilience', 'Chief of Staff', '2021-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/gabriella-over%C3%B6dder-8314a19b/?originalSubdomain=se', NULL, 'Full-time', 'Longtermism')/*Updated as of 2023-01-06*/
    ,('Jade Leung', 'The Centre for Long-Term Resilience', 'Board member', '2021-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20210720215028/https://www.longtermresilience.org/team', NULL, 'Board member', 'Longtermism')
    ,('James Ginns', 'The Centre for Long-Term Resilience', 'Head of Risk Management Policy', '2022-04-06', 'month', NULL, NULL, 'https://www.longtermresilience.org/post/cltr-appoints-james-ginns-as-head-of-risk-management-policy#:~:text=2%20min-,CLTR%20appoints%20James%20Ginns%20as%20Head%20of%20Risk%20Management%20Policy,most%20extreme%20risks%20we%20face. https://web.archive.org/web/20220625021618/https://www.longtermresilience.org/team', NULL, NULL, 'Longtermism')/*Updated as of 2023-01-06*/
    ,('Jess Whittlestone', 'The Centre for Long-Term Resilience', 'Head of AI Policy', '2022-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jess-whittlestone-18545656/?originalSubdomain=uk', NULL, NULL, 'Longtermism')/*Updated as of 2023-01-06*/
    ,('Niel Bowerman', 'The Centre for Long-Term Resilience', 'Board member', '2021-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20210720215028/https://www.longtermresilience.org/team', NULL, 'Board member', 'Longtermism')
    ,('Sophie Dannreuther', 'The Centre for Long-Term Resilience', 'Founder and Director', '2021-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20210720215028/https://www.longtermresilience.org/team', NULL, NULL, 'Longtermism')
    ,('Sophie Rose', 'The Centre for Long-Term Resilience', 'Biosecurity Policy Manager', '2022-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rosesophie/', NULL, NULL, 'Longtermism')/*Updated as of 2023-01-06*/
    ,('Tildy Stokes', 'The Centre for Long-Term Resilience', 'External Consultant', '2021-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20210720215028/https://www.longtermresilience.org/team', NULL, NULL, 'Longtermism')
