# Automated add from scripts/open_phil_proc.py
insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values


    ,('Allan Dafoe', 'Cooperative AI Foundation', 'Trustee', '2021-05-05', 'year', NULL, NULL, 'https://web.archive.org/web/20210505150134/https://www.cooperativeai.com/foundation https://web.archive.org/web/20220616134020/https://www.cooperativeai.com/foundation', NULL, 'board member', 'AI safety')
    ,('Amrit Sidhu-Brar', 'Cooperative AI Foundation', 'Operations Manager', NULL, NULL, '2022-05-09', 'month', 'https://web.archive.org/web/20220509104016/https://www.cooperativeai.com/foundation', NULL, NULL, 'AI safety')
    ,('Amrit Sidhu-Brar', 'Cooperative AI Foundation', 'Operations Associate', '2022-06-16', 'month', NULL, NULL, 'https://web.archive.org/web/20220616134020/https://www.cooperativeai.com/foundation', NULL, NULL, 'AI safety')
    ,('Dario Amodei', 'Cooperative AI Foundation', 'Trustee', '2021-05-05', 'year', NULL, NULL, 'https://web.archive.org/web/20210505150134/https://www.cooperativeai.com/foundation https://web.archive.org/web/20220610165957/https://www.cooperativeai.com/foundation', NULL, 'board member', 'AI safety')
    ,('Eric Horvitz', 'Cooperative AI Foundation', 'Trustee', '2021-05-05', 'year', NULL, NULL, 'https://www.cooperativeai.com/foundation', NULL, 'board member', 'AI safety')
    ,('Gillian Hadfield', 'Cooperative AI Foundation', 'Trustee', '2021-05-05', 'year', NULL, NULL, 'https://web.archive.org/web/20210505150134/https://www.cooperativeai.com/foundation https://web.archive.org/web/20220610165957/https://www.cooperativeai.com/foundation', NULL, 'board member', 'AI safety')
    ,('Jesse Clifton', 'Cooperative AI Foundation', 'Research Analyst', NULL, NULL, NULL, NULL, 'https://www.cooperativeai.com/foundation', NULL, NULL, 'AI safety')
    ,('Lewis Hammond', 'Cooperative AI Foundation', 'Acting Executive Director', '2022-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lrhammond/ https://web.archive.org/web/20220417085005/https://www.cooperativeai.com/foundation https://web.archive.org/web/20220616134020/https://www.cooperativeai.com/foundation', NULL, 'part-time', 'AI safety')
    ,('Ruairi Donnelly', 'Cooperative AI Foundation', 'Trustee', '2021-05-05', 'year', NULL, NULL, 'https://web.archive.org/web/20210505150134/https://www.cooperativeai.com/foundation https://web.archive.org/web/20220610165957/https://www.cooperativeai.com/foundation', NULL, 'board member', 'AI safety') 
    ,('Vincent Conitzer', 'Cooperative AI Foundation', 'Advisor', '2022-04-17', 'month', NULL, NULL, 'https://web.archive.org/web/20220417085005/https://www.cooperativeai.com/foundation https://web.archive.org/web/20220616134020/https://www.cooperativeai.com/foundation', 'Professor at Carnegie Mellon University and Professor at University of Oxford', 'advisor', 'AI safety')
