insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
    ('William MacAskill','Forethought Foundation for Global Priorities Research','Director','2018-11-25','month',NULL,NULL,'http://web.archive.org/web/20181125024917/https://www.forethought.org/about-us/ https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global','See https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global for the launch post by MacAskill.','full-time','Cause prioritization')
    ,('Laura Pomarius','Forethought Foundation for Global Priorities Research','Assistant Director','2018-11-25','month',NULL,NULL,'http://web.archive.org/web/20181125024917/https://www.forethought.org/about-us/ https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global','See https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global for the launch post by MacAskill.','full-time','Cause prioritization')
    ,('Aron Vallinder','Forethought Foundation for Global Priorities Research','Research Fellow','2018-11-25','month',NULL,NULL,'http://web.archive.org/web/20181125024917/https://www.forethought.org/about-us/ https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global','See https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global for the launch post by MacAskill.','full-time','Cause prioritization')
    ,('Philip Trammell','Forethought Foundation for Global Priorities Research','Research Fellow','2018-11-25','month','2020-05-25','month','http://web.archive.org/web/20181125024917/https://www.forethought.org/about-us/ https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global http://web.archive.org/web/20200525151620/https://www.forethought.org/about-us','See https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global for the launch post by MacAskill.','full-time','Cause prioritization')
    ,('Luisa Rodriguez','Forethought Foundation for Global Priorities Research','Research Fellow','2020-02-01','month',NULL,NULL,'http://web.archive.org/web/20200525151620/https://www.forethought.org/about-us https://www.linkedin.com/in/luisa-rodriguez-837835bb/',NULL,'full-time','Cause prioritization')
    ,('Luisa Rodriguez','Forethought Foundation for Global Priorities Research','Chief Of Staff','2021-09-01','month', '2021-09-01', 'month','https://www.linkedin.com/in/luisa-rodriguez-837835bb/',NULL,'full-time','Cause prioritization')
    ,('Luisa Rodriguez','Forethought Foundation for Global Priorities Research','Strategic Advisor','2021-01-01', NULL,NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-uss',NULL,'Advisor','Cause prioritization')
    ,('Frankie Andersen-Wood','Forethought Foundation for Global Priorities Research','Executive Assistant','2020-03-01','month',NULL,NULL,'https://web.archive.org/web/20201204231753/https://www.forethought.org/about-us https://www.linkedin.com/in/fandersenwood/?originalSubdomain=uk',NULL,'full-time','Cause prioritization')
    ,('Max Daniel','Forethought Foundation for Global Priorities Research','Chief of Staff','2021-07-01','month',NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-us https://www.linkedin.com/in/max-daniel/',NULL,'full-time','Cause prioritization')
    ,('Eirin Evjen','Forethought Foundation for Global Priorities Research','Operations Associate','2021-09-01','month',NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-us https://www.linkedin.com/in/eirinevjen/',NULL, NULL,'Cause prioritization')
    ,('John G. Halstead','Forethought Foundation for Global Priorities Research','Research Fellow','2021-01-01', NULL,NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-us',NULL, NULL,'Cause prioritization')
    ,('Stephen Clare','Forethought Foundation for Global Priorities Research','Research Fellow','2021-08-01', 'month',NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-us https://www.linkedin.com/in/stephen-clare-66616081/',NULL, NULL,'Cause prioritization')
    ,('Leopold Aschenbrenner','Forethought Foundation for Global Priorities Research','Research Fellow','2021-06-01', 'month',NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-ushttps://www.linkedin.com/in/leopold-aschenbrenner/',NULL, 'full-time','Cause prioritization')
    ,('Thomas Moynihan','Forethought Foundation for Global Priorities Research','Research Fellow','2021-08-01', 'month',NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-us https://www.linkedin.com/in/thomas-moynihan-3a69731a7/',NULL, NULL,'Cause prioritization')
    ,('Igor Kurganov','Forethought Foundation for Global Priorities Research','Strategic Advisor','2021-01-01', NULL,NULL,NULL,'https://web.archive.org/web/20211106145330/https://www.forethought.org/about-us',NULL, 'Advisor','Cause prioritization')
    ,('Risto Uuk','Forethought Foundation for Global Priorities Research','Global Priorities Fellow','2021-03-01', 'month',NULL,NULL,'https://www.linkedin.com/in/ristouuk/',NULL, NULL,'Cause prioritization')
    ,('Pedro Oliboni','Forethought Foundation for Global Priorities Research','Global Priorities Fellow','2021-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/pedrooliboni/',NULL, NULL,'Cause prioritization')
    ,('Zach Freitas-Groff','Forethought Foundation for Global Priorities Research','Global Priorities Fellow','2019-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/zachgroff/',NULL, NULL,'Cause prioritization')
 


