insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
     ('Akhil Deo','Future of Life Institute','Communications Specialist','2022-08-01','month','2023-06-01','month','https://www.linkedin.com/in/deo94/',NULL,NULL,NULL,'Full-time','AI safety') /*closed*/
    ,('Alan Alda','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Alan Guth','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Alan Yan','Future of Life Institute','Research & Community Engagement','2017-02-01','month','2018-08-01','month','https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Ales Flidr','Future of Life Institute','Volunteer','2014-04-01','month','2015-12-01','month','https://www.linkedin.com/in/ales-flidr-96764638 https://futureoflife.org/about-us/our-people/past-volunteers/',NULL,NULL,NULL,'volunteer','AI safety') /*closed*/
    ,('Alexandra Tsalidis', 'Future of Life Institute', 'EU Policy Fellow', '2023-09-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/ https://theorg.com/org/future-of-life-institute/org-chart/alexandra-tsalidis', NULL, NULL, NULL, NULL, 'AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Andrea Berman','Future of Life Institute','Grants Manager','2021-07-01','month',NULL,NULL,'https://www.linkedin.com/in/andreackb/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Anna Hehir','Future of Life Institute','Program Manager for Autonomous Weapons Systems','2022-11-01','month',NULL,NULL,'https://www.linkedin.com/in/anna-hehir-258878b2/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Anna Yelizarova','Future of Life Institute','Project Manager','2020-06-01','month',NULL,NULL,'https://www.linkedin.com/in/annayelizarova/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Anthony Aguirre','Future of Life Institute','Executive Director and co-founder','2014-05-01','month',NULL,NULL,'https://futureoflife.org/team/ https://foresight.org/publications/AGI-Timeframes&PolicyWhitePaper.pdf https://www.linkedin.com/in/anthony-aguirre-75751b9/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,'board member','AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Ariel Conn','Future of Life Institute','Director of Communications and Outreach','2015-01-01','year','2019-01-01','year','https://www.linkedin.com/in/aconn23/ https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')/*closed*/
    ,('Ben Eisenpress', 'Future of Life Institute', 'Director of Operations', '2023-03-01', 'month', NULL, NULL, 'https://theorg.com/org/future-of-life-institute/org-chart/ben-eisenpress https://www.linkedin.com/in/beneisenpress/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/', NULL, NULL, NULL, 'Full-time', 'AI safety')/*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Blake Pierson','Future of Life Institute','Director of Communications, Outreach and Operations',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety') 
    ,('Carlos Ignacio Gutierrez', 'Future of Life Institute', 'Artificial Intelligence Policy Researcher / UN Representative', '2021-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/carlosig/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/', NULL, NULL, NULL, 'Full-time', 'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Chase Moores','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/about-us/our-people/past-volunteers/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Christof Koch','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Claudia Prettner','Future of Life Institute','EU Representative','2022-08-01','month','2022-12-01','month','https://www.linkedin.com/in/claudiaprettner/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Daniel Dewey','Future of Life Institute','Program Officer for AI Grants','2015-01-01','year',NULL,NULL,'https://www.fhi.ox.ac.uk/wp-content/uploads/Daniel-Dewey.pdf',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Daniel R. Miller','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/about-us/our-people/past-volunteers/',NULL,NULL,NULL,'volunteer','AI safety') /*closed*/ 
    ,('David E. Nicholson', 'Future of Life Institute', 'Director, Future of Life Award', '2020-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/denich/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/', NULL, NULL, NULL, 'Full-time', 'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('David Stanley','Future of Life Institute','Project Coordinator','2015-04-01','month','2019-01-01','month','https://www.linkedin.com/in/davearthurstanley/ https://futureoflife.org/person/david-stanley/',NULL,NULL,NULL,'volunteer','AI safety') /*closed*/
    ,('Elon Musk','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Emilia Javorsky','Future of Life Institute','Director, Futures Program','2019-03-01','month',NULL,NULL,'https://www.linkedin.com/in/emilia-javorsky/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/  
    ,('Erik Brynjolfsson','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Eric Gastfriend','Future of Life Institute',NULL,NULL,NULL,'2024-03-02',NULL,'https://futureoflife.org/person/eric-gastfriend/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Fazl Barez', 'Future of Life Institute', 'AI Research (AI Existential Safety) Affiliate', '2023-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/fbarez/', NULL, NULL, NULL, NULL, 'AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Francesca Rossi','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Frank Wilczek','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('George Church','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/   
    ,('Hamza Tariq Chaudhry', 'Future of Life Institute', 'US Policy Specialist', '2023-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/hamza-tariq-chaudhry/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/', NULL, NULL, NULL, 'Full-time', 'AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Isabella Hampton', 'Future of Life Institute', 'Policy Researcher', '2024-02-27', 'month', NULL, NULL, 'https://web.archive.org/web/20240227231647/https://futureoflife.org/about-us/our-people/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/', NULL, NULL, NULL, NULL, 'AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Jaan Tallinn','Future of Life Institute','Co-Founder','2014-05-01','month',NULL,NULL,'https://web.archive.org/web/20221013205644/https://futureoflife.org/about-us/our-people/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,'board member','AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Jacob Beebe','Future of Life Institute','International Research Assistant','2016-06-01','month','2019-05-01','month','https://www.linkedin.com/in/beebeja/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Janos Kramar','Future of Life Institute','Volunteer',NULL,NULL,'2024-03-02',NULL,'https://futureoflife.org/person/janos-kramar/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Jesse Galef','Future of Life Institute','Program Manager','2014-01-01','year','2015-01-01','year','https://www.linkedin.com/in/jessegalef/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/ 
    ,('Kazue Evans','Future of Life Institute',NULL,NULL,NULL,'2024-03-02',NULL,'https://futureoflife.org/person/kazue-evans/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Landon Klein', 'Future of Life Institute', 'Director of U.S. Policy', '2023-01-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/ https://www.linkedin.com/in/landonmklein/', NULL, NULL, NULL, NULL, 'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Lucas Perry','Future of Life Institute','Project Manager','2015-10-01','month','2021-06-01','month','https://www.linkedin.com/in/lucas-perry-950157107/ https://futureoflife.org/team/',NULL,NULL,NULL,'Full-time','AI safety') /*closed*/ 
    ,('Lucas Perry','Future of Life Institute','Host, Future of Life Institute Podcast','2018-06-01','month','2022-03-01','month','https://www.linkedin.com/in/lucas-perry-950157107/ https://futureoflife.org/team/',NULL,NULL,NULL,'Full-time','AI safety')/*closed*/
    ,('Maggie Munro', 'Future of Life Institute', 'Communications Strategist', '2023-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maggiemunro/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/', NULL, NULL, NULL, 'Full-time', 'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Mark Brakel','Future of Life Institute','Director of European Policy','2021-05-01','month','2022-08-01','month','https://www.linkedin.com/in/markbrakel/',NULL,NULL,NULL,'Full-time','AI safety') /*closed*/    
    ,('Mark Brakel','Future of Life Institute','Director of Policy','2022-09-01','month',NULL,NULL,'https://www.linkedin.com/in/markbrakel/ https://theorg.com/org/future-of-life-institute/org-chart/mark-brakel https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,'Full-time','AI safety')  /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Martin Rees','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Maxim Kesin','Future of Life Institute','Volunteer','2015-02-01','month',NULL,NULL,'https://www.linkedin.com/in/maxkhesin/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Max Tegmark','Future of Life Institute','President and Co-Founder',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,'board member','AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Meia Chita-Tegmark','Future of Life Institute','Co-Founder','2014-05-01','month',NULL,NULL,'https://futureoflife.org/team/ https://www.linkedin.com/in/meia-chita-tegmark-2b5b529b/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,'board member','AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Melody Guan','Future of Life Institute','Volunteer','2015-05-01','month',NULL,NULL,'https://www.linkedin.com/in/melodyguan/ https://futureoflife.org/team/',NULL,NULL,NULL,'volunteer','AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Morgan Freeman','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Na Li','Future of Life Institute','Volunteer','2016-06-01','month','2024-03-02',NULL,'https://futureoflife.org/wp-content/uploads/2019/02/2018-Annual-Report.pdf?x51579 https://futureoflife.org/team/',NULL,NULL,NULL,'volunteer','AI safety') /*closed*/
    ,('Nick Bostrom','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Peter Haas','Future of Life Institute','Volunteer',NULL,NULL,'2024-03-02',NULL,'https://futureoflife.org/person/peter-haas/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Rafael Martinez-Galarza','Future of Life Institute',NULL,NULL,NULL,'2024-03-02',NULL,'https://futureoflife.org/person/rafael-martinez-galarza/',NULL,NULL,NULL,NULL,'AI safety')/*closed*/
    ,('Richard Mallah','Future of Life Institute','Director of AI Projects','2014-04-01','month','2022-10-01','month','https://www.linkedin.com/in/richardmallah/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Richard Mallah','Future of Life Institute','Technical AI consultant','2022-10-01','month','2023-06-01','month','https://www.linkedin.com/in/richardmallah/ https://foresight.org/publications/AGI-Timeframes&PolicyWhitePaper.pdf',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Richard Mallah','Future of Life Institute','Principal AI Safety Strategist','2023-06-01','month',NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/ https://www.linkedin.com/in/richardmallah/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Risto Uuk','Future of Life Institute','Policy Researcher','2021-07-06','month','2023-06-01','month','https://www.linkedin.com/in/ristouuk/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Risto Uuk','Future of Life Institute','EU Research Lead','2023-06-01','month',NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/ https://www.linkedin.com/in/ristouuk/',NULL,NULL,NULL,NULL,'AI safety')/*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Sandra Faber','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Saul Perlmutter','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Stephen Hawking','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Stuart Russell','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Taylor Jones','Future of Life Institute','Website Manager','2021-09-01','month',NULL,NULL,'https://www.linkedin.com/in/tjonesdesigner/?originalSubdomain=uk',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Tim Schreier', 'Future of Life Institute', 'Policy Researcher & Technical Standards Advisor', '2023-11-27', 'month', NULL, NULL, 'https://web.archive.org/web/20231127085359/https://futureoflife.org/about-us/our-people/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/', NULL, NULL, NULL, NULL,'AI safety')/*Reviewed as of 2024-03-02*/ /*current position*/
    ,('Tucker Davey','Future of Life Institute','Writer and Editor','2017-01-01','month','2021-05-01','month','https://www.linkedin.com/in/tucker-davey-507aa2a5/ https://futureoflife.org/team/',NULL,NULL,NULL,'Full-time','AI safety')/*closed*/
    ,('Vera Koroleva','Future of Life Institute',NULL,NULL,NULL,'2024-03-02',NULL,'https://futureoflife.org/person/vera-koroleva/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Victoria Krakovna','Future of Life Institute','Co-Founder','2014-03-01','month',NULL,NULL,'https://www.linkedin.com/in/vkrakovna/ https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,'board member','AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/
    ,('William Jones','Future of Life Institute','Editorial Manager',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20240302052639/https://futureoflife.org/about-us/our-people/',NULL,NULL,NULL,NULL,'AI safety') /*Reviewed as of 2024-03-02*/ /*current position*/ 
    ,('Yishuai Du','Future of Life Institute','Volunteer','2016-01-01','year','2020-01-01','month','https://www.linkedin.com/in/yishuai-du-583a17b5/ https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
    ,('Zara Yaqoob','Future of Life Institute','volunteer',NULL,NULL,'2024-03-02',NULL,'https://futureoflife.org/person/zara-yaqoob/',NULL,NULL,NULL,NULL,'AI safety') /*closed*/
;
