insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
    ('Daniel Dewey','Future of Life Institute','Program Officer for AI Grants','2015-01-01','year',NULL,NULL,'https://www.fhi.ox.ac.uk/wp-content/uploads/Daniel-Dewey.pdf',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jaan Tallinn','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Max Tegmark','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Victoria Krakovna','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Anthony Aguirre','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/ https://foresight.org/publications/AGI-Timeframes&PolicyWhitePaper.pdf',NULL,NULL,NULL,NULL,'AI safety')
    ,('Meia Chita-Tegmark','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Alan Alda','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Nick Bostrom','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Erik Brynjolfsson','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('George Church','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Morgan Freeman','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Alan Guth','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Stephen Hawking','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Christof Koch','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Elon Musk','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Saul Perlmutter','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Martin Rees','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Francesca Rossi','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Stuart Russell','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Frank Wilczek','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Ariel Conn','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Tucker Davey','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Richard Mallah','Future of Life Institute','Technical AI consultant',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/ https://foresight.org/publications/AGI-Timeframes&PolicyWhitePaper.pdf',NULL,NULL,NULL,NULL,'AI safety')
    ,('Mark Brakel','Future of Life Institute','Director of Policy',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Carlos Ignacio Gutierrez','Future of Life Institute','Policy Researcher',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Claudia Prettner,'Future of Life Institute','EU Representative',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Risto Uuk','Future of Life Institute','Policy Researcher',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Blake Pierson','Future of Life Institute','Director of Communications, Outreach and Operations',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Anna Yelizarova','Future of Life Institute','Project Manager',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Andrea Berman','Future of Life Institute','Grants Manager',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Emilia Javorsky','Future of Life Institute','Director of Grants and Multistakeholder Engagement',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Akhil Deo','Future of Life Institute','Social Media Manager',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')"
    ,('Gus Docker','Future of Life Institute','Podcast Host',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Taylor Jones','Future of Life Institute','Website Manager',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Will Jones','Future of Life Institute','Editorial Manager',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Anna Hehir','Future of Life Institute','Program Manager for Autonomous Weapons Systems',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Lucas Perry','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('David Stanley','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Alan Yan','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Eric Gastfriend','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Grzegorz Orwiński','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jacob Beebe','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Kazue Evans','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Na Li','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Rafael Martinez-Galarza','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Vera Koroleva','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Xin Wen','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Yishuai Du','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Zara Yaqoob','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Ales Flidr','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jesse Galef','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Melody Guan','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Peter Haas','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Max Kesin','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Janos Kramar','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Daniel R. Miller','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Chase Moores','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jacob Trefethen','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jesse Galef','Future of Life Institute','Program Manager','2014-01-01','year','2015-01-01','year','https://www.linkedin.com/in/jessegalef/',NULL,NULL,NULL,NULL,'AI safety')
;
