insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values

     ('Marcus Daniell', 'High Impact Athletes', 'Founder', '2020-06-01', 'month', NULL, NULL, 'https://web.archive.org/web/20201201003557/https://highimpactathletes.com/team https://www.linkedin.com/in/marcus-daniell-313b6893/', NULL, NULL, 'Effective altruism')
    ,('Hugo Inglis', 'High Impact Athletes', 'Founder', '2020-06-01', 'month', NULL, NULL, 'https://web.archive.org/web/20201201003557/https://highimpactathletes.com/team https://www.linkedin.com/in/hugo-inglis/', NULL, NULL, 'Effective altruism')
    ,('Lewis Bollard', 'High Impact Athletes', 'Advisor', '2020-12-01', 'year', NULL, NULL, 'https://web.archive.org/web/20201201003557/https://highimpactathletes.com/team https://www.linkedin.com/in/lewisbollard/', NULL, NULL, 'Effective altruism')
    ,('Charlie Bresler', 'High Impact Athletes', 'Advisor', '2020-12-01', 'year', NULL, NULL, 'https://web.archive.org/web/20201201003557/https://highimpactathletes.com/team', NULL, NULL, 'Effective altruism')
    ,('Josh Daniell', 'High Impact Athletes', 'Advisor', '2020-12-01', 'year', NULL, NULL, 'https://web.archive.org/web/20201201003557/https://highimpactathletes.com/team', NULL, NULL, 'Effective altruism')
    ,('Caroline Daniell', 'High Impact Athletes', 'Legal Counsel', '2020-12-01', 'year', NULL, NULL, 'https://web.archive.org/web/20201201003557/https://highimpactathletes.com/team', NULL, NULL, 'Effective altruism')
    ,('Judith Rensing', 'High Impact Athletes', 'Director of operations', '2021-04-01', 'month', NULL, NULL, 'https://web.archive.org/web/20220104181119/https://highimpactathletes.org/team https://www.linkedin.com/in/judith-rensing/', NULL, 'full-time', 'Effective altruism')
    ,('Peter Singer', 'High Impact Athletes', 'Advisor', '2021-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20220104181119/https://highimpactathletes.org/team', NULL, 'Advisor', 'Effective altruism')
    ,('Jack Lewars', 'High Impact Athletes', 'Advisor', '2021-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20220104181119/https://highimpactathletes.org/team', NULL, 'Advisor', 'Effective altruism')
   