 insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
     ('Geoff Anders', 'Leverage Research', 'Executive Director', '2011-01-01', 'month', NULL, NULL, 'https://web.archive.org/web/20210802231852/https://www.leverageresearch.org/team https://www.linkedin.com/in/geoff-anders-0246b532/ https://web.archive.org/web/20240926205527/https://www.leverageresearch.org/team', "Founded Leverage Research in 2011 to support independent research. Focuses on psychology, sociology, and research methodology. Leads Paradigm Academy. Holds a PhD in Philosophy from Rutgers and a BS in Economics from Wharton.", NULL, NULL) /*Reviewed on 2024-09-26*/ /*Ongoing position*/
    ,('Kerry Vaughan', 'Leverage Research', 'Program Manager', '2019-08-01', 'month', NULL, NULL, 'https://web.archive.org/web/20210802231852/https://www.linkedin.com/in/kerry-vaughan/ https://web.archive.org/web/20240926205527/https://www.leverageresearch.org/team', "Manages the Exploratory Psychology program. Develops tools and coordinates psychology research. Former movement building coordinator and Y Combinator member. Holds a PhD in Philosophy from Rice University.", NULL, NULL) /*Reviewed on 2024-09-26*/ /*Ongoing position*/
    ,('Oliver Carefull', 'Leverage Research', 'Research Communicator and Head of Culture', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20210802231852/ https://web.archive.org/web/20240926205527/https://www.leverageresearch.org/team', "Founding member of Leverage Research in 2011. Worked on collective intelligence, consensus, and methodology. Currently translates technical work and helps develop organizational culture.", NULL, NULL) /*Reviewed on 2024-09-26*/ /*Ongoing position*/
    ,('Melinda Bradley', 'Leverage Research', 'Head of Operations and Events Manager', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20210802231852/ https://web.archive.org/web/20240926205527/https://www.leverageresearch.org/team', "Oversees day-to-day operations and event management. Strong background in psychology, management, and human resources.", NULL, NULL) /*Reviewed on 2024-09-26*/ /*Ongoing position*/
    ,('Daniel Graham', 'Leverage Research', 'History of Science Researcher', '2023-01-01', 'month', NULL, NULL, 'https://web.archive.org/web/20210802231852/ https://web.archive.org/web/20240926205527/https://www.leverageresearch.org/team', "Researches case studies on the history of electricity and technological progress. Former history teacher and museum curator. Holds a PhD in History from the Catholic University of America.", NULL, NULL) /*Reviewed on 2024-09-26*/ /*Ongoing position*/
 

/*.............................................closed positions below.........................................*/
 

    ,('Evan Pence', 'Leverage Research', 'Researcher', '2020-11-01', 'month', '2022-10-01', 'month', 'https://web.archive.org/web/20210802231852/https://www.leverageresearch.org/team https://www.linkedin.com/in/davidevanpence/ https://web.archive.org/web/20220903051419/https://www.leverageresearch.org/team', NULL, NULL, NULL) /*closed position*/
    ,('Larissa Hesketh-Rowe', 'Leverage Research', 'Engagement Specialist, Research Fellows', '2019-12-01', 'month', '2022-11-01', 'month', 'https://web.archive.org/web/20210802231852/https://www.leverageresearch.org/team https://www.linkedin.com/in/larissa-hesketh-rowe/', NULL, 'full-time', NULL) /*closed position*/
    ,('Larissa Hesketh-Rowe', 'Leverage Research', 'Chief Operating Officer and Head of Engagement', '2022-11-01', 'month', '2023-11-01', 'month', 'https://web.archive.org/web/20210802231852/https://www.linkedin.com/in/larissa-hesketh-rowe/', "Manages day-to-day operations and communication strategy. Background in corporate and non-profit marketing. Former CEO of an international charity. Holds a bachelor's in Politics and Sociology from the University of Sussex.", NULL, NULL)  /*closed position*/ 
    ,('Jasen Murray', 'Leverage Research', 'Researcher', '2011-08-01', 'month', '2019-08-01', 'month', 'https://www.linkedin.com/in/jasen-murray-27946517/', NULL, NULL, NULL) /*closed position*/ 
    ,('Emily Crotteau', 'Leverage Research', 'Researcher', '2015-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/emily-crotteau-9b3a6747/', NULL, NULL, NULL)  
;