insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
/*........................................................................Management...................................................................................*/    

('Rachel Adams','Leverhulme Centre for the Future of Intelligence','Research Professor and Executive Director','2026-01-01','month',NULL,NULL,'https://www.linkedin.com/in/rachel-adams-895608255/  https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')



,('Stephen Cave','Leverhulme Centre for the Future of Intelligence','Academic Director | Research Professor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stephen-cave/ https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69702.html https://archive.is/b4bhr https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Maya Indira Ganesh','Leverhulme Centre for the Future of Intelligence','Associate Director (Research Partnerships) | Programme Co-director, Narratives & Justice',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
,('Henry Shevlin','Leverhulme Centre for the Future of Intelligence','Associate Director (Education) | Programme Co-Director, Kinds of Intelligence','2023-04-01','month',NULL,NULL,'https://www.linkedin.com/in/henry-shevlin-b58941b/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
,('Seán Ó hÉigeartaigh','Leverhulme Centre for the Future of Intelligence','Associate Director (Research Strategy) | Programme Director, AI:FAR',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/sean-heigeartaigh/ https://arxiv.org/pdf/1802.07228.pdf https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Eleanor Drage','Leverhulme Centre for the Future of Intelligence','Programme Co-Director, Narratives & Justice | Assistant Research Professor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
,('Rafael Calvo','Leverhulme Centre for the Future of Intelligence','Spoke Co-Lead, Imperial',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Stuart Russell','Leverhulme Centre for the Future of Intelligence','Spoke Lead, Berkeley',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stuart-russell/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Murray Shanahan','Leverhulme Centre for the Future of Intelligence','Spoke Co-Lead, Imperial',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/murray-shanahan/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Adrian Weller','Leverhulme Centre for the Future of Intelligence','Programme Director, Trust and Society',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/adrian-weller/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Huw Price','Leverhulme Centre for the Future of Intelligence','Founder and Strategy Group Chair',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/huw-price/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
/*........................................................................Operations Team...................................................................................*/    
,('Rachel Burgess','Leverhulme Centre for the Future of Intelligence','Institute Manager (ITH)',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Lucy Cavan','Leverhulme Centre for the Future of Intelligence','Postgraduate Co-ordinator',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Viviana Fascianella','Leverhulme Centre for the Future of Intelligence','Centre Co-ordinator',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Yvonne Martin-Portugues','Leverhulme Centre for the Future of Intelligence','Research Project Administrator',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Yiyun Mu','Leverhulme Centre for the Future of Intelligence','Administrative Assistant and Personal Assistant (Centre Director)',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Hannah Tigg','Leverhulme Centre for the Future of Intelligence','Research Grants Co-ordinator',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Hang Vu','Leverhulme Centre for the Future of Intelligence','Finance Co-ordinator',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
,('Lina Vysniauskiene','Leverhulme Centre for the Future of Intelligence','Communication & Alumni Engagement Co-ordinator',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
/*.....................................................................................Academic Staff.............................................................................*/
    ,('Claire Benn','Leverhulme Centre for the Future of Intelligence','University Associate Professor | Director of MPhil Programme',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Lucius Caviola','Leverhulme Centre for the Future of Intelligence','University Assistant Professor | Director of Admissions',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('José Hernández-Orallo','Leverhulme Centre for the Future of Intelligence','Research Professor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/jose-hernandez-orallo/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jonnie Penn','Leverhulme Centre for the Future of Intelligence','Associate Teaching Professor (MSt) | Assistant Research Professor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Dorian Peters','Leverhulme Centre for the Future of Intelligence','University Assistant Professor | Director of Short Courses',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Beryl Pong','Leverhulme Centre for the Future of Intelligence','UKRI Future Leaders Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Christoph Winter','Leverhulme Centre for the Future of Intelligence','University Assistant Professor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Adrià Segarra','Leverhulme Centre for the Future of Intelligence','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Stephen Kyle','Leverhulme Centre for the Future of Intelligence','Research Software Engineer',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,'software engineering','Full-time','AI safety')
    ,('Jacob Stegenga','Leverhulme Centre for the Future of Intelligence','Senior Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jack Casey','Leverhulme Centre for the Future of Intelligence','Teaching Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('William Chan','Leverhulme Centre for the Future of Intelligence','Teaching Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Connor Wright','Leverhulme Centre for the Future of Intelligence','Research Assistant',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Marta Halina','Leverhulme Centre for the Future of Intelligence','Senior Research Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/marta-halina/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Milena Ivanova','Leverhulme Centre for the Future of Intelligence','Senior Teaching Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Jedrzej Niklas','Leverhulme Centre for the Future of Intelligence','Teaching Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Achim Rosemann','Leverhulme Centre for the Future of Intelligence','Teaching Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Ben Slater','Leverhulme Centre for the Future of Intelligence','Research Software Engineer',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,'software engineering','Full-time','AI safety')
    ,('Giulio Corsi','Leverhulme Centre for the Future of Intelligence','Research Fellow | Student Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Amy Gaeta','Leverhulme Centre for the Future of Intelligence','Research Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Katarzyna Nowaczyk-Basińska','Leverhulme Centre for the Future of Intelligence','Assistant Research Professor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Lorenzo Pacchiardi','Leverhulme Centre for the Future of Intelligence','Assistant Research Professor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Jonathan Prunty','Leverhulme Centre for the Future of Intelligence','Research Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Aisha Sobey','Leverhulme Centre for the Future of Intelligence','Research Fellow | Research Program Coordinator',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Tomasz Hollanek','Leverhulme Centre for the Future of Intelligence','Assistant Research Professor | Student Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Apolline Taillandier','Leverhulme Centre for the Future of Intelligence','Research Fellow | Student Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Shahar Avin','Leverhulme Centre for the Future of Intelligence','Senior Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Lucy Cheke','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/lucy-cheke/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Miri Zilka','Leverhulme Centre for the Future of Intelligence','Assistant Professor in Responsible Machine Learning',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Full-time','AI safety')
    ,('Farah Nanji','Leverhulme Centre for the Future of Intelligence','Research Assistant',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Patrick Quinn','Leverhulme Centre for the Future of Intelligence','Research Assistant',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Saide Mobayed Vega','Leverhulme Centre for the Future of Intelligence','Research Assistant',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Asher Kessler','Leverhulme Centre for the Future of Intelligence','Research Assistant',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Matteo Gabriel Mecattaf','Leverhulme Centre for the Future of Intelligence','Research Assistant',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
/*....................................................................................Student Fellows......................................................................................*/
    ,('Ambika Tandon','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Raphael Hernandes','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Lena Wang','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Arik Reuter','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Christoffer Koch Andersen','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Leah Madelaine Schmidt','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Helen Leung','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Suren Pahlevan','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Julien Porquet','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Sammy McKinney','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Aanya Niaz','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Emily Elstub','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Phillip Hintikka Kieval','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Harry Law','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Katie Collins','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Juyeon Heo','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Emma Kallina','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Flavia Saxler','Leverhulme Centre for the Future of Intelligence','Student Fellow','2023-04-01','month',NULL,NULL,'https://www.linkedin.com/in/flavia-saxler-0742b3197/ https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'Intern','AI safety')
    ,('Bill Marino','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Muhammed Alakitan','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Xiang Li','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Myesha Jemison','Leverhulme Centre for the Future of Intelligence','Student Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
/*....................................................................................Visitors......................................................................................*/
    ,('Zimeng Zhang','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Leonie Bossert','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Eva Sánchez Salido','Leverhulme Centre for the Future of Intelligence','Visiting Student',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Oskar Galeev','Leverhulme Centre for the Future of Intelligence','Visiting Student',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Sabrina Küspert','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Demetrius Floudas','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Felicity Fu','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Martha Horn','Leverhulme Centre for the Future of Intelligence','Visiting scholar',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')
    ,('Diana Lengua','Leverhulme Centre for the Future of Intelligence','Visiting Student',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,'graduate student','AI safety')
    ,('Minja Axelsson','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20260227190144/https://www.lcfi.ac.uk/people',NULL,NULL,NULL,NULL,'AI safety')









 



 




    ,('Adrian Weller','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/adrian-weller/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Alan Winfield','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/alan-winfield/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Alison Gopnik','Leverhulme Centre for the Future of Intelligence','External Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/alison-gopnik/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Andrew Snyder-Beattie','Leverhulme Centre for the Future of Intelligence','Research Exercise Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/andrew-snyder-beattie/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Anna Alexandrova','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/anna-alexandrova/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Beth Singler','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/beth-singler/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Carla Zoe Cremer', 'Leverhulme Centre for the Future of Intelligence', 'Affiliated Researcher', '2018-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/carla-zoe-cremer-34073068/', NULL, NULL, subject, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('David Runciman','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/david-runciman/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Demis Hassabis','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/demis-hassabis/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Flavia Saxler', 'Leverhulme Centre for the Future of Intelligence', 'Student Fellow', '2023-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/flavia-saxler-0742b3197/', NULL, NULL, NULL, 'Intern','AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Francesca Rossi','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/francesca-rossi/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Haydn Belfield', 'Leverhulme Centre for the Future of Intelligence', 'Associate Fellow', '2019-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/haydnbelfield/', NULL, NULL, NULL, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Heather Roff','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/heather-roff/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Huw Price','Leverhulme Centre for the Future of Intelligence',NULL,NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/huw-price/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Irene Pellegero Querol', 'Leverhulme Centre for the Future of Intelligence', 'Office Administrator', '2023-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/i-pellegero/', NULL, NULL, NULL, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('José Hernández-Orallo','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/jose-hernandez-orallo/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Kanta Dihal','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/kanta-dihal/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Karina Vold','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/karina-vold/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Kay Firth-Butterfield','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/kay-firth-butterfield/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Kofi Yeboah', 'Leverhulme Centre for the Future of Intelligence', 'Visiting Scholar', '2024-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kofiyeboah/', NULL, NULL, NULL, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
 
    ,('Malak Sadek', 'Leverhulme Centre for the Future of Intelligence', 'PHD Fellow', '2023-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/malaksadek/', NULL, NULL, NULL, 'Full-time','AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Manuela M. Veloso','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/manuela-veloso/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Margaret Boden','Leverhulme Centre for the Future of Intelligence','External Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/margaret-boden/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Marta Halina','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/marta-halina/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Martin Rees','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/martin-rees/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Matthijs M. Maas', 'Leverhulme Centre for the Future of Intelligence', 'Postdoctoral Research Associate', '2020-10-01', 'month', '2022-07-01', 'month', 'https://www.linkedin.com/in/matthijsmaas/', NULL, NULL, NULL, 'Full-time','AI safety') /*closed*/
    ,('Matthijs M. Maas', 'Leverhulme Centre for the Future of Intelligence', 'Research Affiliate', '2022-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/matthijsmaas/', NULL, NULL, NULL, 'Full-time','AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Michael A. Osborne','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/michael-osborne/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Murray Shanahan','Leverhulme Centre for the Future of Intelligence','Spoke Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/murray-shanahan/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Neil Lawrence','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/neil-lawrence/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Niall Donnelly', 'Leverhulme Centre for the Future of Intelligence', 'Collaborator', '2021-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/niall-donnelly-182288111/', NULL, NULL, NULL, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Nick Bostrom','Leverhulme Centre for the Future of Intelligence','Spoke Leader and Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/nick-bostrom/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Philip Pettit','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/philip-pettit/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Rafael A. Calvo', 'Leverhulme Centre for the Future of Intelligence', 'Visiting Fellow', '2018-12-01', 'month', '2020-01-01', 'month', 'https://www.linkedin.com/in/rafael-a-calvo/', NULL, NULL, NULL, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Rafael A. Calvo', 'Leverhulme Centre for the Future of Intelligence', 'Co Lead', '2020-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rafael-a-calvo/', NULL, NULL, NULL, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Rune Nyrup','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/rune-nyrup/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Sarah Dillon','Leverhulme Centre for the Future of Intelligence','Project Leader and Senior Research Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/sarah-dillon/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Stephen Cave','Leverhulme Centre for the Future of Intelligence','Executive Director and Senior Research Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stephen-cave/ https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69702.html https://archive.is/b4bhr',NULL,NULL,NULL,NULL,'AI safety')
    ,('Stephen John','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stephen-john/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Stuart Russell','Leverhulme Centre for the Future of Intelligence','Spoke Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stuart-russell/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Susan Gowans','Leverhulme Centre for the Future of Intelligence','Administrator',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/susan-gowans/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Tameem Adel','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/tameem-adel/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Thomas D. Grant','Leverhulme Centre for the Future of Intelligence','Research Exercise Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/thomas-grant/',NULL,NULL,NULL,NULL,'AI safety')
    ,('Toshie Takahashi', 'Leverhulme Centre for the Future of Intelligence', 'Associate Fellow', '2021-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/toshietakahashi/', NULL, NULL, NULL, NULL,'AI safety') /*Reviewed on 2024-05-02*/ /*current position*/
    ,('Zoubin Ghahramani','Leverhulme Centre for the Future of Intelligence',NULL,NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/zoubin-ghahramani/',NULL,NULL,NULL,NULL,'AI safety')