insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
    ('Oliver Habryka','LessWrong 2.0','Developer','2017-06-01','month',NULL,NULL,'https://github.com/riceissa/aiwatch/issues/8#issue-369865886 https://www.lesswrong.com/about https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.linkedin.com/in/raymond-arnold-07951614/ https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction',NULL,'position','software engineering','full-time','AI safety') /* Updated as of 2022-09-29 */ 
    ,('Matthew Graves','LessWrong 2.0',NULL,'2017-06-01','year',NULL,NULL,'https://www.lesswrong.com/about https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview',NULL,'position',NULL,NULL,'AI safety') /* Updated as of 2022-09-29 */  
    ,('Ben Albert Pace','LessWrong 2.0', 'Core Team','2017-06-01','year',NULL,NULL,'https://www.lesswrong.com/about https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction',NULL,'position',NULL,NULL,'AI safety') /* Updated as of 2022-09-29 */  
    ,('Raymond Arnold','LessWrong 2.0', 'Core Team','2017-09-01','month',NULL,NULL,'https://www.lesswrong.com/about https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview https://www.linkedin.com/in/raymond-arnold-07951614/ https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction',NULL,'position',NULL,NULL,'AI safety') /* Updated as of 2022-09-29 */  
    ,('Harmanas Chopra','LessWrong 2.0',NULL,'2017-06-01','year',NULL,NULL,'https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview',NULL,'position',NULL,NULL,'AI safety')
    ,('Eric Rogstad','LessWrong 2.0',NULL,'2017-06-01','year',NULL,NULL,'https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview',NULL,'position',NULL,NULL,'AI safety')
    ,('James Babcock', 'LessWrong 2.0', 'Chief technology officer', NULL, NULL, NULL, NULL, 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team https://twitter.com/jimrandomh?lang=en', NULL, 'position', NULL, 'full-time', 'AI safety')
    ,('Ruben Bloom', 'LessWrong 2.0', 'Co-Founder', '2018-09-01', 'month', '2021-07-01', 'month', 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team https://www.linkedin.com/in/rubenbloom/ https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction https://www.linkedin.com/in/rubenbloom/', NULL, 'position', NULL, NULL, 'AI safety') /* Updated as of 2022-09-29 */
    ,('Kaj Sotala', 'LessWrong 2.0', 'Moderator', '2017-09-01', 'month', NULL, NULL, 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team https://www.linkedin.com/in/kaj-sotala-85a50210/ https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction', NULL, NULL, NULL, NULL, 'AI safety') /* Updated as of 2022-09-29 */  
    ,('Elizabeth V', 'LessWrong 2.0', 'Moderator', NULL, NULL, NULL, NULL, 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team#Elizabeth_V___Elizabeth https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction', NULL, NULL, NULL, NULL, 'AI safety') /* Updated as of 2022-09-29 */  
;
