insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values


    ('Oliver Habryka', 'Lightcone Infrastructure', 'Team member', '2022-07-11', 'month', NULL, NULL, 'https://web.archive.org/web/20220711174235/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20250908232014/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-09-08*/ /*current position*/
    ,('Ben Albert Pace','Lightcone Infrastructure', 'Team member','2021-10-04','year', NULL ,NULL,'https://web.archive.org/web/20211104091826/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20250908232014/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-09-08*/ /*current position*/
    ,('Robert Mushkatblat', 'Lightcone Infrastructure', 'Team', '2023-02-08', 'month', NULL, NULL, 'https://web.archive.org/web/20230208125445/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20250908232014/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-09-08*/ /*current position*/
    ,('Ruben Bloom', 'Lightcone Infrastructure', 'Team member', '2021-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rubenbloom/ https://web.archive.org/web/20250106024753/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20250908232014/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-09-08*/ /*current position*/
    ,('Jacob Lagerros', 'Lightcone Infrastructure', 'Team member', '2021-07-01', 'month', NULL, NULL, 'https://web.archive.org/web/20211104091826/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20250908232014/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-09-08*/ /*current position*/
    ,('Raymond Arnold', 'Lightcone Infrastructure', 'Team member', '2021-11-04', 'year',  NULL,NULL, 'https://web.archive.org/web/20211104091826/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20250908232014/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-09-08*/ /*current position*/
    ,('Rafe Kennedy', 'Lightcone Infrastructure', 'Team member', '2022-10-01'/*check https://mail.google.com/mail/u/0/?tab=rm&ogbl#search/is/FMfcgzQXKDdJVXxcFDzRKsBWcjwnHxWP*/, 'month', NULL, NULL, 'https://web.archive.org/web/20230208125445/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20250908232014/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*Last consulted Wayback snapshot is from 2025-09-08*/ /*current position*/
/*........................................................closed positions below..........................................................*/
    ,('Ben Albert Pace','Lightcone Infrastructure', 'Core Team','2017-06-01','year','2021-07-01',NULL,'https://www.lesswrong.com/about https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction',NULL,'position',NULL,NULL,'AI safety') /*closed*/  
    ,('Elizabeth Van Nostrand', 'Lightcone Infrastructure', 'Moderator', NULL, NULL, '2021-07-01', NULL, 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team#Elizabeth_V___Elizabeth https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction', NULL, NULL, NULL, NULL, 'AI safety') /*closed*/  
    ,('Eric Rogstad','Lightcone Infrastructure',NULL,'2017-06-01','year','2021-07-01',NULL,'https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview',NULL,'position',NULL,NULL,'AI safety') /*closed*/ 
    ,('Harmanas Chopra','Lightcone Infrastructure',NULL,'2017-06-01','year','2021-07-01',NULL,'https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview',NULL,'position',NULL,NULL,'AI safety') /*closed*/ 
    ,('James Babcock', 'Lightcone Infrastructure', 'Chief technology officer', NULL, NULL, '2021-07-01', NULL, 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team https://twitter.com/jimrandomh?lang=en', NULL, 'position', NULL, 'full-time', 'AI safety') /*closed*/ 
    ,('Kaj Sotala', 'Lightcone Infrastructure', 'Moderator', '2017-09-01', 'month', '2021-07-01', NULL, 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team https://www.linkedin.com/in/kaj-sotala-85a50210/ https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction', NULL, NULL, NULL, NULL, 'AI safety') /*closed*/ 
    ,('Matthew Graves','Lightcone Infrastructure',NULL,'2017-06-01','year','2021-07-01',NULL,'https://www.lesswrong.com/about https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview',NULL,'position',NULL,NULL,'AI safety') /*closed*/   
    ,('Oliver Habryka', 'Lightcone Infrastructure', 'LessWrong 2.0 Project Lead', '2016-12-01', 'month', '2021-10-01', 'month', 'https://www.linkedin.com/in/oliver-habryka-8a585297/ https://web.archive.org/web/20230523165727/https://www.lightconeinfrastructure.com/', 'Lead web developer and a primary admin, he was also responsible for fundraising, hiring, and managing the site''s two employees.', 'position', NULL, NULL, 'AI safety') /*closed*/ 
    ,('Oliver Habryka', 'Lightcone Infrastructure', 'CEO', '2021-11-04', 'year', '2022-05-11', 'month', 'https://web.archive.org/web/20211104091826/https://www.lightconeinfrastructure.com/ https://web.archive.org/web/20220511185623/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*closed*/ 
    ,('Raymond Arnold','Lightcone Infrastructure', 'Core Team','2017-09-01','month','2021-07-01',NULL,'https://www.lesswrong.com/about https://www.lesswrong.com/posts/bxctncS8qcgeCEMGN/lw-2-0-open-beta-starts-9-20 https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview https://www.linkedin.com/in/raymond-arnold-07951614/ https://web.archive.org/web/20240617231841/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*closed*/ 
    ,('Ruben Bloom', 'Lightcone Infrastructure', 'Lesswrong 2.0 co-founder', '2018-09-01', 'month', '2021-07-01', 'month', 'https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team https://www.linkedin.com/in/rubenbloom/ https://web.archive.org/web/20220722125953/https://www.lesswrong.com/posts/aG74jJkiPccqdkK3c/the-lesswrong-team-page-under-construction https://web.archive.org/web/20240617231841/https://www.lightconeinfrastructure.com/', NULL, 'position', NULL, NULL, 'AI safety') /*closed*/ 
;

