insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
    ('Gaia Dempsey', 'Metaculus', 'Chief Executive Officer', '2020-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/gaiadempsey/', NULL, 'full-time', NULL)
   ,('Anthony Aguirre', Metaculus', 'Founder', '2015-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/anthony-aguirre-75751b9/', NULL, NULL, NULL)
   ,('Kris Kitchen', 'Metaculus', 'Consultant', '2016-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kriskitchen/', NULL, NULL, NULL)
   ,('Jacob Lagerros', 'Metaculus', 'Project lead: AI forecasting', '2018-11-01', 'month', '2019-05-01', 'month', 'https://www.linkedin.com/in/jacob-lagerros-48103892/', NULL, NULL, NULL)
   ,('Tamay Besiroglu', 'Metaculus', 'Strategy & Operations Lead', '2018-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tamay-besiroglu/', NULL, NULL, NULL)
   ,('Alysa Stevens', 'Metaculus', 'Student intern', '2020-05-01', 'month', '2020-09-01', 'month', 'https://www.linkedin.com/in/alyssa-stevens-31600291/', NULL, 'intern', NULL)
   ,('Alysa Stevens', 'Metaculus', 'Product Marketing Associate', '2020-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/alyssa-stevens-31600291/', NULL, 'part-time', NULL)
   ,('Juan Cambeiro', 'Metaculus', 'Consultant', '2020-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/juancambeiro1/', NULL, NULL, NULL)
   ,('Daniel Sluder', 'Metaculus', 'Content Coordinator', '2020-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sluddani/', NULL, NULL, NULL)
   ,('David Levine', 'Metaculus', 'Founder, Chief Financial Officer', NULL, NULL, NULL, NULL, 'https://www.metaculus.com/about/', NULL, NULL, NULL)
   ,('Greg Laughlin', 'Metaculus', 'Founder, Research & Development Fellow', NULL, NULL, NULL, NULL, 'https://www.metaculus.com/about/', NULL, NULL, NULL)
   ,('Carroll Wainwright', 'Metaculus', 'Cofounder, data scientist, and software engineer', '2014-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/carroll-wainwright-7690229a/ https://www.metaculus.com/about/', NULL, NULL, NULL)