insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values


  ('Mathieu Bussières', 'NATO Climate Change and Security Centre of Excellence', 'Director', '2023-10-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/ https://www.linkedin.com/in/mathieubussi%C3%A8res/ https://web.archive.org/web/20250929195753/https://ccascoe.org/', NULL, 'full-time', 'Existential risk prevention')  /* Reviewed on 2025-09-10 / / Last available Wayback snapshot date is 2025-09-10 */
 ,('Ulrich Seidenberger', 'NATO Climate Change and Security Centre of Excellence', 'Deputy Director', '2023-08-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/ https://www.linkedin.com/in/ulrich-seidenberger/ https://web.archive.org/web/20250929195753/https://ccascoe.org/', NULL, NULL, 'Existential risk prevention')  /* Reviewed on 2025-09-10 / / Last available Wayback snapshot date is 2025-09-10 */
 ,('François Tinjod', 'NATO Climate Change and Security Centre of Excellence', 'Chief of Staff', '2023-10-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/ https://www.linkedin.com/in/francois-tinjod-5a965b24/ https://web.archive.org/web/20250929195753/https://ccascoe.org/', NULL, NULL, 'Existential risk prevention') /* Reviewed on 2025-09-10 / / Last available Wayback snapshot date is 2025-09-10 */ 
 ,('Kim Vetting', 'NATO Climate Change and Security Centre of Excellence', 'Acting Head of Outreach and Engagement Branch', '2024-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kim-vetting/ https://web.archive.org/web/20250929195753/https://ccascoe.org/', NULL, NULL, 'Existential risk prevention')  /* Reviewed on 2025-09-10 / / Last available Wayback snapshot date is 2025-09-10 */ 
 ,('Katie Woodward', 'NATO Climate Change and Security Centre of Excellence', 'Head of Research, Analysis and Lessons Learned Branch', '2023-10-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/ https://www.linkedin.com/in/katie-w-690800130/ https://web.archive.org/web/20250929195753/https://ccascoe.org/', NULL, NULL, 'Existential risk prevention') /* Reviewed on 2025-09-10 / / Last available Wayback snapshot date is 2025-09-10 */ 
 ,('Gianfranco Pino', 'NATO Climate Change and Security Centre of Excellence', 'Head of Standardization, Concept Development and Experimentation Branch', '2024-08-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/ https://www.linkedin.com/in/gianfranco-pino-607345333/ https://web.archive.org/web/20250929195753/https://ccascoe.org/', NULL, 'full-time', 'Existential risk prevention') /* Reviewed on 2025-09-10 / / Last available Wayback snapshot date is 2025-09-10 */  
 ,('Justin Tynes', 'NATO Climate Change and Security Centre of Excellence', 'Head of Support and Security Branch', '2024-01-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/ https://web.archive.org/web/20250929195753/https://ccascoe.org/', NULL, NULL, 'Existential risk prevention') /* Reviewed on 2025-09-10 / / Last available Wayback snapshot date is 2025-09-10 */   

/* ONLY LINKEDIN */   

 ,('Alexander Kolker', 'NATO Climate Change and Security Centre of Excellence', 'Remote Fellow', '2024-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/alexander-kolker-ph-d-579ba0b0/', NULL, NULL, 'Existential risk prevention') 
 ,('Stephanie Ricci', 'NATO Climate Change and Security Centre of Excellence', 'Web Leader', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/stephanie-ricci-01a305172/', NULL, 'full-time', 'Existential risk prevention') 
 ,('Tyler Stevenson', 'NATO Climate Change and Security Centre of Excellence', 'Intern', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tyler-stevenson-4961591aa/', NULL, 'intern', 'Existential risk prevention') 
 ,('Kassandra Gervasi', 'NATO Climate Change and Security Centre of Excellence', 'Project Intern', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kassandragervasi/', NULL, 'intern', 'Existential risk prevention') 
 ,('Victor Bernaud', 'NATO Climate Change and Security Centre of Excellence', 'Senior Subject Matter Expert', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/victor-bernaud-8367a013a/', NULL, NULL, 'Existential risk prevention') 
,('Jennifer Bélanger', 'NATO Climate Change and Security Centre of Excellence', 'External Relations and Partnerships Officer', '2024-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jenbelanger/', NULL, 'full-time', 'Existential risk prevention') 
,('Hengameh Irandoust', 'NATO Climate Change and Security Centre of Excellence', 'Defence Scientist', '2024-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/hengameh-irandoust-a88773b/', NULL, NULL, 'Existential risk prevention') 
,('Spencer Adrian McMurray', 'NATO Climate Change and Security Centre of Excellence', 'Fellow', '2025-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/spenceramcmurray/', NULL, NULL, 'Existential risk prevention') 
,('Nikolaos G. Stratikis', 'NATO Climate Change and Security Centre of Excellence', 'Steering Committee National Representative', '2024-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nikolaos-niko-g-stratikis-a6349634a/', NULL, 'full-time', 'Existential risk prevention') 
,('Bruno Charbonneau', 'NATO Climate Change and Security Centre of Excellence', 'Conseiller scientifique senior', '2024-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/bruno-charbonneau-a67b7059/', NULL, NULL, 'Existential risk prevention') 
,('Randy Marroquin', 'NATO Climate Change and Security Centre of Excellence', 'Information Technology Infrastructure Specialis', '2024-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/randy-marroquin-7208861b4/', NULL, 'full-time', 'Existential risk prevention') 
,('Mohamed Rahmo', 'NATO Climate Change and Security Centre of Excellence', 'Senior communication advisor', '2024-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rahmo/', NULL, 'full-time', 'Existential risk prevention') 
,('Martin Aarnaes', 'NATO Climate Change and Security Centre of Excellence', 'Head of Outreach and Engagement Branch', '2023-11-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/ https://www.linkedin.com/in/martin-aarnaes-79a367286/', NULL, NULL, 'Existential risk prevention') 
,('Reiner Zimmermann', 'NATO Climate Change and Security Centre of Excellence', 'Head Research, Analysis and Lessons Learned Branch', '2024-12-01', NULL, NULL, NULL, 'https://web.archive.org/web/20241217133001/https://ccascoe.org/our-story/', NULL, NULL, 'Existential risk prevention') 

