insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
    ('Andreas Stuhlmüller','Ought','President',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Owain Evans','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Paul Christiano','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Noah Goodman','Ought','Advisor',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,'advisor','AI safety')
    ,('Ben Rachbach','Ought','Interim Head of Operations',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Andrew Schreiber','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Ben West','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Ben Goldhaber','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Zachary Miller','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Milan Griffes','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Ozzie Gooen','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Ben Weinstein-Raun','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Tom McGrath','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Zac Kenton','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Ryan Carey','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Neal Jean','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Girish Sastry','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Chris Cundy','Ought','Collaborator',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,NULL,'AI safety')
    ,('Andreas Stuhlmüller','Ought','Board member',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,'board member','AI safety')
    ,('Owain Evans','Ought','Board member',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,'board member','AI safety')
    ,('Paul Christiano','Ought','Board member',NULL,NULL,NULL,NULL,'http://www.webcitation.org/query?url=https%3A%2F%2Fought.org%2Fteam&date=2018-10-17',NULL,'position',NULL,'board member','AI safety')
;
