 insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
  
  
 ('Robert Trager', 'Oxford Martin AI Governance Initiative', 'Director', '2023-01-01', 'month', NULL, NULL, 'https://web.archive.org/web/20230921114929/https://www.oxfordmartin.ox.ac.uk/ai-governance/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */  
,('Michael Osborne', 'Oxford Martin AI Governance Initiative', 'Professor of Machine Learning', '2023-09-01', 'year', NULL, NULL, 'https://web.archive.org/web/20230921114929/https://www.oxfordmartin.ox.ac.uk/ai-governance/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */ 
,('Nikki Sun', 'Oxford Martin AI Governance Initiative', 'Programme Manager', '2024-01-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240229080514/https://www.oxfordmartin.ox.ac.uk/ai-governance/ https://www.linkedin.com/in/nikki-sun/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, 'full-time', 'AI safety')  /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */ 
,('Marta Ziosi', 'Oxford Martin AI Governance Initiative', 'Postdoctoral Researcher', '2024-04-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240502222305/https://www.oxfordmartin.ox.ac.uk/ai-governance/ https://www.linkedin.com/in/marta-ziosi-3342007a/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, 'full-time', 'AI safety')  /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */  
,('Nicholas Caputo', 'Oxford Martin AI Governance Initiative', 'Legal Researcher', '2024-09-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241119110127/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/nickacaputo/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, 'full-time', 'AI safety')  /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */  
,('Fazl Barez', 'Oxford Martin AI Governance Initiative', 'Senior Postdoctoral Research Fellow', '2024-09-01', 'month', NULL, NULL, 'https://web.archive.org/web/20250116040041/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/fbarez/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */   
,('Ben Garfinkel', 'Oxford Martin AI Governance Initiative', 'Postdoctoral Researcher', '2023-01-01', 'month', NULL, NULL, 'https://web.archive.org/web/20241004031157/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */ 
,('Sam Daws', 'Oxford Martin AI Governance Initiative', 'Senior Advisor', '2024-02-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240229080514/https://www.oxfordmartin.ox.ac.uk/ai-governance/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */   
,('Henry de Zoete', 'Oxford Martin AI Governance Initiative', 'Senior Advisor and Visiting Fellow', '2024-10-01', 'month', NULL, NULL, 'https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/henry-de-zoete-obe-aa01835/ https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, 'part-time', 'AI safety')  /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */   
,('Allan Dafoe', 'Oxford Martin AI Governance Initiative', 'Visiting Fellow', '2024-08-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */    
,('Julia C. Morse', 'Oxford Martin AI Governance Initiative', 'Visiting Fellow', '2024-08-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20251006235237/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  /* Reviewed on 2025-10-06 / / Last available Wayback snapshot date is 2025-10-06 */   

/* LINKEDIN */   

,('Sumaya Nur Adan', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-06-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/sumaya-nur-adan/', NULL, NULL, NULL, NULL, 'AI safety')  
,('José Jaime Villalobos', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-02-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/jos%C3%A9-jaime-villalobos-bb77a4114/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Patricia Paskov', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2025-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/patricia-paskov/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Kayla Blomquist', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2023-10-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240229080514/https://www.oxfordmartin.ox.ac.uk/ai-governance/ https://www.linkedin.com/in/kayla-blomquist-1129a493/ https://web.archive.org/web/20240721160701/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')   
,('Claire Dennis', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-01-01', 'year', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/claireedithdennis/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Ben Harack', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-07-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/benharack/', NULL, NULL, NULL, 'part-time', 'AI safety')  
,('Julian Jacobs', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-06-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/julian-jacobs-a729b87a/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Malou van Draanen Glismann', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/malou-van-draanen-glismann/', NULL, NULL, NULL, 'full-time', 'AI safety')  
,('Jan Króliński', 'Oxford Martin AI Governance Initiative', 'Graduate Researcher', '2025-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/krolinski/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Mark Robinson', 'Oxford Martin AI Governance Initiative', 'Senior Advisor', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/mark-robinson-3594132b/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Keir Reid', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2025-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/keir-reid/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Orsolya Dobe', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/orsolya-dobe-9ba499163/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Charles Martinet', 'Oxford Martin AI Governance Initiative', 'Research', '2024-10-02', 'month', NULL, NULL, 'https://www.linkedin.com/in/charles-martinet/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Miro Pluckebaum', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2025-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/orsolya-dobe-9ba499163/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Janvi Ahuja', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2025-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/janvi-ahuja-792bb8150/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Milan Gandhi', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-06-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/gandhimilan/', NULL, NULL, NULL, 'part-time', 'AI safety')  
,('Lama Saouma', 'Oxford Martin AI Governance Initiative', 'Visiting Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lama-saouma-84892881/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Jeba Sania', 'Oxford Martin AI Governance Initiative', 'Technical AI Governance Research Fellow', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jeba-sania/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Ze Shen Chin', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/chinzeshen/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Kwan Yee Ng', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kwanyeeng/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Luise Eder', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/luise-eder-789909175/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Elias Groll', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/eliasgroll/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Ben Bucknall', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-05-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/ben-s-bucknall/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Scott Singer', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-05-01', 'month', NULL, NULL, 'http://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/scott-singer/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Benedictus Djanuar', 'Oxford Martin AI Governance Initiative', 'Graduate Research Assistant', '2025-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/benedictusdjanuar/', NULL, NULL, NULL, NULL, 'AI safety')  
,('Saad Siddiqui', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-05-01', 'month', NULL, NULL, 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/saad-siddiqui-02b4a7144/', NULL, NULL, NULL, NULL, 'AI safety') 

/* CLOSED */   

,('Charles Martinet', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-04-01', 'month', '2024-10-01', 'month', 'http://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://www.linkedin.com/in/charles-martinet/ https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Toby Ord', 'Oxford Martin AI Governance Initiative', 'Senior Researcher', '2024-05-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20240502222305/https://www.oxfordmartin.ox.ac.uk/ai-governance/ https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Naima Green-Riley', 'Oxford Martin AI Governance Initiative', 'Visiting Fellow', '2024-08-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Tim Fist', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-08-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Noa Zilberman', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-08-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Leonie Koessler', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-08-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Sihao Huang', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-08-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Elisabeth Siegel', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-08-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20240801085624/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  
,('Lucia Velasco', 'Oxford Martin AI Governance Initiative', 'Research Affiliate', '2024-10-01', 'month', '2025-02-01', 'month', 'https://web.archive.org/web/20241004031157/https://www.oxfordmartin.ox.ac.uk/ai-governance https://web.archive.org/web/20250221165836/https://www.oxfordmartin.ox.ac.uk/ai-governance', NULL, NULL, NULL, NULL, 'AI safety')  

