
('Maneka Gandhi', 'People For Animals Public Policy Foundation', 'Patron', '2025-10-17', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20251017111139/https://pfappf.com/meet-our-team-2/ https://web.archive.org/web/20260922191519/https://pfappf.com/meet-our-team-2/', NULL, NULL, 'Animal welfare'), /*Last checked Wayback snapshot is from 2026-09-22*/
('Gauri Maulekhi', 'People For Animals Public Policy Foundation', 'Trustee', '2025-10-17', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20251017111139/https://pfappf.com/meet-our-team-2/ https://web.archive.org/web/20260922191519/https://pfappf.com/meet-our-team-2/', NULL, 'board member', 'Animal welfare'), /*Last checked Wayback snapshot is from 2026-09-22*/
('Priyanka Bangari', 'People For Animals Public Policy Foundation', 'Trustee', '2020-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/priyanka-bangari-014a9365/ https://web.archive.org/web/20251017111139/https://pfappf.com/meet-our-team-2/ https://web.archive.org/web/20260922191519/https://pfappf.com/meet-our-team-2/', NULL, 'board member', 'Animal welfare'), /*Last checked Wayback snapshot is from 2026-09-22*/
('Jayasimha Nuggehalli', 'People For Animals Public Policy Foundation', 'Trustee', '2025-10-17', 'multi-year', NULL, NULL, 'https://web.archive.org/web/20251017111139/https://pfappf.com/meet-our-team-2/ https://web.archive.org/web/20260922191519/https://pfappf.com/meet-our-team-2/', NULL, 'board member', 'Animal welfare'), /*Last checked Wayback snapshot is from 2026-09-22*/
('Gayathri Sangu', 'People For Animals Public Policy Foundation', 'Ahimsa Fellow', '2025-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/gayathrisangu/', NULL, 'full-time', 'Animal welfare'),
('Varuna Verma', 'People For Animals Public Policy Foundation', 'Project Manager, Corporate Engagement', '2024-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/varuna-verma-80713522/', NULL, 'full-time', 'Animal welfare'),
('Trishna Moulick', 'People For Animals Public Policy Foundation', 'Fundraising Manager', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/trishna-moulick-424323173/', NULL, 'full-time', 'Animal welfare'),
('Sanna Singh', 'People For Animals Public Policy Foundation', 'Senior Program Manager', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sanna-singh-2194231b2/', NULL, 'full-time', 'Animal welfare'),
('Udaya Simha N G', 'People For Animals Public Policy Foundation', 'Director, Applied Animal Advocacy Certificate Program', '2025-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/dr-udaya-simha-n-g-45687a19/', NULL, 'full-time', 'Animal welfare'),
('Udaya Simha N G', 'People For Animals Public Policy Foundation', 'Program Coordinator, Ahimsa Fellowship', '2026-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/dr-udaya-simha-n-g-45687a19/', NULL, 'full-time', 'Animal welfare'),
('Shaalini Agrawal', 'People For Animals Public Policy Foundation', 'Senior Consultant', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/shaalini-agrawal-9ab209127/', NULL, 'full-time', 'Animal welfare'),
('Sunayana Sibal', 'People For Animals Public Policy Foundation', 'Director of Public Policy', '2024-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sunayana-sibal-314437178/', NULL, 'full-time', 'Animal welfare'),
('Simranjeet Singh', 'People For Animals Public Policy Foundation', 'Ahimsa Fellow', '2025-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/simranjeet-singh-509460190/', NULL, NULL, 'Animal welfare'),
('Rohit Bhardwaj', 'People For Animals Public Policy Foundation', 'Ahimsa Fellow', '2024-09-01', 'month', '2025-05-01', 'month', 'https://www.linkedin.com/in/rohit-bhardwaj-506434ab/', NULL, 'full-time', 'Animal welfare'), /*Closed*/
('Rohit Bhardwaj', 'People For Animals Public Policy Foundation', 'Consultant', '2025-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rohit-bhardwaj-506434ab/', NULL, 'full-time', 'Animal welfare'),
('Divya Maria', 'People For Animals Public Policy Foundation', NULL, '2026-09-22', 'multi-year', NULL, NULL, 'https://www.linkedin.com/in/divya-maria-5b4b2596/', NULL, NULL, 'Animal welfare');