insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
('Janek van Tilborg', 'ProVeg International', 'Senior Legal Counsel & Legal Team Lead', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/janek-van-tilborg-2280619b/', NULL, 'full-time', 'Animal welfare'),
('Kiggundu Ronald Reagan', 'ProVeg International', 'ProVeg International Youth Board', '2026-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kiggundu-ronald-reagan-772a35262/', NULL, 'part-time', 'Animal welfare'),
('Virginia C.', 'ProVeg International', 'Project Manager', '2022-07-01', 'month', '2024-06-01', 'month', 'https://www.linkedin.com/in/virginia-c-0b565522/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Virginia C.', 'ProVeg International', 'Senior Food Industry Manager', '2024-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/virginia-c-0b565522/', NULL, 'full-time', 'Animal welfare'),
('Greta Scott', 'ProVeg International', 'Youth Board Member', '2026-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/greta-scott/', NULL, 'board member', 'Animal welfare'),
('Pascal Blanché', 'ProVeg International', 'IT-Systemadministrator', '2024-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/pascal-blanch%C3%A9/', NULL, 'part-time', 'Animal welfare'),
('Sebastian Joy', 'ProVeg International', 'Founding President of ProVeg International', '2008-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sebastian-joy-78bb54122/ https://web.archive.org/web/20240122234302/https://proveg.org/about-us/ https://web.archive.org/web/20251201084101/https://proveg.org/about-us/', NULL, NULL, 'Animal welfare') /*Last checked Wayback snapshot is from 2025-12-01*/,
('Viola Pizzuto', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/viola-pizzuto-264214324/', NULL, 'full-time', 'Animal welfare'),
('Vivian (Wen-Huei) Chen', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/vivianwhchen/', NULL, NULL, 'Animal welfare'),
('Rachel Gifford', 'ProVeg International', 'Senior Policy Researcher', '2025-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/giffordrachel/', NULL, 'part-time', 'Animal welfare'),
('Lucas Oliveira', 'ProVeg International', 'Freelancer Nutritionist', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lucasfonsecarodriguesoliveira/', NULL, 'contractor', 'Animal welfare'),
('Saharsh Oswal', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/saharshoswal/', NULL, 'board member', 'Animal welfare'),
('Tony de Silva', 'ProVeg International', 'Monitoring And Evaluation Coordinator', '2021-09-01', 'month', '2024-03-01', 'month', 'https://www.linkedin.com/in/tonydesilva/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Tony de Silva', 'ProVeg International', 'Monitoring and Evaluation Manager', '2024-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tonydesilva/', NULL, 'full-time', 'Animal welfare'),
('Sara Clemm', 'ProVeg International', 'Graphic Designer', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sara-clemm-00b085202/', NULL, 'full-time', 'Animal welfare'),
('Geofrey Junior Waako', 'ProVeg International', 'ProVeg International Youth Board', '2024-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/geofrey-junior-waako/', NULL, 'part-time', 'Animal welfare'),
('Soizic Larcher', 'ProVeg International', 'EU Policy Officer', '2023-12-01', 'month', '2025-03-01', 'month', 'https://www.linkedin.com/in/soiziclarcher/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Soizic Larcher', 'ProVeg International', 'EU Policy Manager', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/soiziclarcher/', NULL, 'full-time', 'Animal welfare'),
('Sharon Gakii', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/climatesharon/', NULL, 'contractor', 'Animal welfare'),
('Beatrice Rocca', 'ProVeg International', 'UN Policy Manager (Biodiversity)', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/beatrice-rocca/', NULL, 'full-time', 'Animal welfare'),
('Avik Banerjee', 'ProVeg International', 'Senior Manager (PV India)', '2025-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/avik-banerjee-276b5967/', NULL, 'full-time', 'Animal welfare'),
('Fredrick Kilonzo', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/fredrick-kilonzo-4901171a6/', NULL, 'contractor', 'Animal welfare'),
('Earl Ackon Cromwell', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/earl-ackon-cromwell-258a44208/', NULL, 'contractor', 'Animal welfare')
,
('Eve Mosley', 'ProVeg International', 'Global Head of Development', '2025-10-01', 'month', NULL, NULL, NULL, NULL, 'full-time', 'Animal welfare'),
('Kati Radloff', 'ProVeg International', 'Assistant of President', '2021-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kati-radloff-5ba597266/', NULL, 'contractor', 'Animal welfare'),
('Dom Altomari', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/dom-altomari/', NULL, 'part-time', 'Animal welfare'),
('Narhari Gupta', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/narharigupta/', NULL, 'part-time', 'Animal welfare'),
('Yuna Lee', 'ProVeg International', 'Public Food Coordinator', '2025-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/yunaleeee/', NULL, 'full-time', 'Animal welfare'),
('Teresa Romagna', 'ProVeg International', 'HR Officer', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/teresa-romagna-330372207/', NULL, 'full-time', 'Animal welfare'),
('Teresa Romagna', 'ProVeg International', 'Senior HR Manager', '2022-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/teresa-romagna-330372207/', NULL, 'full-time', 'Animal welfare')
,
('Renato Pichler', 'ProVeg International', 'Bundesleitungs-Mitglied', '2019-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/renato-pichler/', NULL, 'board member', 'Animal welfare'),
('Cheryl Chang Lin', 'ProVeg International', 'Program Manager', '2022-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cheryl-chang-lin-30885524a/', NULL, 'contractor', 'Animal welfare'),
('Ignacia Sáiz Lynch', 'ProVeg International', 'International Events Coordinator', '2023-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ignaciasaiz/', NULL, 'full-time', 'Animal welfare'),
('Yi Qian Oo', 'ProVeg International', 'Nutritionist', '2025-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/yi-qian-oo-a851b28b/', NULL, NULL, 'Animal welfare'),
('Valentina Gallani', 'ProVeg International', 'Health and Nutrition Manager', '2022-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/valentina-gallani-991bab183/', NULL, 'part-time', 'Animal welfare')
,
('Lucia Hortelano', 'ProVeg International', 'EU Policy Manager', '2022-09-01', 'month', '2023-10-01', 'month', 'https://www.linkedin.com/in/lucia-hortelano/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Lucia Hortelano', 'ProVeg International', 'EU Senior Policy Manager', '2023-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lucia-hortelano/', NULL, 'full-time', 'Animal welfare'),
('Juliette Tronchon', 'ProVeg International', 'Volunteer Coordinator', '2020-01-01', 'month', '2021-04-01', 'month', 'https://www.linkedin.com/in/juliette-tronchon/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Juliette Tronchon', 'ProVeg International', 'Policy and Public Affairs Specialist International', '2021-01-01', 'month', '2022-10-01', 'month', 'https://www.linkedin.com/in/juliette-tronchon/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Juliette Tronchon', 'ProVeg International', 'Senior Policy and Public Affairs Specialist', '2022-10-01', 'month', '2024-01-01', 'month', 'https://www.linkedin.com/in/juliette-tronchon/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Juliette Tronchon', 'ProVeg International', 'Head of UN Affairs', '2024-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/juliette-tronchon/', NULL, 'full-time', 'Animal welfare'),
('Bianca Maria Galatanu', 'ProVeg International', 'UN Advocacy Assistant', '2024-08-01', 'month', '2025-02-01', 'month', 'https://www.linkedin.com/in/bianca-maria-galatanu-62a47a223/', NULL, 'intern', 'Animal welfare') /*Closed*/,
('Bianca Maria Galatanu', 'ProVeg International', 'UN Policy Officer', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/bianca-maria-galatanu-62a47a223/', NULL, 'full-time', 'Animal welfare'),
('Chloe Thompson', 'ProVeg International', 'Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/chloe-thompson-a3700215a/', NULL, 'board member', 'Animal welfare'),
('Susann Schmiedgen', 'ProVeg International', 'Monitoring, Evaluation & Learning Manager', '2021-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/susannschmiedgen/', NULL, NULL, 'Animal welfare')
,
('Heloísa Rigolon', 'ProVeg International', 'Youth Board Member', '2024-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/heloisarigolon/', NULL, 'board member', 'Animal welfare'),
('Josh Bisig', 'ProVeg International', 'Senior Project Manager', '2022-11-01', 'month', '2025-01-01', 'month', 'https://www.linkedin.com/in/joshbisig/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Josh Bisig', 'ProVeg International', 'Senior Policy Research Manager', '2025-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/joshbisig/', NULL, 'full-time', 'Animal welfare'),
('Juan David Amaya', 'ProVeg International', 'Youth Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/juandavid-am/', NULL, 'board member', 'Animal welfare'),
('Carol Destro', 'ProVeg International', 'International Development Manager', '2024-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/carol-destro-62516459/', NULL, 'full-time', 'Animal welfare'),
('Joanna Trewern Jimenez', 'ProVeg International', 'Head of Research', '2023-10-01', 'month', '2024-04-01', 'month', 'https://www.linkedin.com/in/joanna-trewern-jimenez-884425113/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Joanna Trewern Jimenez', 'ProVeg International', 'Director of Partnerships and Institutional Engagement', '2024-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/joanna-trewern-jimenez-884425113/ https://web.archive.org/web/20240717122921/https://proveg.org/about-us/ https://web.archive.org/web/20251201084101/https://proveg.org/about-us/', NULL, 'full-time', 'Animal welfare') /*Last checked Wayback snapshot is from 2025-12-01*/,
('Isabel Hughes', 'ProVeg International', 'International Growth Manager', '2023-11-01', 'month', '2024-08-01', 'month', 'https://www.linkedin.com/in/isabelmayhughes/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Isabel Hughes', 'ProVeg International', 'Head of International Growth', '2024-08-01', 'month', '2026-04-01', 'month', 'https://www.linkedin.com/in/isabelmayhughes/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Isabel Hughes', 'ProVeg International', 'Head of International Policy and Advocacy', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/isabelmayhughes/', NULL, 'full-time', 'Animal welfare')
,
('Swantje Tomalak', 'ProVeg International', 'Event Program Manager', '2021-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/stomalak/', NULL, 'contractor', 'Animal welfare'),
('Matthias Schillig', 'ProVeg International', 'Digital Marketing Manager', '2015-04-01', 'month', '2016-12-01', 'month', 'https://www.linkedin.com/in/matthias-schillig-838270106/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Matthias Schillig', 'ProVeg International', 'Head Of Communications, Germany', '2017-01-01', 'month', '2020-04-01', 'month', 'https://www.linkedin.com/in/matthias-schillig-838270106/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Matthias Schillig', 'ProVeg International', 'Senior Organisational Development Manager', '2020-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/matthias-schillig-838270106/', NULL, 'full-time', 'Animal welfare'),
('Sophie Gunter', 'ProVeg International', 'Webdesigner', '2018-09-01', 'month', '2022-05-01', 'month', 'https://www.linkedin.com/in/sophie-gunter/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Sophie Gunter', 'ProVeg International', 'Graphic Designer', '2022-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sophie-gunter/', NULL, 'part-time', 'Animal welfare'),
('Patrycja Homa', 'ProVeg International', 'President of the Management Board (Country Director)', '2017-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/patrycja-homa-545344a1/', NULL, 'full-time', 'Animal welfare'),
('Adrian Schultze', 'ProVeg International', 'Projektmanager', '2017-08-01', 'month', '2022-04-01', 'month', 'https://www.linkedin.com/in/adrian-schultze-035bb51a4/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Adrian Schultze', 'ProVeg International', 'Full-stack Developer', '2020-08-01', 'month', '2023-04-01', 'month', 'https://www.linkedin.com/in/adrian-schultze-035bb51a4/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Adrian Schultze', 'ProVeg International', 'Senior IT Specialist', '2023-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/adrian-schultze-035bb51a4/', NULL, NULL, 'Animal welfare')
,
('Morvah George', 'ProVeg International', 'Corporate Engagement Manager', '2026-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/morvahgeorge/', NULL, NULL, 'Animal welfare'),
('Njoke Raisa', 'ProVeg International', 'Youth Board Member', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/njoke-raisa-a29707164/', NULL, 'full-time', 'Animal welfare'),
('Daniel Braune', 'ProVeg International', 'Executive Assistant', '2016-06-01', 'month', '2017-05-01', 'month', 'https://www.linkedin.com/in/daniel-braune/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Daniel Braune', 'ProVeg International', 'Head Of Research', '2017-06-01', 'month', '2023-10-01', 'month', 'https://www.linkedin.com/in/daniel-braune/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Daniel Braune', 'ProVeg International', 'Food Systems Sustainability Lead', '2023-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/daniel-braune/', NULL, 'full-time', 'Animal welfare'),
('Nina Stummvoll', 'ProVeg International', 'HR Manager at ProVeg International', '2018-08-01', 'month', '2022-07-01', 'month', 'https://www.linkedin.com/in/nina-stummvoll-78a9b887/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Nina Stummvoll', 'ProVeg International', 'Senior HR Manager', '2022-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nina-stummvoll-78a9b887/', NULL, NULL, 'Animal welfare'),
('Nina Stummvoll', 'ProVeg International', 'Senior People & Culture Manager', '2023-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nina-stummvoll-78a9b887/', NULL, NULL, 'Animal welfare')
,
('Nora Winter', 'ProVeg International', 'HR & Volunteer Manager', '2013-06-01', 'month', '2017-06-01', 'month', 'https://www.linkedin.com/in/nora-winter-56363b26/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Nora Winter', 'ProVeg International', 'HR-Manager, Head of Support', '2017-07-01', 'month', '2018-05-01', 'month', 'https://www.linkedin.com/in/nora-winter-56363b26/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Nora Winter', 'ProVeg International', 'Head of HR and Volunteer Management', '2018-06-01', 'month', '2021-09-01', 'month', 'https://www.linkedin.com/in/nora-winter-56363b26/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Nora Winter', 'ProVeg International', 'International Head of HR & Volunteer Management', '2021-10-01', 'month', '2023-04-01', 'month', 'https://www.linkedin.com/in/nora-winter-56363b26/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Nora Winter', 'ProVeg International', 'Director of People and Culture', '2023-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nora-winter-56363b26/ https://web.archive.org/web/20241206200551/https://proveg.org/about-us/ https://web.archive.org/web/20251201084101/https://proveg.org/about-us/', NULL, 'full-time', 'Animal welfare') /*Last checked Wayback snapshot is from 2025-12-01*/,
('Tobias Fichtel', 'ProVeg International', 'Junior PR-Manager', '2023-11-01', 'month', '2024-09-01', 'month', 'https://www.linkedin.com/in/tobias-fichtel-71a1a9153/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Tobias Fichtel', 'ProVeg International', 'PR-Manager', '2024-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tobias-fichtel-71a1a9153/', NULL, 'full-time', 'Animal welfare'),
('Salomón Derreza', 'ProVeg International', 'Gruppenleiter', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/salom%C3%B3n-derreza-9675525b/', NULL, NULL, 'Animal welfare'),
('Jessica Baker', 'ProVeg International', 'International Digital Project Administrator', '2023-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/baker36/', NULL, NULL, 'Animal welfare'),
('David Aleksov', 'ProVeg International', 'People & Culture Manager (International Recruiting)', '2024-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/davidaleksov/', NULL, 'full-time', 'Animal welfare'),
('Annalena Janentzky', 'ProVeg International', 'Werkstudentin Food & Acounting', '2023-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/annalena-janentzky-070173273/', NULL, 'part-time', 'Animal welfare')
,
('Stephanie Maw', 'ProVeg International', 'Policy Manager', '2023-05-01', 'month', '2024-01-01', 'month', 'https://www.linkedin.com/in/stephanie-maw/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Stephanie Maw', 'ProVeg International', 'Senior UN Policy & Advocacy Manager', '2024-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/stephanie-maw/', NULL, 'full-time', 'Animal welfare'),
('Sophia Marte', 'ProVeg International', 'Student Fundraiser', '2020-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sophia-marte-297239200/', NULL, NULL, 'Animal welfare'),
('Lena Renz', 'ProVeg International', 'PR Manager Germany', '2021-10-01', 'month', '2022-03-01', 'month', 'https://www.linkedin.com/in/lenarenz/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Lena Renz', 'ProVeg International', 'Team Lead Communications Germany', '2022-04-01', 'month', '2023-05-01', 'month', 'https://www.linkedin.com/in/lenarenz/', 'Temporary position, due to family leave', 'full-time', 'Animal welfare') /*Closed*/,
('Lena Renz', 'ProVeg International', 'Senior PR Manager Germany', '2023-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lenarenz/', NULL, 'full-time', 'Animal welfare'),
('Alessandra Möhle', 'ProVeg International', 'Advisory role on organisational development and strategy', '2024-11-01', 'month', '2025-07-01', 'month', 'https://www.linkedin.com/in/alessandra-m%C3%B6hle-073041192/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Alessandra Möhle', 'ProVeg International', 'Global Chief of Staff', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/alessandra-m%C3%B6hle-073041192/', NULL, 'full-time', 'Animal welfare'),
('Michael Kaiser', 'ProVeg International', 'V-Label Customer Success Manager', '2022-05-01', 'month', '2023-09-01', 'month', 'https://www.linkedin.com/in/michael-kaiser-59543b219/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Michael Kaiser', 'ProVeg International', 'V-Label Business Consultant', '2023-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/michael-kaiser-59543b219/', NULL, 'full-time', 'Animal welfare'),
('Elizabeth Álvarez', 'ProVeg International', 'International Development Manager', '2026-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/elizabethalvarezmar/', NULL, 'full-time', 'Animal welfare')
,
('Isabell Kaiser', 'ProVeg International', 'V-Label Junior Business Development Manager/Sales', '2024-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/isabell-kaiser-959a51293/', NULL, 'contractor', 'Animal welfare'),
('Liz Kelliher', 'ProVeg International', 'Executive and Operations Team Assistant', '2026-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/liz-kelliher-854123a4/', NULL, NULL, 'Animal welfare'),
('Celeste Rodriguez - Portugues', 'ProVeg International', 'Events Coordinator', '2017-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/celeste-rodriguez-portugues-ba015b64/', NULL, NULL, 'Animal welfare'),
('Flora S', 'ProVeg International', 'Project Management and Controlling', '2016-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/flora-s-a2036026/', NULL, NULL, 'Animal welfare'),
('Margaret Shapiro', 'ProVeg International', 'Supporter Engagement & Administrative Coordinator', '2022-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/margaret-shapiro-4248043b/', NULL, NULL, 'Animal welfare'),
('Giovanna Diniz', 'ProVeg International', 'Social Media Volunteer', '2025-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/giovanna-diniz-santos/', NULL, 'full-time', 'Animal welfare'),
('Phoenix Sage', 'ProVeg International', 'Director of Operations and Finance', '2021-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/phoenix-sage-ab7932242/', NULL, 'full-time', 'Animal welfare')
,
('Martin Ranninger', 'ProVeg International', 'President', '2018-05-01', 'month', '2021-08-01', 'month', 'https://www.linkedin.com/in/martinranninger/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Martin Ranninger', 'ProVeg International', 'Country Director, ProVeg Czechia', '2021-08-01', 'month', '2023-08-01', 'month', 'https://www.linkedin.com/in/martinranninger/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Martin Ranninger', 'ProVeg International', 'Country Co-Director, ProVeg Czechia', '2023-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/martinranninger/', NULL, NULL, 'Animal welfare'),
('Melanie Jaecques', 'ProVeg International', 'Grants Program Intervention Specialist', '2020-04-01', 'month', '2023-01-01', 'month', 'https://www.linkedin.com/in/melanie-jaecques-63188925/', NULL, 'contractor', 'Animal welfare') /*Closed*/,
('Melanie Jaecques', 'ProVeg International', 'Movement Building and Intervention Specialist', '2023-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/melanie-jaecques-63188925/', NULL, 'contractor', 'Animal welfare'),
('Michéle Deutschmann', 'ProVeg International', 'Fundraiser', '2024-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/micheledeutschmann/', NULL, 'part-time', 'Animal welfare'),
('maureen vande cappelle', 'ProVeg International', 'Country Co-Director ProVeg Belgium', '2022-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maureen-vande-cappelle-8b13b3171/', NULL, 'part-time', 'Animal welfare'),
('Jane Wang', 'ProVeg International', 'Senior Strategic Project Manager', '2025-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jane-wang-21005b57/', NULL, 'full-time', 'Animal welfare')
,
('Stephanie Chen', 'ProVeg International', 'International Projects Manager/Advisor', '2024-08-01', 'month', '2026-07-01', 'month', 'https://www.linkedin.com/in/stephanie-yun-chen-chen/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Stephanie Chen', 'ProVeg International', 'International Programme Manager', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/stephanie-yun-chen-chen/', NULL, NULL, 'Animal welfare'),
('Stuti P.', 'ProVeg International', 'Asia-Pacific-Africa Grants Coordinator', '2024-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/stuti-parekh/', NULL, 'part-time', 'Animal welfare'),
('Stuti P.', 'ProVeg International', 'Global Grants and Engagement Manager', '2025-09-01', 'month', '2025-12-01', 'month', 'https://www.linkedin.com/in/stuti-parekh/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Ria Rehberg', 'ProVeg International', 'Global Strategy Director', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/riarehberg/', NULL, 'part-time', 'Animal welfare'),
('Chee Hoe Keong', 'ProVeg International', 'Programme Lead', '2025-03-01', 'month', '2026-01-01', 'month', 'https://www.linkedin.com/in/chee-hoe-keong-43906228b/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Chee Hoe Keong', 'ProVeg International', 'Asia Partnerships & Organizational Manager', '2026-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/chee-hoe-keong-43906228b/', NULL, 'full-time', 'Animal welfare'),
('Maxi Heese', 'ProVeg International', 'V-Label Werkstudentin Marketing & Kommunikation', '2023-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maxi-heese/', NULL, 'part-time', 'Animal welfare')
,
('Marie Korbel', 'ProVeg International', 'Leitung ProVeg School Plate Programme Lake Geneva', '2024-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/marie-korbel/', NULL, 'contractor', 'Animal welfare'),
('Karthik Pulugurtha', 'ProVeg International', 'Executive Director (PV India)', '2025-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/karthik-pulugurtha-b8902923/', NULL, 'full-time', 'Animal welfare'),
('Lea Stockmeier', 'ProVeg International', 'International Eventmanager', '2018-09-01', 'month', '2021-04-01', 'month', 'https://www.linkedin.com/in/lea-stockmeier-218b7a2b7/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Lea Stockmeier', 'ProVeg International', 'Senior International Eventmanager', '2021-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lea-stockmeier-218b7a2b7/', NULL, 'full-time', 'Animal welfare'),
('Dawn Moncrief', 'ProVeg International', 'Board Chair (USA)', '2018-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/dawn-moncrief/', NULL, 'board member', 'Animal welfare'),
('Julia-Janine Bressem', 'ProVeg International', 'Social Media-Managerin', '2023-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/julia-janine-bressem-040080152/', NULL, 'part-time', 'Animal welfare')
,
('Olivia Ladinig', 'ProVeg International', 'Grants Program & Impact Evaluation Analyst', '2026-02-01', 'month', '2026-03-01', 'month', 'https://www.linkedin.com/in/olivia-ladinig-884873125/', NULL, 'contractor', 'Animal welfare') /*Closed*/,
('Olivia Ladinig', 'ProVeg International', 'Head of Global Grantmaking', '2026-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/olivia-ladinig-884873125/', NULL, 'full-time', 'Animal welfare'),
('Nicole Wu', 'ProVeg International', 'China Executive Director', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nicole-wu-bei/', NULL, 'full-time', 'Animal welfare'),
('Colette Fox', 'ProVeg International', 'Special Adviser to President & Global CEO', '2024-02-01', 'month', '2024-07-01', 'month', 'https://www.linkedin.com/in/colettefox/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Colette Fox', 'ProVeg International', 'Public Food Lead', '2025-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/colettefox/', NULL, 'full-time', 'Animal welfare'),
('Dr. Nina Wolff', 'ProVeg International', 'Senior Policy Expert', '2025-06-01', 'month', '2026-05-01', 'month', 'https://www.linkedin.com/in/nina-wolff-berlin/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Dr. Nina Wolff', 'ProVeg International', 'Head of Policy Germany', '2026-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nina-wolff-berlin/', NULL, NULL, 'Animal welfare'),
('Altamush Saeed', 'ProVeg International', 'Youth Board Member 2024', '2024-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/altamushsaeed95/', NULL, 'board member', 'Animal welfare'),
('Altamush Saeed', 'ProVeg International', 'Kickstarting for Good Graduate', '2024-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/altamushsaeed95/', NULL, 'contractor', 'Animal welfare'),
('Altamush Saeed', 'ProVeg International', 'ProVeg Youth Board Member 2025', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/altamushsaeed95/', NULL, 'board member', 'Animal welfare'),
('Stephanie Otto', 'ProVeg International', 'Executive Coordinator', '2019-06-01', 'month', '2020-05-01', 'month', 'https://www.linkedin.com/in/ottostephanie/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Stephanie Otto', 'ProVeg International', 'Executive Coordination Manager', '2020-06-01', 'month', '2021-10-01', 'month', 'https://www.linkedin.com/in/ottostephanie/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Stephanie Otto', 'ProVeg International', 'International Operations Team Lead', '2021-11-01', 'month', '2023-03-01', 'month', 'https://www.linkedin.com/in/ottostephanie/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Stephanie Otto', 'ProVeg International', 'Head of International Operations', '2023-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ottostephanie/ https://web.archive.org/web/20240122234302/https://proveg.org/about-us/ https://web.archive.org/web/20251201084101/https://proveg.org/about-us/', NULL, 'full-time', 'Animal welfare') /*Last checked Wayback snapshot is from 2025-12-01*/
,
('Stephanie Otto', 'ProVeg International', 'Impact Reporting', '2018-04-01', 'month', '2018-09-01', 'month', 'https://www.linkedin.com/in/ottostephanie/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Sophie Ollrog', 'ProVeg International', 'Food Services Department', '2021-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sophie-ollrog-196a45138/', NULL, NULL, 'Animal welfare'),
('Andile Mnguni', 'ProVeg International', 'Executive Director, ProVeg South Africa', '2026-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/andile-mnguni-376948164/', NULL, 'full-time', 'Animal welfare'),
('Tim Polkowski', 'ProVeg International', 'Strategic Advisor', '2023-01-01', 'month', '2023-07-01', 'month', 'https://www.linkedin.com/in/tim-polkowski/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Tim Polkowski', 'ProVeg International', 'International Director (Strategy and Growth)', '2023-07-01', 'month', '2025-09-01', 'month', 'https://www.linkedin.com/in/tim-polkowski/ https://web.archive.org/web/20240122234302/https://proveg.org/about-us/ https://web.archive.org/web/20250901170439/https://proveg.org/about-us/ https://web.archive.org/web/20251001052104/https://proveg.org/about-us/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Tim Polkowski', 'ProVeg International', 'Deputy CEO', '2025-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tim-polkowski/ https://web.archive.org/web/20251001052104/https://proveg.org/about-us/ https://web.archive.org/web/20251201084101/https://proveg.org/about-us/', NULL, NULL, 'Animal welfare') /*Last checked Wayback snapshot is from 2025-12-01*/,
('Amada Perales Ferrer', 'ProVeg International', 'Public Affairs Manager', '2025-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/amada-perales/', NULL, 'full-time', 'Animal welfare'),
('Muriel Fritsch', 'ProVeg International', 'Praktikantin V-Label', '2022-08-01', 'month', '2022-09-01', 'month', 'https://www.linkedin.com/in/muriel-fritsch-ba0935277/', NULL, 'intern', 'Animal welfare') /*Closed*/,
('Muriel Fritsch', 'ProVeg International', 'Werkstudentin V-Label Qualitätsmanagement', '2022-10-01', 'month', '2023-07-01', 'month', 'https://www.linkedin.com/in/muriel-fritsch-ba0935277/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Muriel Fritsch', 'ProVeg International', 'Werkstudentin Finance', '2023-08-01', 'month', '2024-01-01', 'month', 'https://www.linkedin.com/in/muriel-fritsch-ba0935277/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Muriel Fritsch', 'ProVeg International', 'Werkstudentin V-Label Qualitätsmanagement', '2024-02-01', 'month', '2025-01-01', 'month', 'https://www.linkedin.com/in/muriel-fritsch-ba0935277/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Muriel Fritsch', 'ProVeg International', 'Business Development Manager', '2025-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/muriel-fritsch-ba0935277/', NULL, 'full-time', 'Animal welfare')
,
('Tobias Leenaert', 'ProVeg International', 'Co-Founder', '2017-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tobiasleenaert/ https://web.archive.org/web/20240122234302/https://proveg.org/about-us/ https://web.archive.org/web/20251201084101/https://proveg.org/about-us/', NULL, NULL, 'Animal welfare') /*Last checked Wayback snapshot is from 2025-12-01*/,
('Shreya Ghodawat', 'ProVeg International', 'Youth Board Member', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/shreyaghodawat/', NULL, 'board member', 'Animal welfare'),
('Adriana Banda Dias', 'ProVeg International', 'Fundraiser', '2022-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/adriana-banda-dias/', NULL, 'part-time', 'Animal welfare'),
('Pia Voltz', 'ProVeg International', 'Mentor', '2023-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/pia-voltz/', NULL, NULL, 'Animal welfare'),
('Eileen Valy', 'ProVeg International', 'Assistentin der Geschäftsleitung', '2017-10-01', 'month', '2018-07-01', 'month', 'https://www.linkedin.com/in/eileen-valy/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Eileen Valy', 'ProVeg International', 'Assistenz Head of Communication', '2018-08-01', 'month', '2020-01-01', 'month', 'https://www.linkedin.com/in/eileen-valy/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Eileen Valy', 'ProVeg International', 'International Communications Manager', '2020-01-01', 'month', '2022-01-01', 'month', 'https://www.linkedin.com/in/eileen-valy/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Eileen Valy', 'ProVeg International', 'Social Media Manager', '2022-01-01', 'month', '2022-07-01', 'month', 'https://www.linkedin.com/in/eileen-valy/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Eileen Valy', 'ProVeg International', 'International Senior Social Media Manager', '2022-07-01', 'month', '2023-08-01', 'month', 'https://www.linkedin.com/in/eileen-valy/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Eileen Valy', 'ProVeg International', 'International Senior Digital Communications Manager', '2023-09-01', 'month', '2024-07-01', 'month', 'https://www.linkedin.com/in/eileen-valy/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Eileen Valy', 'ProVeg International', 'International Senior Communications Manager', '2024-07-01', 'month', '2025-06-01', 'month', 'https://www.linkedin.com/in/eileen-valy/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Eileen Valy', 'ProVeg International', 'Head of Digital Engagement', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/eileen-valy/', NULL, 'full-time', 'Animal welfare')
,
('Gemma Chapman', 'ProVeg International', 'Content Creator and Writer', '2022-10-01', 'month', '2023-06-01', 'month', 'https://www.linkedin.com/in/gemma-chapman/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Gemma Chapman', 'ProVeg International', 'International Advocacy Communications Manager', '2023-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/gemma-chapman/', NULL, 'full-time', 'Animal welfare'),
('Kathy A. Davis', 'ProVeg International', 'Financial Operations Specialist', '2023-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kathyallendavis/', NULL, NULL, 'Animal welfare'),
('Fabio Venturini', 'ProVeg International', 'Head of Digital', '2019-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/fabioventuriniirl/', NULL, 'full-time', 'Animal welfare'),
('Sebastian Golly', 'ProVeg International', 'International IT Specialist', '2022-08-01', 'month', '2024-05-01', 'month', 'https://www.linkedin.com/in/sebastian-golly/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Sebastian Golly', 'ProVeg International', 'Senior International IT Specialist', '2024-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sebastian-golly/', NULL, NULL, 'Animal welfare'),
('Troy Estrellado', 'ProVeg International', 'Research Analyst', '2025-04-01', 'month', '2026-03-01', 'month', 'https://www.linkedin.com/in/troy-estrellado/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Troy Estrellado', 'ProVeg International', 'Project Assistant', '2026-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/troy-estrellado/', NULL, 'full-time', 'Animal welfare'),
('Emmanuel Márquez Morales', 'ProVeg International', 'Grants Program Coordinator', '2023-10-01', 'month', '2024-04-01', 'month', 'https://www.linkedin.com/in/emmanuel-marquez-m/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Emmanuel Márquez Morales', 'ProVeg International', 'Grants Program Manager', '2024-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/emmanuel-marquez-m/', NULL, 'full-time', 'Animal welfare')
,
('Laura Thomas-Walters', 'ProVeg International', 'Head of Impact', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/laura-thomas-walters-529a5a10b/', NULL, 'full-time', 'Animal welfare'),
('Rithika Ramesh', 'ProVeg International', 'Sr. Consultant (ProVeg India)', '2026-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rithikaramesh-/', NULL, NULL, 'Animal welfare'),
('Julian Cottee', 'ProVeg International', 'Senior Corporate Engagement Manager', '2025-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/juliancottee/', NULL, NULL, 'Animal welfare'),
('Laura Goetze', 'ProVeg International', 'International Event Manager', '2020-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lauragoetze/', NULL, NULL, 'Animal welfare'),
('Martin Hesse', 'ProVeg International', 'V-Label Senior Quality Manager Germany', '2019-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/martin-hesse-plantbased-solutions/', NULL, 'full-time', 'Animal welfare'),
('Josefine Märtin', 'ProVeg International', 'Qualitätsmanagement und Vertrieb V-Label', '2016-04-01', 'month', '2022-06-01', 'month', 'https://www.linkedin.com/in/josefine-m%C3%A4rtin-66b880a5/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Josefine Märtin', 'ProVeg International', 'Teamleiterin Lebensmittellizenzierung', '2022-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/josefine-m%C3%A4rtin-66b880a5/', NULL, 'part-time', 'Animal welfare')
,
('Chantal Du Chenne', 'ProVeg International', 'Corporate and Institutional Partnership', '2024-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/chantal-du-chenne-0ba48152/', NULL, NULL, 'Animal welfare'),
('Mark Simpson', 'ProVeg International', 'Lead Developer', '2019-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/markyz89/', NULL, 'full-time', 'Animal welfare'),
('Valentina González', 'ProVeg International', 'Impact MEL - BFD', '2025-10-01', 'month', '2026-07-01', 'month', 'https://www.linkedin.com/in/valentinagonzalezf/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Valentina González', 'ProVeg International', 'Impact Manager Germany', '2026-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/valentinagonzalezf/', NULL, 'full-time', 'Animal welfare'),
('Paris Badat', 'ProVeg International', 'Global Lead Development Operations', '2025-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/paris-badat/', NULL, 'full-time', 'Animal welfare'),
('Shirley L.', 'ProVeg International', 'Executive Director - Greater China', '2019-04-01', 'month', '2020-08-01', 'month', 'https://www.linkedin.com/in/shirley-l-273730/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Shirley L.', 'ProVeg International', 'Managing Director - Asia and Chief China Representative', '2020-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/shirley-l-273730/', NULL, 'full-time', 'Animal welfare'),
('Laura Bermúdez', 'ProVeg International', 'Lead Graphic Designer', '2018-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/aelini/', NULL, 'full-time', 'Animal welfare'),
('Monrada Waraho', 'ProVeg International', 'Student Brand Ambassador', '2022-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/mwyok/', NULL, 'part-time', 'Animal welfare')
,
('Vicki Sagar', 'ProVeg International', 'Senior Marketing and Communications Manager, ProVeg Incubator', '2022-12-01', 'month', '2025-04-01', 'month', 'https://www.linkedin.com/in/vickisagar/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Anna-Lena Klapp', 'ProVeg International', 'Nutrition and Health Specialist', '2018-04-01', 'month', '2021-09-01', 'month', 'https://www.linkedin.com/in/anna-lena-klapp/', NULL, 'part-time', 'Animal welfare') /*Closed*/,
('Anna-Lena Klapp', 'ProVeg International', 'International Nutrition & Health Lead', '2021-09-01', 'month', '2024-11-01', 'month', 'https://www.linkedin.com/in/anna-lena-klapp/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Anna-Lena Klapp', 'ProVeg International', 'Head of Research', '2024-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/anna-lena-klapp/', NULL, 'full-time', 'Animal welfare'),
('Joy Aquino', 'ProVeg International', 'International Fundraising Coordinator', '2020-11-01', 'month', '2022-10-01', 'month', 'https://www.linkedin.com/in/joyanneaquino/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Joy Aquino', 'ProVeg International', 'International Fundraising and Outreach Manager', '2022-10-01', 'month', '2024-01-01', 'month', 'https://www.linkedin.com/in/joyanneaquino/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Joy Aquino', 'ProVeg International', 'International Digital Marketing and Communications Manager', '2024-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/joyanneaquino/', NULL, NULL, 'Animal welfare'),
('Jasmijn De Boo', 'ProVeg International', 'International Director (Executive Team)', '2018-04-01', 'month', '2020-05-01', 'month', 'https://www.linkedin.com/in/jasmijndeboo/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Jasmijn De Boo', 'ProVeg International', 'Vice President (Executive Team)', '2020-05-01', 'month', '2023-05-01', 'month', 'https://www.linkedin.com/in/jasmijndeboo/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Jasmijn De Boo', 'ProVeg International', 'Global CEO', '2023-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jasmijndeboo/ https://web.archive.org/web/20240122234302/https://proveg.org/about-us/ https://web.archive.org/web/20251201084101/https://proveg.org/about-us/', NULL, 'full-time', 'Animal welfare') /*Last checked Wayback snapshot is from 2025-12-01*/,
('Leena Joshi', 'ProVeg International', 'Board Member', '2026-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/leena-joshi-/', NULL, 'board member', 'Animal welfare'),
('Verónica Larco Jiménez', 'ProVeg International', 'Communications Manager ProVeg España', '2019-08-01', 'month', '2023-01-01', 'month', 'https://www.linkedin.com/in/ver%C3%B3nica-larco-jim%C3%A9nez-68182058/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Verónica Larco Jiménez', 'ProVeg International', 'Senior Comms Manager', '2023-02-01', 'month', '2024-10-01', 'month', 'https://www.linkedin.com/in/ver%C3%B3nica-larco-jim%C3%A9nez-68182058/', NULL, 'full-time', 'Animal welfare') /*Closed*/,
('Verónica Larco Jiménez', 'ProVeg International', 'Senior Comms Manager Spain and Latam', '2024-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ver%C3%B3nica-larco-jim%C3%A9nez-68182058/', NULL, 'full-time', 'Animal welfare'),
('Prerna Singh', 'ProVeg International', 'Operations Assistant', '2025-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/prerna-singh-a64364351/', NULL, 'full-time', 'Animal welfare')
,
('Veerle Vrindts', 'ProVeg International', 'Strategic Partnerships Connector & Storyteller in Residence', '2025-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/veerle-vrindts-6b93a325/', NULL, 'contractor', 'Animal welfare'),
('Adam Fedoryszyn', 'ProVeg International', 'Fundraiser', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/adam-fedoryszyn-39813836b/', NULL, 'contractor', 'Animal welfare'),
('Jens Tuider', 'ProVeg International', 'Chief Strategy Officer', '2024-01-22', 'multi-year', '2024-11-10', 'month', 'https://web.archive.org/web/20240122234302/https://proveg.org/about-us/ https://web.archive.org/web/20241110210746/https://proveg.org/about-us/ https://web.archive.org/web/20241206200551/https://proveg.org/about-us/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Peter Krocka', 'ProVeg International', 'International Head of People & Culture (cover)', '2024-01-22', 'multi-year', '2024-11-10', 'month', 'https://web.archive.org/web/20240122234302/https://proveg.org/about-us/ https://web.archive.org/web/20241110210746/https://proveg.org/about-us/ https://web.archive.org/web/20241206200551/https://proveg.org/about-us/', NULL, NULL, 'Animal welfare') /*Closed*/,
('Urgesa Jemal', 'ProVeg International', 'International Youth Board', '2026-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/urgesa-jemal-329576379/', NULL, 'board member', 'Animal welfare');