insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
    ('Philipp Ryf', 'Sentience Politics', 'Project Manager', '2014-09-01', 'month', '2016-02-01', 'month', 'https://www.linkedin.com/in/philipp-ryf-24095563/?originalSubdomain=ch', NULL, NULL, 'Animal welfare')
    ,('Silvano Lieger', 'Sentience Politics', 'Co-Managing Director', '2019-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lieger/', NULL, NULL, 'Animal welfare')
    ,('Johanna Kuhn', 'Sentience Politics', 'Project Manager', '2020-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/johanna-kuhn/', NULL, NULL, 'Animal welfare')
    ,('Ivo Mändli', 'Sentience Politics', 'Board Member', '2019-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ivo-m%C3%A4ndli-296375127/', NULL, NULL, 'Animal welfare')
    ,('Valentin Salzgeber', 'Sentience Politics', 'Board Member', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, NULL, 'Animal welfare')
    ,('Reto Walther', 'Sentience Politics', 'Board Member', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, NULL, 'Animal welfare')
    ,('Angelina Dobler', 'Sentience Politics', 'Board Member', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, NULL, 'Animal welfare')
    ,('Urban Müller', 'Sentience Politics', 'Board Member', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, NULL, 'Animal welfare')
    ,('Anna Travinskaya', 'Sentience Politics', 'Volunteer', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, 'volunteer', 'Animal welfare')
    ,('Daniel Rüthemann', 'Sentience Politics', 'Graphic and design', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, NULL, 'Animal welfare')
    ,('Mirjam Arn', 'Sentience Politics', 'Volunteer', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, 'volunteer', 'Animal welfare')
    ,('Rahel Alt', 'Sentience Politics', 'Volunteer', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, 'volunteer', 'Animal welfare')
    ,('Melina Tan', 'Sentience Politics', 'Volunteer', NULL, NULL, NULL, NULL, 'https://sentience-politics.org/de/about/team/', NULL, 'volunteer', 'Animal welfare')
    ,('Tamina S. Graber', 'Sentience Politics', 'Campaign Leader', '2020-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/taminagraber/', 'Based in Zürich', 'part-time', 'Animal welfare')
    ,('Adriano Mannino', 'Sentience Politics', 'Co-Founder', '2014-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/adriano-mannino-5004a0a5/', NULL, NULL, 'Animal welfare')
    ,('Meret Schneider', 'Sentience Politics', 'Manager at Sentience Politics Switzerland', '2015-10-18', 'year', NULL, NULL, 'https://web.archive.org/web/20151018063925/http://sentience-politics.org/about-2/', NULL, NULL, 'Animal welfare')
 