 insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
 ('Cillian Crosson', 'Tarbell Center for AI Journalism', 'Executive Director and President', '2022-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cillian-crosson/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, NULL, 'AI safety')  /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Shakeel Hashim', 'Tarbell Center for AI Journalism', 'Editor, Transformer', '2024-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/shakeelhashim/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'full-time', 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Sawyer Bernath', 'Tarbell Center for AI Journalism', 'Operations Director and Treasurer', '2024-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sawyerbernath/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'full-time', 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Anna Gordon', 'Tarbell Center for AI Journalism', 'AI Journalism Lead', '2025-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/annagordon0111/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'full-time', 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Michel Justen', 'Tarbell Center for AI Journalism', 'AI Grants Lead', '2025-04-02', 'month', NULL, NULL, 'https://www.linkedin.com/in/michel-justen/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Yi-Ling Liu', 'Tarbell Center for AI Journalism', 'Journalist in Residence', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/yi-ling-l-89799783/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'full-time', 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Leah Harrison', 'Tarbell Center for AI Journalism', 'Partnerships Director', '2025-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/leah-harrison-5469a813/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Jasper Jackson', 'Tarbell Center for AI Journalism', 'Managing Editor, Transformer', '2025-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */

,('Celia Ford', 'Tarbell Center for AI Journalism', 'Reporter, Transformer', '2025-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, NULL, 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Cillian Crosson', 'Tarbell Center for AI Journalism', 'Board Member', '2025-01-01', NULL, NULL, NULL, 'https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'board member', 'AI safety')  /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Mikko Järvenpää', 'Tarbell Center for AI Journalism', 'Board Member', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/mikkojarvenpaa/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'board member', 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Elizabeth Seger', 'Tarbell Center for AI Journalism', 'Board Member', '2025-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/elizabeth-seger-5209797b/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'board member', 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */
,('Cody Fenwick', 'Tarbell Center for AI Journalism', 'Board Member', '2025-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cody-fenwick-8073089b/ https://web.archive.org/web/20250826000305/https://www.tarbellfellowship.org/team', NULL, NULL, NULL, 'board member', 'AI safety') /* Reviewed on 2025-08-26 / / Last available Wayback snapshot date is 2025-08-26 */

/* ONLY LINKEDIN */

,('Tharin Pillay', 'Tarbell Center for AI Journalism', 'Fellow', '2024-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tharin-pillay/', NULL, NULL, NULL, NULL, 'AI safety') 
,('Elissa Welle', 'Tarbell Center for AI Journalism', 'AI Reporter', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/elissawelle/', NULL, NULL, NULL, 'full-time', 'AI safety') 
,('Tom Ough', 'Tarbell Center for AI Journalism', 'Mentor', '2023-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/tomough/', NULL, NULL, NULL, 'part-time', 'AI safety') 
,('Ella Markianos', 'Tarbell Center for AI Journalism', 'Tarbell Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ella-markianos-7708a9237/', NULL, NULL, NULL, NULL, 'AI safety') 
,('Michelle Kim', 'Tarbell Center for AI Journalism', 'Tarbell Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/michelletomkim/', NULL, NULL, NULL, 'full-time', 'AI safety') 
,('Robert Hart', 'Tarbell Center for AI Journalism', 'Senior Tarbell Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/theroberthart/', NULL, NULL, NULL, 'full-time', 'AI safety') 
,('Kai Williams', 'Tarbell Center for AI Journalism', 'Tarbell Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kai-t-williams/', NULL, NULL, NULL, 'full-time', 'AI safety') 
,('Nilesh Christopher', 'Tarbell Center for AI Journalism', 'Senior Tarbell Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nilesh-christopher-20831784/', NULL, NULL, NULL, 'full-time', 'AI safety') 
,('Jakub Kraus', 'Tarbell Center for AI Journalism', 'Tarbell Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jakraus/', NULL, NULL, NULL, 'full-time', 'AI safety')
,('Jakub Kraus', 'Tarbell Center for AI Journalism', 'Tarbell Fellow', '2025-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jakraus/', NULL, NULL, NULL, 'full-time', 'AI safety') 

/* CLOSED */

,('Michel Justen', 'Tarbell Center for AI Journalism', 'AI Journalism Associate', '2024-11-01', 'month', '2025-04-01', 'month', 'https://www.linkedin.com/in/michel-justen/', NULL, NULL, NULL, NULL, 'AI safety') 
