(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area)
    ,('Mark Middleton', 'The Humane League', 'Chairman', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Lydia Chaudhry', 'The Humane League', 'Secretary', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Suzanne Niemoth', 'The Humane League', 'Treasurer', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Neysa Colizzi', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Jacob Eliosoff', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Alicia Rodriguez', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Shannon Campion', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Eryn Johnson', 'The Humane League', 'New Media Intern', '2017-03-01', 'month', NULL NULL, 'https://www.linkedin.com/in/erynjohnsonsocial/', NULL, 'volunteer', 'Animal welfare')
    ,('Samara Mendez', 'The Humane League Labs', 'Economist', '2018-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/samara-mendez-97741750/, NULL, NULL, 'Animal welfare')
    ,('Cristyn Hypnar', 'The Humane League', 'Creative Lead', '2017-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cristynhypnar/, NULL, NULL, 'Animal welfare')
    ,('Cristyn Hypnar', 'The Humane League', 'Graphic Designer', '2016-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cristynhypnar/, NULL, NULL, 'Animal welfare') 
    ,('Clare Farrow', 'The Humane League', 'Campaigns Intern', '2016-02-01', 'month', '2016-05-01', 'month', https://www.linkedin.com/in/claremfarrow/, NULL, NULL, 'Animal welfare')
    ,('Clare Farrow', 'The Humane League', 'NYC Grassroots Director', '2016-06-01', 'month', '2018-01-01', 'month', https://www.linkedin.com/in/claremfarrow/, NULL, NULL, 'Animal welfare')
    ,('Clare Farrow', 'The Humane League', 'Open Wing Alliance Membership Manager', '2018-01-01', 'month', NULL, NULL, https://www.linkedin.com/in/claremfarrow/, NULL, NULL, 'Animal welfare')


