insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
('Gadi Isaev', 'The Israeli Association for Ethics in Artificial Intelligence', 'Founding Partner', '2023-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/gadiisaev/ https://web.archive.org/web/20230921113408/https://iaeai.org/about https://web.archive.org/web/20260918185833/https://iaeai.org/about', NULL, 'position', 'strategy', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-18*/
('Roman Gold', 'The Israeli Association for Ethics in Artificial Intelligence', 'Founding Partner', '2023-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/romangold/ https://web.archive.org/web/20230921113408/https://iaeai.org/about https://web.archive.org/web/20260918185833/https://iaeai.org/about', NULL, 'position', 'strategy', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-18*/
('Liel Gutman', 'The Israeli Association for Ethics in Artificial Intelligence', 'Head of Research', '2023-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maria-liel-gutman/ https://web.archive.org/web/20230921113408/https://iaeai.org/about https://web.archive.org/web/20260918185833/https://iaeai.org/about', NULL, 'position', 'technical research', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-18*/
('Maya Sherman', 'The Israeli Association for Ethics in Artificial Intelligence', 'Scientific Council Member', '2023-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maya-sherman-02b474115/', NULL, 'position', 'policy', 'advisor', 'AI safety'),
('Eugenia Kovatcheva', 'The Israeli Association for Ethics in Artificial Intelligence', 'Invited member of IAEAI Scientific Council', '2023-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/eugenia-kovatcheva/', NULL, 'position', 'technical research', 'advisor', 'AI safety'),
('Ram Rachum', 'The Israeli Association for Ethics in Artificial Intelligence', 'Scientific Council Member', '2023-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ram-rachum-349b7a17/', NULL, 'position', 'technical research', 'advisor', 'AI safety'),
('Chhavi Chauhan', 'The Israeli Association for Ethics in Artificial Intelligence', 'The Israeli Association for Ethics in Artificial Intelligence Scientific Council', '2023-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/chhavichauhan/', NULL, 'position', 'technical research', 'advisor', 'AI safety'),
('Pablo Ballarin Usieto', 'The Israeli Association for Ethics in Artificial Intelligence', 'Scientific Council Member', '2023-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/pabloballarin/', NULL, 'position', 'technical research', 'advisor', 'AI safety'),
('Eran Kahana', 'The Israeli Association for Ethics in Artificial Intelligence', 'Scientific Council Member', '2023-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/erankahana/', NULL, 'position', 'policy', 'advisor', 'AI safety'),
('Thilo Stadelmann', 'The Israeli Association for Ethics in Artificial Intelligence', 'Member of the Scientific Council', '2023-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/thilo-stadelmann/', NULL, 'position', 'technical research', 'advisor', 'AI safety'),
('Tim Kogan', 'The Israeli Association for Ethics in Artificial Intelligence', 'Head of International Relations', '2023-09-21', 'month', NULL, NULL, 'https://web.archive.org/web/20230921113408/https://iaeai.org/about https://web.archive.org/web/20260918185833/https://iaeai.org/about', NULL, 'position', 'strategy', NULL, 'AI safety'), /*Last checked Wayback snapshot is from 2026-09-18*/
('Marcos Tatijewski (Kiko)', 'The Israeli Association for Ethics in Artificial Intelligence', 'Miembro', '2024-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/marcostati/', NULL, 'position', 'general', 'part-time', 'AI safety');
