(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area)
    ,('Mark Middleton', 'The Humane League', 'Chairman', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Lydia Chaudhry', 'The Humane League', 'Secretary', NULL, NULL, NULL, NULL, 'https://thehumaneleague.or g/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Suzanne Niemoth', 'The Humane League', 'Treasurer', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Neysa Colizzi', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Jacob Eliosoff', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Alicia Rodriguez', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Shannon Campion', 'The Humane League', 'Director', NULL, NULL, NULL, NULL, 'https://thehumaneleague.org/our-leadership', NULL, NULL, 'Animal welfare')
    ,('Eryn Johnson', 'The Humane League', 'New Media Intern', '2017-03-01', 'month', NULL NULL, 'https://www.linkedin.com/in/erynjohnsonsocial/', NULL, 'volunteer', 'Animal welfare')
    ,('Samara Mendez', 'The Humane League Labs', 'Economist', '2018-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/samara-mendez-97741750/, NULL, NULL, 'Animal welfare')
    ,('Cristyn Hypnar', 'The Humane League', 'Creative Lead', '2017-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cristynhypnar/ https://web.archive.org/web/20170328195214/http://www.thehumaneleague.com/our-story/', NULL, NULL, 'Animal welfare')
    ,('Cristyn Hypnar', 'The Humane League', 'Graphic Designer', '2016-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cristynhypnar/, NULL, NULL, 'Animal welfare') 
    ,('Clare Farrow', 'The Humane League', 'Campaigns Intern', '2016-02-01', 'month', '2016-05-01', 'month', https://www.linkedin.com/in/claremfarrow/, NULL, NULL, 'Animal welfare')
    ,('Clare Farrow', 'The Humane League', 'NYC Grassroots Director', '2016-06-01', 'month', '2018-01-01', 'month', https://www.linkedin.com/in/claremfarrow/, NULL, NULL, 'Animal welfare')
    ,('Clare Farrow', 'The Humane League', 'Open Wing Alliance Membership Manager', '2018-01-01', 'month', NULL, NULL, https://www.linkedin.com/in/claremfarrow/, NULL, NULL, 'Animal welfare')
    ,('Kristen Diederich', 'The Humane League', 'Donor Relations Manager', '2017-04-01', 'month', '2018-04-01', 'month', 'https://www.linkedin.com/in/kristen-diederich/', NULL, NULL, 'Animal welfare')
    ,('Kristen Diederich', 'The Humane League', 'Development Projects Manager', '2018-04-01', 'month', 'NULL, NULL, 'https://www.linkedin.com/in/kristen-diederich/', NULL, NULL, 'Animal welfare')
    ,('Kyle Fujisawa', 'The Humane League', 'Web Developer Intern', '2017-08-01', 'month', '2017-12-01', 'month', 'https://www.linkedin.com/in/kyle-fujisawa-563648139/', NULL, 'intern', 'Animal welfare')
    ,('Kyle Fujisawa', 'The Humane League', 'Web Developer', '2018-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kyle-fujisawa-563648139/', NULL, NULL, 'Animal welfare')
    ,('Caroline Mills', 'The Humane League', 'Donor Relations Manager', '2016-08-01', 'month', '2018-09-01', 'month', 'https://www.linkedin.com/in/caroline-mills-7abab91a/', NULL, NULL, 'Animal welfare')
    ,('Caroline Mills', 'The Humane League', 'Director Of Donor Relations', '2018-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/caroline-mills-7abab91a/', NULL, NULL, 'Animal welfare')
    ,('Stephanie Frankle', 'The Humane League', 'San Francisco Grassroots Director', '2014-01-01', 'month', '2016-06-01', 'month', 'https://www.linkedin.com/in/stephanie-frankle-0597455a/', NULL, NULL, 'Animal welfare')
    ,('Stephanie Frankle', 'The Humane League', 'Campus Outreach Director', '2016-07-01', 'month', '2017-05-01', 'month', 'https://www.linkedin.com/in/stephanie-frankle-0597455a/', NULL, NULL, 'Animal welfare')
    ,('Stephanie Frankle', 'The Humane League', 'Director of Student Engagement', '2017-05-01', 'month', '2018-06-01', 'month', 'https://www.linkedin.com/in/stephanie-frankle-0597455a/', NULL, NULL, 'Animal welfare')
    ,('Stephanie Frankle', 'The Humane League', 'Culture and Engagement Specialist', '2018-06-01', 'month', '2020-01-01', 'month', 'https://www.linkedin.com/in/stephanie-frankle-0597455a/', NULL, NULL, 'Animal welfare')
    ,('Jon Camp', 'The Humane League', 'Vice President, Grassroots', '2016-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jon-camp-68a746b6/?trk=public_profile_browsemap_profile-result-card_result-card_full-click https://web.archive.org/web/20160202053112/http://www.thehumaneleague.org/our-story/', NULL, NULL, 'Animal welfare')
    ,('Adrian Guinn, 'The Humane League', 'Boston Grassroots Coordinator', '2017-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/adrian-guinn-7827b1171/', NULL, NULL, 'Animal welfare')
    ,('Anna Finch', 'The Humane League', 'Fundraising Events Coordinator', '2018-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/anna-lea-finch/', NULL, NULL, 'Animal welfare')
    ,('Erin Dorman', 'The Humane League', 'Copywritter', '2020-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/erin-doman-15399195/', NULL, NULL, 'Animal welfare')
    ,('Maitlyn Healy', 'The Humane League', 'Field Organizer- DC', '2019-8-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maitlynhealy/', NULL, 'full time', 'Animal welfare')
    ,('Ryan Bulzan', 'The Humane League', 'New Media Intern', '2017-03-01', 'month', '2017-11-01', 'month', 'https://www.linkedin.com/in/ryan-bulzan/', NULL, 'intern', 'Animal welfare')
    ,('Ryan Bulzan', 'The Humane League', 'Grassroots Coordinator', '2017-10-01', 'month', '2019-03-01', 'month', 'https://www.linkedin.com/in/ryan-bulzan/', NULL, NULL, 'Animal welfare')
    ,('Ryan Bulzan', 'The Humane League', 'Field Organizer, Regional', '2019-03-01', 'month', '2019-06-01', 'month', 'https://www.linkedin.com/in/ryan-bulzan/', NULL, NULL, 'Animal welfare')
    ,('Ryan Bulzan', 'The Humane League', 'Senior Field Organizer, Regional', '2019-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ryan-bulzan/', NULL, NULL, 'Animal welfare')
    ,('Jennifer Barckley', 'The Humane League', 'Vice President, Communications', '2018-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jenniferbarckley/', NULL, NULL, 'Animal welfare')
    ,('Michelle Kucerak', 'The Humane League', 'Vice President. Development', '2014-12-01', 'month', '2018-12-01', 'month', 'https://www.linkedin.com/in/michelle-kucerak-b057b76/', NULL, NULL, 'Animal welfare')
    ,('Michelle Kucerak', 'The Humane League', 'Senior Vice-President, Programs and Development', '2019-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/michelle-kucerak-b057b76/', NULL, NULL, 'Animal welfare')
    ,('Laura Elseroad', 'The Humane League', 'National Volunteer Coordinator, US', '2017-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lauraelseroad/', NULL, NULL, 'Animal welfare')
    ,('Laura Elseroad', 'The Humane League', 'Senior Field Organizer, Regional, '2019-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lauraelseroad/', NULL, NULL, 'Animal welfare') 
    ,('Alex Wolfe', 'The Humane League', 'NYC Field Organizer', '2019-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/alex-wolfe-55ba2435/', NULL, NULL, 'Animal welfare')
    ,('Kassy Ortega', 'The Humane League', 'Grassroots Director', '2016-01-01', 'month', '2017-07-01', 'month','https://www.linkedin.com/in/kassyortega/ https://web.archive.org/web/20160202053112/http://www.thehumaneleague.org/our-story/', NULL, NULL, 'Animal welfare')
    ,('Kassy Ortega', 'The Humane League', 'Corpor ate Relations Manager', '2017-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kassyortega/', NULL, NULL, 'Animal welfare')
    ,('Britta Johnson', 'The Humane League', 'Regional Field Organizer', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/britta-johnson-2b54b461/', NULL, NULL, 'Animal welfare')
    ,('Diana Cimino', 'The Humane League', 'Donor Relations Manager', '2017-08-01', 'month', '2018-07-01', 'month', 'https://www.linkedin.com/in/dianacimino/', NULL, NULL, 'Animal welfare')
    ,('Diana Cimino', 'The Humane League', 'Senior Donor Relations Manager', '2018-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/dianacimino/', NULL, NULL, 'Animal welfare')
    ,('Taylor Ford', 'The Humane League', 'Corporate Campaigns Manager', '2014-12-01', 'month', '2017-04-01', 'month', 'https://www.linkedin.com/in/taylor-ford-83648693/', NULL, NULL, 'Animal welfare')
    ,('Taylor Ford', 'Director of Campaigns', 'Director of Corporate Engagement', '2017-01-01', 'month', '2020-01-01', 'month', 'https://www.linkedin.com/in/taylor-ford-83648693/', NULL, NULL, 'Animal welfare')
    ,('Taylor Ford', 'The Humane League', 'Director of Corporate Engagement', '2020-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/taylor-ford-83648693/', NULL, NULL, 'Animal welfare')
    ,('Beth Anne Hendrickson', 'The Humane League', 'Corporate Relations Specialist', '2017-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/bethannehendrickson/', NULL, NULL, 'Animal welfare')
    ,('Jyllian Shepard', 'The Humane League', 'Human Resources Coordinator', '2017-09-01', 'month', '2018-04-01', 'month', 'https://www.linkedin.com/in/jyllian-shepard/', NULL, 'full time', 'Animal welfare')
    ,('Jyllian Shepard', 'The Humane League', 'Human Resources Manager', '2018-04-01', 'month', '2019-01-01', 'month', 'https://www.linkedin.com/in/jyllian-shepard/', NULL, 'full time', 'Animal welfare')
    ,('Jyllian Shepard', 'The Humane League', 'Talent Acquisition Manager', '2019-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jyllian-shepard/', NULL, 'full time', 'Animal welfare')
    ,('Chris Liptrot', 'The Humane League', 'Corporate Outreach Manager', NULL, NULL, NULL, NULL, 'https://www.linkedin.com/in/chris-liptrot-730289120/', NULL, NULL, 'Animal welfare')
    ,('Chris Liptrot', 'The Humane League', 'Director Of Corporate Relations', '2017-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/chris-liptrot-730289120/', NULL, NULL, 'Animal welfare')
    ,('Kelly Myers', 'The Humane League', 'Corporate Campaigns Coordinator', '2016-04-02', 'month', '2020-02-01', 'month', 'https://www.linkedin.com/in/kelly-myers-4b08a780/ https://web.archive.org/web/20160402161712/http://thehumaneleague.org/our-story/', NULL, NULL, 'Animal welfare')
    ,('Kelly Myers', 'The Humane League', 'Senior Campaigns Specialist', '2019-01-01', 'year', '2020-02-01', 'month', 'https://www.linkedin.com/in/kelly-myers-4b08a780/', NULL, NULL, 'Animal welfare')
    ,('Kelly Myers', 'The Humane League', 'Senior Campaigns Specialist', '2020-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kelly-myers-4b08a780/', NULL, NULL, 'Animal welfare')
    ,('Katerra Martin', 'The Humane League', 'Corporate Relations Specialist', '2018-12-01', 'month', '2020-03-01', 'month', 'https://www.linkedin.com/in/katerra-martin/', NULL, NULL, 'Animal welfare')
    ,('Rachel Huff-Wagenborg', 'The Humane League', 'Vice President of Operations', '2014-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rachelh-w/', NULL, NULL, 'Animal welfare')
    ,('Andrea Gunn', 'The Humane League', 'Charlotte Director', '2013-09-01', 'month', '2015-05-01', 'month', 'https://www.linkedin.com/in/andreagunnthl/', NULL, NULL, 'Animal welfare')
    ,('Andrea Gunn', 'The Humane League', 'National Grassroots Director', '2014-06-01', 'month', '2015-12-01', 'month', 'https://www.linkedin.com/in/andreagunnthl/', NULL, NULL, 'Animal welfare')
    ,('Andrea Gunn', 'The Humane League', 'Executive Vice President', '2016-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/andreagunnthl/ https://web.archive.org/web/20160202053112/http://www.thehumaneleague.org/our-story/', NULL, NULL, 'Animal welfare')
    ,('David Coman-Hidy', 'The Humane League', 'Boston Grassroots Director', '2010-01-01', 'year', '2013-01-01', 'year', 'https://www.linkedin.com/in/david-coman-hidy-4816b727/', NULL, NULL, 'Animal welfare')
    ,('David Coman-Hidy', 'The Humane League', 'President', '2013-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/david-coman-hidy-4816b727/', NULL, NULL, 'Animal welfare')
    ,('Dena Blumenthal', 'The Humane League', 'Campaign coordinator', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/denablum/', NULL, NULL, 'Animal welfare')
    ,('Amanda Waxman', 'The Humane League', 'Social Media Coordinator', '2019-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/amanda-waxman-032721148/', NULL, NULL, 'Animal welfare')
    ,('Kelsey Joseph', 'The Humane League', 'Grassroots Coordinator', '2017-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kelsey-joseph/', NULL, NULL, 'Animal welfare')
    ,('Kelsey Joseph', 'The Humane League', 'Senior Regional Field Organizer', '2019-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/kelsey-joseph/', NULL, NULL, 'Animal welfare')
    ,('Danielle Fahs', 'The Humane League', 'Digital Mobilization Specialist', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/danielle-fahs/', NULL, NULL, 'Animal welfare')
    ,('Derek Shiller', 'The Humane League', 'Web Developer', '2018-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/derek-shiller-3a254b121/', NULL, NULL, 'Animal welfare')
    ,('Angel Lugo', 'The Humane League', 'Video Editor', '2018-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/angel-lugo-88183722/', NULL, NULL, 'Animal welfare')
    ,('Catherine Liguori', 'The Humane League', 'Global Digital Ad Coordinator, '2015-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/catherine-liguori-874559129/', NULL, NULL, 'Animal welfare')
    ,('Chris Hendrickson', 'The Humane League', 'Boston Grassroots Director', '2015-09-01', 'month', '2017-09-01', 'month', 'https://www.linkedin.com/in/cahendrickson/', NULL, NULL, 'Animal welfare')
    ,('Chris Hendrickson', 'The Humane League', 'California Campaign Manager', '2017-09-01', 'month', '2019-01-01', 'month', 'https://www.linkedin.com/in/cahendrickson/', NULL, NULL, 'Animal welfare')
    ,('Chris Hendrickson', 'The Humane League', 'Regional Organizing Manager', '2019-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cahendrickson/', NULL, NULL, 'Animal welfare')
    ,('John Oberg', 'The Humane League', 'Director of New Media', '2016-01-01', 'month', '2018-12-01', 'month', 'https://www.linkedin.com/in/johnsoberg/ https://web.archive.org/web/20160202053112/http://www.thehumaneleague.org/our-story/', NULL, NULL, 'Animal welfare')
    ,('José Elias', 'The Humane League', 'Campus Campaigns Coordinator', '2016-02-01', 'month', '2016-12-01', 'month', 'https://www.linkedin.com/in/jos%C3%A9-elias-478093139/', NULL, NULL, 'Animal welfare')
    ,('José Elias', 'The Humane League', 'Campus Outreach Director', '2016-12-01', 'month', '2019-06-01', 'month', 'https://www.linkedin.com/in/jos%C3%A9-elias-478093139/', NULL, NULL, 'Animal welfare')
    ,('José Elias', 'The Humane League', 'Assistant Video Producer', '2019-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jos%C3%A9-elias-478093139/', NULL, NULL, 'Animal welfare')
    ,('Romina Giel, 'The Humane League', 'Intern', '2016-11-01', 'month', '2017-10-01', 'month', 'https://www.linkedin.com/in/romina-giel-aa7347a4/', NULL, 'intern', 'Animal welfare')
    ,('Romina Giel, 'The Humane League', 'Philadelphia Grassroots Coordinator', '2017-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/romina-giel-aa7347a4/', NULL, NULL, 'Animal welfare')
    ,('Romina Giel, 'The Humane League', 'Open Wing Alliance Events Coordinator', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/romina-giel-aa7347a4/', NULL, NULL, 'Animal welfare')
    ,('Alanna Ramsier', 'The Humane League', 'Communications Project Lead', '2017-09-01', 'month', '2020-02-01', 'month', 'https://www.linkedin.com/in/alanna-ramsier-16041672/', NULL, 'full time', 'Animal welfare')
    ,('Alanna Ramsier', 'The Humane League', 'Content Operations Lead', '2020-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/alanna-ramsier-16041672/', NULL, 'full time', 'Animal welfare')
    ,('Julia Tomkins', 'The Humane League', 'Public Relations Director', '2019-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/julia-tomkins-395ab236/', NULL, NULL, 'Animal welfare')
    ,('Katie Zarajczyk', 'The Humane League', 'Campus Organizer', '2017-01-01', 'month', '2018-06-01', 'month', 'https://www.linkedin.com/in/katie-zarajczyk-ma-70a5a3176/', NULL, NULL, 'Animal welfare')
    ,('Katie Zarajczyk', 'The Humane League', 'Campus Outreach Coordinator', '2018-07-01', 'month', '2019-12-01', 'month', 'https://www.linkedin.com/in/katie-zarajczyk-ma-70a5a3176/', NULL, NULL, 'Animal welfare')
    ,('Katie Zarajczyk', 'The Humane League', 'Fellowship Lead', '2019-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/katie-zarajczyk-ma-70a5a3176/', NULL, NULL, 'Animal welfare')
    ,('Daniela Escamilla', 'The Humane League', 'Social Media Manager', '2019-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/danielaescamilla/', NULL, NULL, 'Animal welfare')
    ,('Kalista Barter', 'The Humane League', 'Senior Director Of Development', '2019-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/kalista-barter/', NULL, NULL, 'Animal welfare')
    ,('Brooke Shephard, 'The Humane League', 'Social Media Intern', '2018-11-01', 'month', '2019-02-01', 'month', 'https://www.linkedin.com/in/brooke-shephard-865195154/', NULL, NULL, 'Animal welfare')
    ,('Brooke Shephard, 'The Humane League', 'Community Volunteer', '2018-07-01', 'month', '2019-07-01', 'month', 'https://www.linkedin.com/in/brooke-shephard-865195154/', NULL, 'volunteer', 'Animal welfare')
    ,('Brooke Shephard, 'The Humane League', 'Changemaker Captain', '2019-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/brooke-shephard-865195154/', NULL, NULL, 'Animal welfare')
    ,('Agata Nguyen', 'The Humane League', 'Director of People Operations', '2019-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/agata-nguyen-shrm-cp-3b648629/', NULL, NULL, 'Animal welfare')
    ,('Ariav Feingersch', 'The Humane League', 'Internship', '2015-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ariav-feingersch-27552499/, NULL, 'intern', 'Animal welfare')
    ,('Allie Gunter', 'The Humane League', 'Campaign Coordinator', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/allie-gunter-35371b32/', NULL, NULL, 'Animal welfare')
    ,('Allie Gunter', 'The Humane League', 'Development Coordinator (Temporary position)', '2018-11-01', 'month', '2019-01-01', 'month', 'https://www.linkedin.com/in/allie-gunter-35371b32/', NULL, NULL, 'Animal welfare')
    ,('Vicky Bond', 'The Humane League', 'Corporate Relations Specialist', '2016-11-01', 'month', '2017-04-01', 'month', 'https://www.linkedin.com/in/vicky-bond-b9107936/?originalSubdomain=uk', NULL, NULL, 'Animal welfare')
    ,('Vicky Bond', 'The Humane League', 'Managing Director UK', '2017-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/vicky-bond-b9107936/?originalSubdomain=uk', NULL, NULL, 'Animal welfare')
    ,('Pru Elliott, 'The Humane League', 'UK Corporate Campaigns Coordinator', '2016-07-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/pru-elliott-b471aa62/', NULL, NULL, 'Animal welfare') 
    ,('Pru Elliott, 'The Humane League', 'Head of Campaigns', '2017-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/pru-elliott-b471aa62/', NULL, NULL, 'Animal welfare') 
    ,('Cordelia Britton', 'The Humane League', 'Senior Campaigner', '2019-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cordelia-britton-4827a247/', NULL, NULL, 'Animal welfare')
    ,('Maddy Dawe', 'The Humane League', 'Campaigns Coordinator, UK', '2020-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maddy-dawe-ba7b2019a/', NULL, 'part-time', 'Animal welfare')
    ,('Emma Goddard', 'The Humane League', 'National Volunteer Coordinator', '2017-05-01', 'month', '2019-01-01', 'month', 'https://www.linkedin.com/in/emma-goddard-929667109/', NULL, NULL, 'Animal welfare')
    ,('Emma Goddard', 'The Humane League', 'Programs Lead', '2019-01-01', 'month', PULL, PULL, 'https://www.linkedin.com/in/emma-goddard-929667109/', NULL, NULL, 'Animal welfare')
    ,('Amy Odene', 'The Humane League UK', 'Global Corporate Relations', '2019-02-02', 'month', '2020-03-01', 'month', 'https://www.linkedin.com/in/amy-odene-29901414b/', NULL, NULL, 'Animal welfare')
    ,('Hannah Yates', 'The Humane League', 'Communications Coordinator', '2017-06-01', 'month', '2019-01-01', 'month', 'https://www.linkedin.com/in/hannah-yates-387b5189/', NULL, NULL, 'Animal welfare')
    ,('Hannah Yates', 'The Humane League', 'Communications Manager', '2019-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/hannah-yates-387b5189/', NULL, NULL, 'Animal welfare')
    ,('Klara Schmidt', 'The Humane League UK', 'City Leader Volunteer', '2017-08-01', 'month', '2019-01-01', 'month', 'https://www.linkedin.com/in/kjjschmidt/?originalSubdomain=uk', NULL, NULL, 'Animal welfare')
    ,('Paulina Zyskowski', 'The Humane League', 'The Humane League Student Outreach Intern', '2018-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/paulina-zyskowski-a67544119/', NULL, NULL, 'Animal welfare')
    ,('Stephanie Chase', 'The Humane League', 'Intern', '2017-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/stephanie-chase-0011a456/', NULL, NULL, 'Animal welfare')
    ,('Hannah Truxell', 'The Humane League', 'Staff Attorney', '2019-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/hannahtruxell/', NULL, 'full-time', 'Animal welfare')
    ,('Sydney South', 'The Humane League', 'Graphic Designer', '2017-10-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sydney-south-0b950185/', NULL, NULL, 'Animal welfare')
    ,('Ashley Zebro', 'The Humane League', 'Executive Assistant', '2017-10-01', 'month', '2020-02-01', 'month', 'https://www.linkedin.com/in/ashley-zebro-47612b74/', NULL, NULL, 'Animal welfare')
    ,('Ashley Zebro', 'The Humane League', 'Operations Coordinator', '2020-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ashley-zebro-47612b74/', NULL, NULL, 'Animal welfare')
    ,('Skye Walker', 'The Humane League', 'Changemaker Volunteer', '2020-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/skye-walker-230474170/', NULL, NULL, 'Animal welfare')
    ,('Sarah De Munck', 'The Humane League', 'Operations Manager', '2016-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sarahdemunck/', NULL, NULL, 'Animal welfare')
    ,('Giovana T.', 'The Humane League', 'Animal Welfare Specialist', '2018-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/giovana-t-15767689/', NULL, NULL, 'Animal welfare')
    ,('Anne-Marie Renier', 'The Humane League', 'Development Coordinator', '2018-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/annemarierenier/', NULL, NULL, 'Animal welfare')
    ,('Adam Peditto', 'The Humane League', 'Video Producer', '2014-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/adampeditto/', NULL, NULL, 'Animal welfare')
    ,('Adam Peditto', 'The Humane League', 'Video Production Manager', '2019-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/adampeditto/', NULL, NULL, 'Animal welfare')
    ,('Olivia Jannuzzi','The Humane League', 'Campaign Assistant', NULL, NULL, NULL, NULL, 'https://www.linkedin.com/in/olivia-jannuzzi-4647a5ba/', NULL, NULL, 'Animal welfare')
    ,('Cecilia Valenza, 'The Humane League', 'Advisory committee member at Open Wings Alliance - OWA', '2020-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cecilia-valenza/', NULL, 'full-time', 'Animal welfare')
    ,('Janosch L.', 'The Humane League', 'Research Associate', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/janosch-l-728240138/', NULL, NULL, 'Animal welfare')
    ,('Morgan Nati', 'The Humane League', 'Associate Counsel', '2019-09-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/morgannati/', NULL, NULL, 'Animal welfare')
    ,('Karen Nilsen', 'The Humane League', 'Director of Digital Communications Strategy', '2020-05-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/karen-nilsen/', NULL, 'full-time', 'Animal welfare')
    ,('Edie Bowles', 'The Humane League', 'Trustee', '2018-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/edie-bowles-b2500614/', NULL, NULL, 'Animal welfare')
    ,('Michael Scandle', 'The Humane League', 'Volunteer', '2013-11-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/michael-scandle-91929183/', NULL, 'volunteer', 'Animal welfare')
    ,('Madeleine Jones', 'The Humane League', 'Community Engagement Research Fellow', '2020-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/madeleine-a-jones/', NULL, NULL, 'Animal welfare')
    ,('Sajani Fernando', 'The Humane League', 'Communications Fellow', '2020-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sajanif/', NULL, 'intern', 'Animal welfare')
    ,('Gabrielle Sweetman', 'The Humane League', 'Veg Advocacy Fellow', '2020-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/gabrielle-sweetman-3b1136140/', NULL, NULL, 'Animal welfare')
    ,('Lily Lu-Lerner', 'The Humane League', 'Changemaker Captain', '2019-12-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/lily-lu-lerner/', NULL, 'intern', 'Animal welfare')
    ,('Emily Glassman', 'The Humane League', 'Social Media Analyst', '2017-02-01', 'month', '2017-02-01', 'month', 'https://www.linkedin.com/in/emily-glassman-102315157/', NULL, NULL, 'Animal welfare')
    ,('Emily Glassman', 'The Humane League', 'Volunteer', '2012-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/emily-glassman-102315157/', NULL, 'volunteer', 'Animal welfare')
    ,('Darrell Sawczuk', 'The Humane League', 'Social Media Volunteer', '2019-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/darrell-sawczuk-a746a9188/', NULL, NULL, 'Animal welfare')
    ,('Maho Cavalier', 'The Humane League, Japan', 'Regional Manager', '2017-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/maho-cavalier-98604164/',  NULL, 'full-time', 'Animal welfare')
    ,('Cristina Diniz', 'The Humane League', 'Latin America Coordinator for the Open Wing Alliance', '2019-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/cristinadiniz/', NULL, NULL, 'Animal welfare')
    ,('Jennifer Ashley', 'The Humane League', 'Development Coordinator', '2019-11-01', NULL, NULL, NULL, 'https://www.linkedin.com/in/jennifernashley/', NULL, 'part-time', 'Animal welfare')
    ,('Asvini Ravindran', 'The Humane League', 'New Media Intern', '2018-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/asviniravindran/', NULL, NULL, 'Animal welfare')
    ,('Nicole Birkhold', 'The Humane League', 'Production Artist', '2019-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/nicole-birkhold-3a7233b/', NULL, NULL, 'Animal welfare')
    ,('Rebecca Coleman Lerback', 'The Humane League', 'Senior Donor Relations Officer', '2020-08-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/rebecca-coleman-lerback-06211b6/', NULL, NULL, 'Animal welfare')
    ,('David Marten', 'The Humane League', 'Web Developer', '2019-06-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/david-marten-035226a3/', NULL, NULL, 'Animal welfare')
    ,('Lydia Chaudhry', 'The Humane League', 'Operations Support & Volunteer Coordinator', '2009-01-01', 'year', '2015-01-01', 'year', 'https://www.linkedin.com/in/lydia-chaudhry-7515a858/',  NULL, NULL, 'Animal welfare')
    ,('Lydia Chaudhry', 'The Humane League', 'Organizer, Philadelphia Vegfest', '2014-01-01', 'year', '2015-01-01', 'year', 'https://www.linkedin.com/in/lydia-chaudhry-7515a858/',  NULL, NULL, 'Animal welfare')
    ,('Lydia Chaudhry', 'The Humane League', 'Member Board Of Directors', '2013-01-01', 'year', NULL, NULL, 'https://www.linkedin.com/in/lydia-chaudhry-7515a858/',  NULL, NULL, 'Animal welfare')
    ,('Alexandria Beck', 'The Humane League', 'Denver Grassroots Director and Regional Grassroots Manager', '2015-03-01', 'month', '2017-04-01', 'month', 'https://www.linkedin.com/in/alexandriabeck/', NULL, NULL, 'Animal welfare')
    ,('Alexandria Beck', 'The Humane League', 'Director, Open Wing Alliance', '2017-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/alexandriabeck/', NULL, NULL, 'Animal welfare')
    ,('Ellie Donohue-Miller', 'The Humane League', 'OWA Campaigns Manager', '2017-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ellie-donohue-miller-2789a6121/', NULL, NULL, 'Animal welfare')
    ,('Wendy Watts', 'The Humane League', 'Vice President, Legal and General Counsel', '2017-02-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/wendy-watts/', NULL, NULL, 'Animal welfare')
    ,('Jessika Griffin', 'The Humane League', 'Regional Field Organizer', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/jessika-griffin/', NULL, NULL, 'Animal welfare')
    ,('Beau Broughton', 'The Humane League', 'Grassroots Director', San Diego', '2015-05-01', 'month', '2018-09-01', 'month', 'https://www.linkedin.com/in/beauabroughton/', NULL, NULL, 'Animal welfare')
    ,('Beau Broughton', 'The Humane League', 'Grassroots Engagement Manager', '2018-09-01', 'month', '2019-03-01', 'month', 'https://www.linkedin.com/in/beauabroughton/', NULL, NULL, 'Animal welfare')
    ,('Beau Broughton', 'The Humane League', 'Regional Organizing Manager', '2019-03-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/beauabroughton/', NULL, NULL, 'Animal welfare')
    ,('Aaron Ross', 'The Humane League', 'Vice President of Policy and Strategy', '2005-01-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/aaron-ross-303b48166/', NULL, NULL, 'Animal welfare')
    ,('Rachel Atcheson', 'The Humane League', 'Philadelphia Campaign Director', '2013-08-01', 'month', '2015-07-01', 'month', 'https://www.linkedin.com/in/rachel-atcheson-517b47a0/', NULL, NULL, 'Animal welfare')
    ,('Rachel Atcheson', 'The Humane League', 'Senior Campus Outreach Director', '2015-08-01', 'month', '2016-12-01', 'month', 'https://www.linkedin.com/in/rachel-atcheson-517b47a0/', NULL, NULL, 'Animal welfare')
    ,('Elyssa Diehl', 'The Humane League', 'South Florida Grassroots Director', '2014-08-01', 'month', '2016-06-01', 'month', 'https://www.linkedin.com/in/elyssa-s-diehl/', NULL, NULL, 'Animal welfare')
    ,('Elyssa Diehl', 'The Humane League', 'General Counsel', '2016-06-01', 'month', '2016-12-01', 'month', 'https://www.linkedin.com/in/elyssa-s-diehl/', NULL, NULL, 'Animal welfare')
    ,('Elyssa Diehl', 'The Humane League', 'Of Counsel', '2016-12-01', 'month', '2017-02-01', 'month', 'https://www.linkedin.com/in/elyssa-s-diehl/', NULL, NULL, 'Animal welfare')
    ,('Rachel Black', 'The Humane League', 'Volunteer', '2014-01-01', 'month', '2019-02-01', 'month', 'https://www.linkedin.com/in/rachel-black-8631a52b/', NULL, NULL, 'Animal welfare')
    ,('Rachel Black', 'The Humane League', 'Philadelphia Director', '2015-06-01', 'month', '2019-02-01', 'month', 'https://www.linkedin.com/in/rachel-black-8631a52b/', NULL, NULL, 'Animal welfare')
    ,('Rachel Black', 'The Humane League', 'Senior National Volunteer Coordinator', '2017-01-01', 'month', '2019-02-01', 'month', 'https://www.linkedin.com/in/rachel-black-8631a52b/', NULL, NULL, 'Animal welfare')
    ,('Di Lamont', 'The Humane League', 'Campaign Coordinator', '2015-03-01', 'month', '2015-12-01', 'month', 'https://www.linkedin.com/in/di-lamont/', 'Based in the Greater Chicago Area', NULL, 'Animal welfare')
    ,('Di Lamont', 'The Humane League', 'Campus Campaigns Manager', '2015-12-01', 'month', '2016-07-01', 'month', 'https://www.linkedin.com/in/di-lamont/', NULL, NULL, 'Animal welfare')
    ,('Di Lamont', 'The Humane League', 'Global Alliance Manager', '2016-07-01', 'month', '2017-02-01', 'month', 'https://www.linkedin.com/in/di-lamont/', 'Based in the San Francisco Bay Area', NULL, 'Animal welfare')
    ,('Ana Ortega', 'The Humane League Mexico', 'Managing Director', '2015-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/ana-ortega-9984625a/?originalSubdomain=mx', 'Based in Mexico', 'full-time', 'Animal welfare')
    ,('Maddie Segal', 'The Humane League', 'Charlotte Director', '2015-06-01', 'month', '2017-06-01', 'month', 'https://www.linkedin.com/in/maddiesegal/', 'Based in Charlotte, North Carolina Area', NULL, 'Animal welfare')
    ,('Maddie Segal', 'The Humane League', 'Director of Grassroots Engagement', '2017-06-01', 'month', '2019-04-01', 'month', 'https://www.linkedin.com/in/maddiesegal/', NULL, NULL, 'Animal welfare')
    ,('Maddie Segal', 'The Humane League', 'Fellowship Manager', '2019-04-01', 'month', '2020-02-01', 'month', 'https://www.linkedin.com/in/maddiesegal/', NULL, NULL, 'Animal welfare')
    ,('Heather Bolint', 'The Humane League', 'Seattle Director', '2014-09-01', 'month', '2017-06-01', 'month', 'https://www.linkedin.com/in/heather-bolint/', 'Based in Seattle', NULL, 'Animal welfare')
    ,('Ethan Dussault', 'The Humane League', 'Dallas Director', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20150815225839/http://www.thehumaneleague.org/our-story/', NULL, NULL, 'Animal welfare')
    ,('Rochelle Marrett-Smith', 'The Humane League', 'Dallas Director', '2015-11-01', NULL, '2017-05-01', 'month', 'https://www.linkedin.com/in/rochelle-marrett-smith-92675749/', 'Based in Dallas', NULL, 'Animal welfare')
    ,('Laura Nicole Miller', 'The Humane League', title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area)
    ,('Sarah De Munck', 'The Humane League', 'Operations Manager', '2016-04-01', 'month', NULL, NULL, 'https://www.linkedin.com/in/sarahdemunck/', NULL, NULL, 'Animal welfare')
    ,('Meghan Smith', 'The Humane League', 'Atlanta Grassroots Director', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20170328195214/http://www.thehumaneleague.com/our-story/', NULL, NULL, 'Animal welfare')
    ,('Zoë Sigle', 'The Humane League', 'Grassroots Director', '2016-07-01', 'month', '2018-04-01', 'month', 'https://www.linkedin.com/in/zoesigle/', NULL, NULL, 'Animal welfare')
    ,('Zoë Sigle', 'The Humane League', 'Senior Grassroots Director', '2018-04-01', 'month', '2018-12-01', 'month', 'https://www.linkedin.com/in/zoesigle/', NULL, NULL, 'Animal welfare')
    ,('Zoë Sigle', 'The Humane League', 'Corporate Relations Specialist', '2018-12-01', 'month', '2020-08-01', 'month', 'https://www.linkedin.com/in/zoesigle/', NULL, NULL, 'Animal welfare')
    ,('Jeni Haines', 'The Humane League', 'Corporate Relations Manager, Latin America', NULL, NULL, NULL, NULL, 'https://web.archive.org/web/20170512030342/http://thehumaneleague.com:80/our-story', NULL, NULL, 'Animal welfare')
    ,('Zoe Novic', 'The Humane League', 'Grassroots Director, San Francisco', '2016-06-01', 'month', '2019-08-01', 'month', 'https://www.linkedin.com/in/zoe-novic-17045b169/', NULL, NULL, 'Animal welfare') 
