insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, ai_safety_relation, subject, employment_type, cause_area) values
    ('Andrew Critch','Berkeley Existential Risk Initiative','Executive Director',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Kenzi Amodei','Berkeley Existential Risk Initiative','Interim Deputy Director','2017-07-01','month','2018-03-08','month','http://existence.org/team/ http://existence.org/08-2017-semi-annual-report.pdf https://web.archive.org/web/20180308063244/http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Rebecca Raible','Berkeley Existential Risk Initiative','Writer and Operations Manager','2017-08-01','month',NULL,NULL,'http://existence.org/team/ http://existence.org/08-2017-semi-annual-report.pdf',NULL,'GCR organization',NULL,'part-time','AI safety')
    ,('Kyle Scott','Berkeley Existential Risk Initiative','Project Manager','2017-10-01','month',NULL,NULL,'http://existence.org/2017/11/03/activity-update-october-2017.html https://archive.is/esMXe',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Gina Stuessy','Berkeley Existential Risk Initiative','Operations Consulting',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Michael Keenan','Berkeley Existential Risk Initiative','IT Support',NULL,NULL,'2018-03-08','month','http://existence.org/team/ https://web.archive.org/web/20180308063244/http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Andrew Snyder-Beattie','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Malo Bourgon','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Seán Ó hÉigeartaigh','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Stuart Russell','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Jacob Tsimerman','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Jaan Tallinn','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'GCR organization',NULL,NULL,'AI safety')
    ,('Jeremy Schlatter','Berkeley Existential Risk Initiative','Software Engineer','2017-11-01','month',NULL,NULL,'https://www.linkedin.com/in/jeremy-schlatter/',NULL,'position','software engineering',NULL,'AI safety')
    ,('Colleen Gleason','Berkeley Existential Risk Initiative','Operations & Finance Manager','2018-03-21','year',NULL,NULL,'http://existence.org/team/',NULL,'position','general','full-time','AI safety')
    ,('Matthew Fallshaw','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'position',NULL,'advisor','AI safety')
    ,('Sam Bankman-Fried','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'position',NULL,'advisor','AI safety')
    ,('Andrew Critch','Berkeley Existential Risk Initiative','Board chair',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'position',NULL,'board member','AI safety')
    ,('Eric Rogstad','Berkeley Existential Risk Initiative','Board treasurer',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'position',NULL,'board member','AI safety')
    ,('Qiaochu Yuan','Berkeley Existential Risk Initiative','Board secretary',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,'position',NULL,'board member','AI safety')
    ,('Josh Jacobson','Berkeley Existential Risk Initiative','Collaboration Manager & Project Manager','2018-09-03','month',NULL,NULL,'https://web.archive.org/web/20180903104753/http://existence.org/team/',NULL,'position',NULL,'full-time','AI safety')
;
