# Snapshots used:
# https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team
# https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team
# https://web.archive.org/web/20160729025438/http://www.gfi.org:80/our-team

insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, employment_type, cause_area) values
    ('Bruce Friedrich','The Good Food Institute','Executive Director',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Chris Kerr','The Good Food Institute','Entrepreneur in Residence',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Brian Kateman','The Good Food Institute','Innovation Manager',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Milena Esherick','The Good Food Institute','Senior Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Khaled bin Alwaleed','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Josh Balk','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Ryan Bethencourt','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Kevin Boylan','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Asheem Chandna','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Liz Dee','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Brad Goldberg','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Alinta Hawkins','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Chuck Laue','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Craig Phillips','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Mark Post','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Alicia Robb','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Chris Roth','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Chad Sarno','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Derek Sarno','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Kurt Schmidinger','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Ajit Singh','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Shen Tong','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Susan Vitka','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Suzy Welch','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Eron Zehavi','The Good Food Institute','Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20160509141206/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Nicole Negowetti','The Good Food Institute','Policy Director','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Christie Lagally','The Good Food Institute','Senior Scientist','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Liz Specht','The Good Food Institute','Senior Scientist','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Jaime Surenkamp','The Good Food Institute','Senior Advisor','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Emily Byrd','The Good Food Institute','Communications Manager','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Reannon Branchesi','The Good Food Institute','Executive Assistant','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
    ,('Matt Prescott','The Good Food Institute','Advisor','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Uma Valeti','The Good Food Institute','Advisor','2016-06-27','month',NULL,NULL,'https://web.archive.org/web/20160627185951/http://www.gfi.org:80/our-team',NULL,'advisor','Animal welfare')
    ,('Clare Bland','The Good Food Institute','Development Director','2016-07-29','month',NULL,NULL,'https://web.archive.org/web/20160729025438/http://www.gfi.org:80/our-team',NULL,NULL,'Animal welfare')
;
