create table positions(
    position_id int(11) not null auto_increment primary key,
    person varchar(40) not null,
    organization varchar(200) not null,
    title varchar(100),
    start_date date,
    start_date_precision enum('day','month','year','multi-year'),
    # Of the known dates on which the person was doing something else
    # besides the current position prior to the current position, this is the
    # latest one. This allows us to guess at the start_date from the "past"
    # direction. It works like
    #     sup{t : t is before position}
    start_date_lower_guess date,
    # Of the known dates on which the position was held, this is the earliest
    # one. This allows us to guess at the start_date from the "future"
    # direction. It works like
    #     inf{t : position held at time t}
    start_date_upper_guess date,
    end_date date,
    end_date_precision enum('day','month','year','multi-year'),
    # Of the known dates on which the position was held, this is the latest
    # one. This allows us to guess at the end_date from the "past" direction.
    # It works like
    #     sup{t : position held at time t}
    end_date_lower_guess date,
    # Of the known dates on which the person was doing something else
    # besides the current position after the current position, this is the
    # earliest one. This allows us to guess at the end_date from the "future"
    # direction. It works like
    #     inf{t : t is after position}
    end_date_upper_guess date,
    urls varchar(2000),
    ai_safety_related bool default true,
    notes varchar(2000) default null
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into positions(person, organization, title, start_date, start_date_precision, end_date, end_date_precision, urls, notes, start_date_lower_guess, start_date_upper_guess, end_date_lower_guess, end_date_upper_guess) values
    ('Andrej Karpathy','OpenAI','Research Scientist','2016-01-01','year','2017-06-01','month','http://cs.stanford.edu/people/karpathy/ https://archive.is/37L6s','The given description is "Deep Learning, Generative Models, Reinforcement Learning"',NULL,NULL,NULL,NULL)
    ,('Eliezer Yudkowsky','Machine Intelligence Research Institute','Senior Research Fellow',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Alex Altair','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Mihaly Barasz','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Paul Christiano','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Daniel Dewey','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Benya Fallenstein','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Marcello Herreshoff','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Bill Hibbard','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Patrick LaVictoire','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Nate Soares','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Kaj Sotala','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Nisan Stiennon','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Paul Christiano','OpenAI',NULL,'2017-01-01','month',NULL,NULL,'https://paulfchristiano.com/ai/ https://archive.is/Tcqbl https://arxiv.org/pdf/1706.03741.pdf','The description given is "working on alignment"',NULL,NULL,NULL,NULL)
    ,('Yura Burda','OpenAI',NULL,'2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Ian Goodfellow','OpenAI',NULL,'2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Alec Radford','OpenAI',NULL,'2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Tim Salimans','OpenAI',NULL,'2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Peter Chen','OpenAI','Intern','2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Rocky Duan','OpenAI','Intern','2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Linxi Fan','OpenAI','Intern','2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Jon Gauthier','OpenAI','Intern','2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Jonathan Ho','OpenAI','Intern','2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Rein Houthooft','OpenAI','Intern','2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Eric Price','OpenAI','Intern','2016-03-31','year',NULL,NULL,'https://blog.openai.com/team-plus-plus/ https://web.archive.org/web/20171024174215/https://blog.openai.com/team-plus-plus/',NULL,NULL,NULL,NULL,NULL)
    ,('Pieter Abbeel','OpenAI','Research Scientist','2016-01-01','year',NULL,NULL,'http://people.eecs.berkeley.edu/~pabbeel/ https://blog.openai.com/welcome-pieter-and-shivon/',NULL,NULL,NULL,NULL,NULL)
    ,('Shivon Zilis','OpenAI','Advisor','2016-04-26','year',NULL,NULL,'https://blog.openai.com/welcome-pieter-and-shivon/',NULL,NULL,NULL,NULL,NULL)
    ,('Marcin Andrychowicz','OpenAI',NULL,'2016-05-25','year',NULL,NULL,'https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Rafał Józefowicz','OpenAI',NULL,'2016-05-25','year',NULL,NULL,'https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Kate Miltenberger','OpenAI',NULL,'2016-05-25','year',NULL,NULL,'https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Ludwig Pettersson','OpenAI',NULL,'2016-05-25','year',NULL,NULL,'https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Jonas Schneider','OpenAI','Engineering Lead, Robotics','2016-04-01','month',NULL,NULL,'https://www.linkedin.com/in/jonas-schneider/ https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Jie Tang','OpenAI',NULL,'2016-05-25','year',NULL,NULL,'https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Prafulla Dhariwal','OpenAI','Intern','2016-05-25','year',NULL,NULL,'https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Paul Christiano','OpenAI','Intern','2016-05-25','year',NULL,NULL,'https://blog.openai.com/team-update/ https://web.archive.org/web/20171024175425/https://blog.openai.com/team-update/',NULL,NULL,NULL,NULL,NULL)
    ,('Dario Amodei','OpenAI','Team Lead for AI Safety','2016-07-01','month',NULL,NULL,'https://www.linkedin.com/in/dario-amodei-3934934/ https://www.crunchbase.com/person/dario-amodei https://blog.openai.com/team-update-august/ https://arxiv.org/pdf/1706.03741.pdf','Description says "working on a combination of reinforcement learning, imitation learning, and AI safety".',NULL,NULL,NULL,NULL)
    ,('Ilya Sutskever','OpenAI','Co-Founder and Research Director','2016-01-01','month',NULL,NULL,'https://www.linkedin.com/in/ilya-sutskever-45978618/ http://www.cs.toronto.edu/~ilya/ https://en.wikipedia.org/wiki/Ilya_Sutskever',NULL,NULL,NULL,NULL,NULL)
    ,('Durk Kingma','OpenAI','Machine Learning Research Scientist','2015-12-01','month',NULL,NULL,'https://www.linkedin.com/in/durk-kingma-58b3564/ http://dpkingma.com/ https://web.archive.org/web/20171024182419/http://dpkingma.com/',NULL,NULL,NULL,NULL,NULL)
    ,('Greg Brockman','OpenAI','Co-Founder and CTO','2015-12-01','month',NULL,NULL,'https://gregbrockman.com/ https://www.technologyreview.com/lists/innovators-under-35/2017/visionary/greg-brockman/ https://blog.gregbrockman.com/define-cto-openai',NULL,NULL,NULL,NULL,NULL)
    ,('Wojciech Zaremba','OpenAI','Head of Robotics research','2015-12-01','month',NULL,NULL,'https://en.wikipedia.org/wiki/Wojciech_Zaremba http://wojzaremba.com/',NULL,NULL,NULL,NULL,NULL)
    ,('John Schulman','OpenAI','Research Scientist','2015-12-01','month',NULL,NULL,'http://joschu.net/ https://blog.openai.com/introducing-openai/',NULL,NULL,NULL,NULL,NULL)
    ,('Trevor Blackwell','OpenAI',NULL,'2015-12-01','month',NULL,NULL,'https://blog.openai.com/introducing-openai/',NULL,NULL,NULL,NULL,NULL)
    ,('Vicki Cheung','OpenAI',NULL,'2015-12-01','month',NULL,NULL,'https://blog.openai.com/introducing-openai/',NULL,NULL,NULL,NULL,NULL)
    ,('Pamela Vagata','OpenAI',NULL,'2015-12-01','month',NULL,NULL,'https://blog.openai.com/introducing-openai/',NULL,NULL,NULL,NULL,NULL)
    ,('Filip Wolski','OpenAI',NULL,'2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Jack Clark','OpenAI',NULL,'2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Scott Gray','OpenAI',NULL,'2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Zain Shah','OpenAI',NULL,'2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Catherine Olsson','OpenAI','Intern or visitor','2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/ https://twitter.com/catherineols?lang=en',NULL,NULL,NULL,NULL,NULL)
    ,('Harri Edwards','OpenAI','Intern or visitor','2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Igor Mordatch','OpenAI','Intern or visitor','2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Taco Cohen','OpenAI','Intern or visitor','2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Tambet Matiisen','OpenAI','Intern or visitor','2016-08-16','year',NULL,NULL,'https://blog.openai.com/team-update-august/',NULL,NULL,NULL,NULL,NULL)
    ,('Tom Brown','OpenAI','Member of Technical Staff','2016-01-01','year',NULL,NULL,'https://www.linkedin.com/in/nottombrown/ http://ai.vision/ https://web.archive.org/web/20171024192811/http://ai.vision/ https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Aleks Kamko','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Alex Ray','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Ankur Handa','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Bob McGrew','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Christopher Berner','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Erika Reinhardt','OpenAI','Engineering Director','2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Jakub Pachocki','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Jeremy Schlatter','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Jonathan Gray','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Peter Welinder','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Rachel Fong','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Shariq Hashme','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Szymon Sidor','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Yaroslav Bulatov','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Catherine Olsson','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Jonathan Ho','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Peter Chen','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Prafulla Dhariwal','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Rein Houthooft','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Rocky Duan','OpenAI',NULL,'2017-01-30','year',NULL,NULL,'https://blog.openai.com/team-update-january/',NULL,NULL,NULL,NULL,NULL)
    ,('Nick Bostrom','Future of Humanity Institute','Founding Director',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Armstrong','Future of Humanity Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/quarterly-update-summer-2017/',NULL,NULL,NULL,NULL,NULL)
    ,('Eric Drexler','Future of Humanity Institute','Senior Research Fellow',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/eric-drexler/ https://www.fhi.ox.ac.uk/quarterly-update-summer-2017/',NULL,NULL,NULL,NULL,NULL)
    ,('Miles Brundage','Future of Humanity Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/miles-brundage/',NULL,NULL,NULL,NULL,NULL)
    ,('Owain Evans','Future of Humanity Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/owain-evans/ https://www.fhi.ox.ac.uk/quarterly-update-summer-2017/',NULL,NULL,NULL,NULL,NULL)
    ,('Allan Dafoe','Future of Humanity Institute','Research Associate','2016-01-01','year',NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/allan-dafoe/ https://www.dropbox.com/s/m94typwhjadf6s8/DafoeCV.pdf?dl=1',NULL,NULL,NULL,NULL,NULL)
    ,('Carl Shulman','Future of Humanity Institute','Research Associate',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/carl-shulman/',NULL,NULL,NULL,NULL,NULL)
    ,('Paul Christiano','Future of Humanity Institute','Research Associate',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/paul-christiano/',NULL,NULL,NULL,NULL,NULL)
    ,('Robin Hanson','Future of Humanity Institute','Research Associate',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/robin-hanson/',NULL,NULL,NULL,NULL,NULL)
    ,('Jan Leike','Future of Humanity Institute','Research Associate',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/jan-leike/ https://www.fhi.ox.ac.uk/quarterly-update-summer-2017/',NULL,NULL,NULL,NULL,NULL)
    ,('Katja Grace','Future of Humanity Institute','Research Associate',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/katja-grace/',NULL,NULL,NULL,NULL,NULL)
    ,('Seán Ó hÉigeartaigh','Future of Humanity Institute','Research Associate',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/sean-o-heigeartaigh/',NULL,NULL,NULL,NULL,NULL)
    ,('Carrick Flynn','Future of Humanity Institute','Research Project Manager','2015-11-01','month',NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/carrick-flynn/ https://www.fhi.ox.ac.uk/wp-content/uploads/Carrick-Flynn-CV_Jan-2016-1.doc',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Snyder-Beattie','Future of Humanity Institute','Director of Research','2015-12-01','month',NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/andrew-snyder-beattie/ https://www.fhi.ox.ac.uk/wp-content/uploads/Andrew-Snyder-Beattie.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Snyder-Beattie','Future of Humanity Institute','Academic Project Manager','2013-11-01','month','2015-12-01','month','https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/andrew-snyder-beattie/ https://www.fhi.ox.ac.uk/wp-content/uploads/Andrew-Snyder-Beattie.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Ben Garfinkel','Future of Humanity Institute','Visiting Researcher',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/ben-garfinkel-bio/',NULL,NULL,NULL,NULL,NULL)
    ,('Chelsea Guo','Future of Humanity Institute','Intern in Governance of AI Program',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/about/the-team/ https://www.fhi.ox.ac.uk/team/chelsea-guo/',NULL,NULL,NULL,NULL,NULL)
    ,('Daniel Dewey','Future of Humanity Institute','Research Associate',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/fhi-alumni/',NULL,NULL,NULL,NULL,NULL)
    ,('Vincent C. Müller','Future of Humanity Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/fhi-alumni/ http://www.sophia.de/activities.htm',NULL,NULL,NULL,NULL,NULL)
    ,('Cecilia Tilli','Future of Humanity Institute','Academic Project Manager',NULL,NULL,NULL,NULL,'https://www.fhi.ox.ac.uk/fhi-alumni/',NULL,NULL,NULL,NULL,NULL)
    ,('William Saunders','Future of Humanity Institute','AI Safety Research Intern','2017-07-03','year',NULL,NULL,'https://www.fhi.ox.ac.uk/team/william-saunders/ https://www.fhi.ox.ac.uk/quarterly-update-summer-2017/',NULL,NULL,NULL,NULL,NULL)
    ,('Girish Sastry','Future of Humanity Institute','Visiting Researcher in Machine Learning','2017-07-03','year',NULL,NULL,'https://www.fhi.ox.ac.uk/quarterly-update-summer-2017/ https://www.fhi.ox.ac.uk/team/girish-sastry/',NULL,NULL,NULL,NULL,NULL)
    ,('Neal Jean','Future of Humanity Institute','Research Assistant in Machine Learning','2017-07-03','year',NULL,NULL,'https://www.fhi.ox.ac.uk/quarterly-update-summer-2017/ https://www.fhi.ox.ac.uk/team/neal-jean/ http://nealjean.com/',NULL,NULL,NULL,NULL,NULL)
    ,('Vipul Naik','Machine Intelligence Research Institute',NULL,'2014-01-15','day','2014-08-01','month','https://vipulnaik.com/miri/',NULL,NULL,NULL,NULL,NULL)
    ,('Laurent Orseau','Google DeepMind','Research Scientist',NULL,NULL,NULL,NULL,'https://intelligence.org/2016/06/01/new-paper-safely-interruptible-agents/ http://auai.org/uai2016/proceedings/papers/68.pdf https://motherboard.vice.com/en_us/article/bmv7x5/google-researchers-have-come-up-with-an-ai-kill-switch http://www.bbc.com/news/technology-36472140 https://www.fhi.ox.ac.uk/deepmind-collaboration/',NULL,NULL,NULL,NULL,NULL)
    ,('Andreas Stuhlmüller','Stanford University',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1707.05173.pdf https://stuhlmueller.org/papers/preferences-aaai2016.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Tor Lattimore','University of Alberta',NULL,NULL,NULL,NULL,NULL,'http://auai.org/uai2016/proceedings/papers/20.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Marcus Hutter','Australian National University',NULL,NULL,NULL,NULL,NULL,'http://auai.org/uai2016/proceedings/papers/20.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Jan Leike','Australian National University',NULL,NULL,NULL,NULL,NULL,'http://auai.org/uai2016/proceedings/papers/20.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Noah D. Goodman','Stanford University',NULL,NULL,NULL,NULL,NULL,'https://stuhlmueller.org/papers/preferences-aaai2016.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Laurent Orseau','AgroParisTech',NULL,NULL,NULL,NULL,NULL,'http://agi-conference.org/2012/wp-content/uploads/2012/12/paper_76.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Laurent Orseau','INRA',NULL,NULL,NULL,NULL,NULL,'http://agi-conference.org/2012/wp-content/uploads/2012/12/paper_76.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Mark Ring','IDSIA',NULL,NULL,NULL,NULL,NULL,'http://agi-conference.org/2012/wp-content/uploads/2012/12/paper_76.pdf http://people.idsia.ch/~ring/',NULL,NULL,NULL,NULL,NULL)
    ,('Mark Ring','Università della Svizzera italiana',NULL,NULL,NULL,NULL,NULL,'http://agi-conference.org/2012/wp-content/uploads/2012/12/paper_76.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Mark Ring','SUPSI',NULL,NULL,NULL,NULL,NULL,'http://agi-conference.org/2012/wp-content/uploads/2012/12/paper_76.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Russell','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Pieter Abbeel','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Anca Dragan','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Tom Griffiths','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Bart Selman','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Joseph Halpern','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Michael Wellman','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Satinder Singh Baveja','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Tania Lombrozo','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Mark Nitzberg','Center for Human-Compatible AI','Executive Director',NULL,NULL,NULL,NULL,'http://humancompatible.ai/about http://humancompatible.ai/people/mark-nitzberg.html',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Critch','Center for Human-Compatible AI','Research Scientist',NULL,NULL,NULL,NULL,'http://humancompatible.ai/about http://humancompatible.ai/people/andrew-critch.html',NULL,NULL,NULL,NULL,NULL)
    ,('Gillian Hadfield','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Siddharth Srivastava','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://humancompatible.ai/about',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Critch','Berkeley Existential Risk Initiative','Executive Director',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Kenzi Amodei','Berkeley Existential Risk Initiative','Interim Deputy Director','2017-07-01','month',NULL,NULL,'http://existence.org/team/ http://existence.org/08-2017-semi-annual-report.pdf',NULL,NULL,'2017-07-31','2017-10-31',NULL)
    ,('Rebecca Raible','Berkeley Existential Risk Initiative','Writer and Operations Manager','2017-08-01','month',NULL,NULL,'http://existence.org/team/ http://existence.org/08-2017-semi-annual-report.pdf',NULL,NULL,'2017-08-31','2017-10-31',NULL)
    ,('Gina Stuessy','Berkeley Existential Risk Initiative','Operations Consulting',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Michael Keenan','Berkeley Existential Risk Initiative','IT Support',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Snyder-Beattie','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Malo Bourgon','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Seán Ó hÉigeartaigh','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Russell','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jacob Tsimerman','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jaan Tallinn','Berkeley Existential Risk Initiative','Advisor',NULL,NULL,NULL,NULL,'http://existence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Margaret Boden','Leverhulme Centre for the Future of Intelligence','External Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/margaret-boden/',NULL,NULL,NULL,NULL,NULL)
    ,('Alison Gopnik','Leverhulme Centre for the Future of Intelligence','External Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/alison-gopnik/',NULL,NULL,NULL,NULL,NULL)
    ,('Philip Pettit','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/philip-pettit/',NULL,NULL,NULL,NULL,NULL)
    ,('Martin Rees','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/martin-rees/',NULL,NULL,NULL,NULL,NULL)
    ,('Francesca Rossi','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/francesca-rossi/',NULL,NULL,NULL,NULL,NULL)
    ,('Manuela M. Veloso','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/manuela-veloso/',NULL,NULL,NULL,NULL,NULL)
    ,('Demis Hassabis','Leverhulme Centre for the Future of Intelligence','Advisor',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/demis-hassabis/',NULL,NULL,NULL,NULL,NULL)
    ,('Huw Price','Leverhulme Centre for the Future of Intelligence',NULL,NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/huw-price/',NULL,NULL,NULL,NULL,NULL)
    ,('Zoubin Ghahramani','Leverhulme Centre for the Future of Intelligence',NULL,NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/zoubin-ghahramani/',NULL,NULL,NULL,NULL,NULL)
    ,('Stephen Cave','Leverhulme Centre for the Future of Intelligence','Executive Director and Senior Research Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stephen-cave/ https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69702.html https://archive.is/b4bhr',NULL,NULL,NULL,NULL,NULL)
    ,('Nick Bostrom','Leverhulme Centre for the Future of Intelligence','Spoke Leader and Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/nick-bostrom/',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Russell','Leverhulme Centre for the Future of Intelligence','Spoke Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stuart-russell/',NULL,NULL,NULL,NULL,NULL)
    ,('Murray Shanahan','Leverhulme Centre for the Future of Intelligence','Spoke Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/murray-shanahan/',NULL,NULL,NULL,NULL,NULL)
    ,('Anna Alexandrova','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/anna-alexandrova/',NULL,NULL,NULL,NULL,NULL)
    ,('Marta Halina','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/marta-halina/',NULL,NULL,NULL,NULL,NULL)
    ,('Stephen John','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/stephen-john/',NULL,NULL,NULL,NULL,NULL)
    ,('David Runciman','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/david-runciman/',NULL,NULL,NULL,NULL,NULL)
    ,('Seán Ó hÉigeartaigh','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/sean-heigeartaigh/',NULL,NULL,NULL,NULL,NULL)
    ,('Thomas D. Grant','Leverhulme Centre for the Future of Intelligence','Research Exercise Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/thomas-grant/',NULL,NULL,NULL,NULL,NULL)
    ,('Adrian Weller','Leverhulme Centre for the Future of Intelligence','Project Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/adrian-weller/',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Snyder-Beattie','Leverhulme Centre for the Future of Intelligence','Research Exercise Leader',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/andrew-snyder-beattie/',NULL,NULL,NULL,NULL,NULL)
    ,('Susan Gowans','Leverhulme Centre for the Future of Intelligence','Administrator',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/susan-gowans/',NULL,NULL,NULL,NULL,NULL)
    ,('Sarah Dillon','Leverhulme Centre for the Future of Intelligence','Project Leader and Senior Research Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/sarah-dillon/',NULL,NULL,NULL,NULL,NULL)
    ,('Rune Nyrup','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/rune-nyrup/',NULL,NULL,NULL,NULL,NULL)
    ,('Henry Shevlin','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/henry-shevlin/',NULL,NULL,NULL,NULL,NULL)
    ,('Karina Vold','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/karina-vold/',NULL,NULL,NULL,NULL,NULL)
    ,('Kanta Dihal','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/kanta-dihal/',NULL,NULL,NULL,NULL,NULL)
    ,('Tameem Adel','Leverhulme Centre for the Future of Intelligence','Postdoctoral Researcher',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/tameem-adel/',NULL,NULL,NULL,NULL,NULL)
    ,('José Hernández-Orallo','Leverhulme Centre for the Future of Intelligence','Visiting Scholar',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/jose-hernandez-orallo/',NULL,NULL,NULL,NULL,NULL)
    ,('Beth Singler','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/beth-singler/',NULL,NULL,NULL,NULL,NULL)
    ,('Heather Roff','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/heather-roff/',NULL,NULL,NULL,NULL,NULL)
    ,('Lucy Cheke','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/lucy-cheke/',NULL,NULL,NULL,NULL,NULL)
    ,('Michael A. Osborne','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/michael-osborne/',NULL,NULL,NULL,NULL,NULL)
    ,('Alan Winfield','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/alan-winfield/',NULL,NULL,NULL,NULL,NULL)
    ,('Neil Lawrence','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/neil-lawrence/',NULL,NULL,NULL,NULL,NULL)
    ,('Kay Firth-Butterfield','Leverhulme Centre for the Future of Intelligence','Associate Fellow',NULL,NULL,NULL,NULL,'http://lcfi.ac.uk/about/people/ http://lcfi.ac.uk/about/people/kay-firth-butterfield/',NULL,NULL,NULL,NULL,NULL)
    ,('Daniel Dewey','Open Philanthropy Project','Program Officer for Potential Risks from Advanced Artificial Intelligence','2015-01-01','year',NULL,NULL,'https://www.openphilanthropy.org/about/team/daniel-dewey',NULL,NULL,NULL,NULL,NULL)
    ,('Katja Grace','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Michael Wulfsohn','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Finan Adamson','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Connor Flexman','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Justis Mills','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Jimmy Rintjema','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Paul Christiano','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('John Salvatier','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Ben Hoffman','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Stephanie Zolayvar','AI Impacts',NULL,NULL,NULL,NULL,NULL,'https://aiimpacts.org/about/',NULL,NULL,NULL,NULL,NULL)
    ,('Jaan Tallinn','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Max Tegmark','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Viktoriya Krakovna','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Anthony Aguirre','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Meia Chita-Tegmark','Future of Life Institute','Co-Founder',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Alan Alda','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Nick Bostrom','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Erik Brynjolfsson','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('George Church','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Morgan Freeman','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Alan Guth','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Stephen Hawking','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Christof Koch','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Elon Musk','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Saul Perlmutter','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Martin Rees','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Francesca Rossi','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Russell','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Frank Wilczek','Future of Life Institute','Advisor',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Ariel Conn','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Tucker Davey','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Richard Mallah','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Lucas Perry','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('David Stanley','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Alan Yan','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Eric Gastfriend','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Grzegorz Orwiński','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jacob Beebe','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Kazue Evans','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Na Li','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Rafael Martinez-Galarza','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Vera Koroleva','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Xin Wen','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Yishuai Du','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Zara Yaqoob','Future of Life Institute',NULL,NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Ales Flidr','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jesse Galef','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Melody Guan','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Peter Haas','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Max Kesin','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Janos Kramar','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Daniel R. Miller','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Chase Moores','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jacob Trefethen','Future of Life Institute','Volunteer',NULL,NULL,NULL,NULL,'https://futureoflife.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Nate Soares','Machine Intelligence Research Institute','Executive Director',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Benya Fallenstein','Machine Intelligence Research Institute','Research Fellow','2014-01-01','year',NULL,NULL,'https://intelligence.org/team/ https://web.archive.org/web/20151123012900/https://intelligence.org/team/',NULL,NULL,'2013-12-31',NULL,NULL)
    ,('Scott Garrabrant','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Marcello Herreshoff','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Sam Eisenstat','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Abram Demski','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Tsvi Benson-Tilsen','Machine Intelligence Research Institute','Assistant Research Fellow',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Katja Grace','Machine Intelligence Research Institute','Researcher, AI Impacts',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Critch','Machine Intelligence Research Institute','Research Fellow (on leave)',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Malo Bourgon','Machine Intelligence Research Institute','Chief Operating Officer',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Alex Vermeer','Machine Intelligence Research Institute','Program Management Analyst',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Rob Bensinger','Machine Intelligence Research Institute','Research Communications Manager',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Aaron Silverbook','Machine Intelligence Research Institute','Office Manager',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Colm Ó Riain','Machine Intelligence Research Institute','Development',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Matthew Graves','Machine Intelligence Research Institute','Staff Writer',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Nick Bostrom','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Russell','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jan Leike','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Bart Selman','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Steve Omohundro','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Gary Drescher','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Luke Muehlhauser','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Robin Hanson','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Christine Peterson','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jed McCaleb','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Jaan Tallinn','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Armstrong','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Ramana Kumar','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Vadim Kosoy','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Edwin Evans','Machine Intelligence Research Institute','Board Chair',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Nate Soares','Machine Intelligence Research Institute','Board Director',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Matthew Fallshaw','Machine Intelligence Research Institute','Board Director',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Eliezer Yudkowsky','Machine Intelligence Research Institute','Board Director',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Anna Salamon','Machine Intelligence Research Institute','Board Director',NULL,NULL,NULL,NULL,'https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Paul Christiano','Open Philanthropy Project','Technical advisor',NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support',NULL,NULL,NULL,NULL,NULL)
    ,('Jacob Steinhardt','Open Philanthropy Project','Technical advisor',NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support',NULL,NULL,NULL,NULL,NULL)
    ,('Christopher Olah','Open Philanthropy Project','Technical advisor',NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support',NULL,NULL,NULL,NULL,NULL)
    ,('Dario Amodei','Open Philanthropy Project','Technical advisor',NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support',NULL,NULL,NULL,NULL,NULL)
    ,('Seth Baum','Global Catastrophic Risk Institute','Executive Director',NULL,NULL,NULL,NULL,'http://gcrinstitute.org/people/ https://arxiv.org/pdf/1607.07730.pdf http://sethbaum.com/ac/2017_AI-RandD.pdf',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Tony Barrett','Global Catastrophic Risk Institute','Director of Research',NULL,NULL,NULL,NULL,'http://gcrinstitute.org/people/ https://arxiv.org/pdf/1607.07730.pdf http://sethbaum.com/ac/2017_AI-RandD.pdf',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Robert de Neufville','Global Catastrophic Risk Institute','Director of Communications',NULL,NULL,NULL,NULL,'http://gcrinstitute.org/people/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Grant Wilson','Global Catastrophic Risk Institute','Deputy Director',NULL,NULL,NULL,NULL,'http://gcrinstitute.org/people/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Mark Fusco','Global Catastrophic Risk Institute','Associate',NULL,NULL,NULL,NULL,'http://gcrinstitute.org/people/','"His research interests include the theology and sociology of global catastrophic risk and the ethics of artificial intelligence."',NULL,'2017-10-31','2017-10-31',NULL)
    ,('Roman Yampolskiy','Global Catastrophic Risk Institute','Associate',NULL,NULL,NULL,NULL,'http://gcrinstitute.org/people/','"His research interests include cybersecurity, biometrics and artificial intelligence safety."',NULL,'2017-10-31','2017-10-31',NULL)
    ,('Roman Yampolskiy','University of Louisville',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1605.02817.pdf https://arxiv.org/pdf/1604.00545v3.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Matthijs Maas','Global Catastrophic Risk Institute','Junior Associate','2016-05-01','month',NULL,NULL,'http://gcrinstitute.org/people/ https://www.linkedin.com/in/matthijsmaas/','"His research interests include the safe governance of artificial intelligence and the effects of emerging technologies on nuclear deterrence stability."','2016-04-30','2016-05-31','2017-10-31',NULL)
    ,('Trevor White','Global Catastrophic Risk Institute','Junior Associate',NULL,NULL,NULL,NULL,'http://gcrinstitute.org/people/','"His research for GCRI focuses on legal liability for risks posed by autonomous machines."',NULL,'2017-10-31','2017-10-31',NULL)
    ,('Matthijs Maas','University of Copenhagen','PhD Fellow in AI governance','2017-09-01','month',NULL,NULL,'https://www.linkedin.com/in/matthijsmaas/',NULL,'2017-08-31','2017-09-30','2017-10-31',NULL)
    ,('Matthijs Maas','Global Politics of Artificial Intelligence Research Group at Yale University and University of Oxford','Researcher','2016-06-01','month',NULL,NULL,'https://www.linkedin.com/in/matthijsmaas/',NULL,'2016-05-31','2016-06-30','2017-10-31',NULL)
    ,('Matthijs Maas','Hague Centre for Strategic Studies','Freelance Analyst','2015-05-01','month','2017-04-01','month','https://www.linkedin.com/in/matthijsmaas/','One of the listed projects is: "A strategic analysis of implications and applications of artificial intelligence for defense and military operations."','2015-04-30','2015-05-31','2017-04-01','2017-05-01')
    ,('Max Daniel','Foundational Research Institute','Executive Director',NULL,NULL,NULL,NULL,'https://foundational-research.org/team/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Brian Tomasik','Foundational Research Institute','Advisor',NULL,NULL,NULL,NULL,'https://foundational-research.org/team/ https://foundational-research.org/artificial-intelligence-and-its-implications-for-future-suffering https://foundational-research.org/international-cooperation-vs-ai-arms-race/ https://foundational-research.org/do-artificial-reinforcement-learning-agents-matter-morally/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Lukas Gloor','Foundational Research Institute','Researcher',NULL,NULL,NULL,NULL,'https://foundational-research.org/team/ https://foundational-research.org/suffering-focused-ai-safety-why-fail-safe-measures-might-be-our-top-intervention/ https://foundational-research.org/altruists-should-prioritize-artificial-intelligence/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Caspar Oesterheld','Foundational Research Institute','Researcher',NULL,NULL,NULL,NULL,'https://foundational-research.org/team/ https://foundational-research.org/backup-utility-functions-fail-safe-ai-technique/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Kaj Sotala','Foundational Research Institute','Associate Researcher',NULL,NULL,NULL,NULL,'https://foundational-research.org/team/ https://foundational-research.org/how-feasible-is-rapid-development-artificial-superintelligence',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Viktoriya Krakovna','Google DeepMind','Research Scientist',NULL,NULL,NULL,NULL,'http://www.aiandsociety.org/en/vikakrakovna/',NULL,NULL,NULL,NULL,NULL)
    ,('Pete Michaud','Center for Applied Rationality','Executive Director',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Anna Salamon','Center for Applied Rationality','President and Co-Founder',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Michael Smith','Center for Applied Rationality','Senior Instructor and Co-Founder',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Duncan Sabien','Center for Applied Rationality','Curriculum Director and Product Head',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Dan Keys','Center for Applied Rationality','Research and Data Analysis',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Lauren Lee','Center for Applied Rationality','Research and Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Jack Carroll','Center for Applied Rationality','Operations Manager',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Adom Hartell','Center for Applied Rationality','Operations',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Elizabeth Garrett','Center for Applied Rationality','Community Manager',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Adam Scholl','Center for Applied Rationality','Instructor and Special Projects',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Ben Sancetta','Center for Applied Rationality','IT Support (contractor)',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Eli Tyre','Center for Applied Rationality','Research and Special Projects (contractor)',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Michael Keenan','Center for Applied Rationality','IT Support (contractor)',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Ben Goldhaber','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Eric Rogstad','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Jordan Tirrell','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Matthew Graves','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Oliver Habryka','Center for Applied Rationality','Adjunct Instructor, Design, and Branding',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Qiaochu Yuan','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Stephanie Zolayvar','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Timothy Telleen-Lawton','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Tsvi Benson-Tilsen','Center for Applied Rationality','Adjunct Instructor',NULL,NULL,NULL,NULL,'http://rationality.org/about/team https://web.archive.org/web/20171101040709/http://rationality.org/about/team',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Nick Bostrom','Google DeepMind','DeepMind Ethics & Society Fellow',NULL,NULL,NULL,NULL,'https://deepmind.com/applied/deepmind-ethics-society/fellows/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Diane Coyle','Google DeepMind','DeepMind Ethics & Society Fellow',NULL,NULL,NULL,NULL,'https://deepmind.com/applied/deepmind-ethics-society/fellows/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Edward W. Felten','Google DeepMind','DeepMind Ethics & Society Fellow',NULL,NULL,NULL,NULL,'https://deepmind.com/applied/deepmind-ethics-society/fellows/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Christiana Figueres','Google DeepMind','DeepMind Ethics & Society Fellow',NULL,NULL,NULL,NULL,'https://deepmind.com/applied/deepmind-ethics-society/fellows/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('James Manyika','Google DeepMind','DeepMind Ethics & Society Fellow',NULL,NULL,NULL,NULL,'https://deepmind.com/applied/deepmind-ethics-society/fellows/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Jeffrey D. Sachs','Google DeepMind','DeepMind Ethics & Society Fellow',NULL,NULL,NULL,NULL,'https://deepmind.com/applied/deepmind-ethics-society/fellows/',NULL,NULL,'2017-10-31','2017-10-31',NULL)
    ,('Sean Legassick','Google DeepMind','Head of DeepMind Ethics & Society','2017-10-04','day',NULL,NULL,'https://www.wired.co.uk/article/deepmind-ethics-and-society-artificial-intelligence https://www.theverge.com/2017/10/4/16417978/deepmind-ai-ethics-society-research-group',NULL,NULL,NULL,NULL,NULL)
    ,('Verity Harding','Google DeepMind','Head of DeepMind Ethics & Society','2017-10-04','day',NULL,NULL,'https://www.wired.co.uk/article/deepmind-ethics-and-society-artificial-intelligence https://www.theverge.com/2017/10/4/16417978/deepmind-ai-ethics-society-research-group',NULL,NULL,NULL,NULL,NULL)
    ,('Demis Hassabis','Google DeepMind','Co-Founder and CEO','2010-09-23','day',NULL,NULL,'https://deepmind.com/about/ https://en.wikipedia.org/wiki/DeepMind',NULL,NULL,NULL,NULL,NULL)
    ,('Mustafa Suleyman','Google DeepMind','Co-Founder and Head of Applied AI','2010-09-23','day',NULL,NULL,'https://deepmind.com/about/ https://en.wikipedia.org/wiki/DeepMind',NULL,NULL,NULL,NULL,NULL)
    ,('Shane Legg','Google DeepMind','Co-Founder and Chief Scientist','2010-09-23','day',NULL,NULL,'https://deepmind.com/about/ https://en.wikipedia.org/wiki/DeepMind https://arxiv.org/pdf/1706.03741.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Miljan Martic','Google DeepMind',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1706.03741.pdf',NULL,NULL,'2017-07-13','2017-07-13',NULL)
    ,('Jan Leike','Google DeepMind',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1706.03741.pdf',NULL,NULL,'2017-07-13','2017-07-13',NULL)
    ,('Rohin Shah','Center for Human-Compatible AI',NULL,NULL,NULL,NULL,NULL,'http://rohinshah.com/ https://archive.is/Tl2BI',NULL,NULL,'2017-11-06','2017-11-06',NULL)
    ,('Wyatt Tessari','Center for Human Success','Founder','2017-07-01','month',NULL,NULL,'https://www.centreforhumansuccess.org/about/who-we-are/ https://archive.is/fGT7H http://effective-altruism.com/ea/1gc/introducing_canadas_first_political_advocacy/',NULL,'2017-06-30','2017-07-31','2017-11-07',NULL)
    ,('David Yu','Center for Human Success',NULL,NULL,NULL,NULL,NULL,'http://effective-altruism.com/ea/1gc/introducing_canadas_first_political_advocacy/',NULL,NULL,NULL,NULL,NULL)
    ,('Simon Beard','Centre for the Study of Existential Risk',NULL,NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69655.html https://archive.is/PTkrC',NULL,NULL,'2017-10-20','2017-10-20',NULL)
    ,('Seán Ó hÉigeartaigh','Centre for the Study of Existential Risk','Executive Director',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69655.html https://archive.is/PTkrC https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/sean-o-heigeartaigh/',NULL,NULL,'2017-10-20','2017-11-07',NULL)
    ,('Shahar Avin','Centre for the Study of Existential Risk','Research Associate',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69655.html https://archive.is/PTkrC https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/shahar-avin/',NULL,NULL,'2017-10-20','2017-11-07',NULL)
    ,('Haydn Belfield','Centre for the Study of Existential Risk','Academic Project Manager',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69655.html https://archive.is/PTkrC https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/haydn-belfield/',NULL,NULL,'2017-10-20','2017-11-07',NULL)
    ,('Martina Kunz','Leverhulme Centre for the Future of Intelligence',NULL,NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69655.html https://archive.is/PTkrC',NULL,NULL,'2017-10-20','2017-10-20',NULL)
    ,('Andrew Ware','University of New Hampshire',NULL,NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/news/lords-ai-committee-written-evidence/ http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/artificial-intelligence-committee/artificial-intelligence/written/69655.html https://archive.is/PTkrC',NULL,NULL,'2017-10-20','2017-10-20',NULL)
    ,('Huw Price','Centre for the Study of Existential Risk','Co-Founder and Academic Director',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Martin Rees','Centre for the Study of Existential Risk','Co-Founder',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Jaan Tallinn','Centre for the Study of Existential Risk','Co-Founder',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Yang Liu','Centre for the Study of Existential Risk','Research Associate',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/yang-liu/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Beth Barnes','Centre for the Study of Existential Risk','Research Affiliate',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/beth-barnes/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Seth Baum','Centre for the Study of Existential Risk','Research Affiliate',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/seth-baum/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Martina Kunz','Centre for the Study of Existential Risk','Research Affiliate',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/martina-kunz/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Ryan Carey','Centre for the Study of Existential Risk','Research Affiliate',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://www.cser.ac.uk/team/ryan-carey/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Margaret Boden','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Nick Bostrom','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('David Chalmers','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Alison Gopnik','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Elon Musk','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Stuart Russell','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Dana Scott','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Murray Shanahan','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Max Tegmark','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Tim Crane','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Stephen Hawking','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Sean Holden','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Adrian Weller','Centre for the Study of Existential Risk','Advisor',NULL,NULL,NULL,NULL,'https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/ https://web.archive.org/web/20171107185800/https://www.cser.ac.uk/team/filter/all/risks-from-artificial-intelligence/',NULL,NULL,'2017-11-07','2017-11-07',NULL)
    ,('Luke Muehlhauser','Machine Intelligence Research Institute','Researcher','2011-01-01','year',NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Luke Muehlhauser','Machine Intelligence Research Institute','Executive Director',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Louie Helm','Machine Intelligence Research Institute','Deputy Director',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Eliezer Yudkowsky','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Malo Bourgon','Machine Intelligence Research Institute','Project Manager',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Kevin Fischer','Machine Intelligence Research Institute','Board Director',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Tomer Kagan','Machine Intelligence Research Institute','Board Director',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Michael Vassar','Machine Intelligence Research Institute','Board Director',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20140209055438/http://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Nate Soares','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Patrick LaVictoire','Machine Intelligence Research Institute','Research Fellow','2015-03-01','month',NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-03-31','2015-05-07',NULL)
    ,('Malo Bourgon','Machine Intelligence Research Institute','Program Management Analyst','2012-01-01','year',NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Alex Vermeer','Machine Intelligence Research Institute','Program Management Analyst','2012-01-01','year',NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Katja Grace','Machine Intelligence Research Institute','Research Assistant','2014-02-01','month',NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/ https://web.archive.org/web/20151123012900/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Rob Bensinger','Machine Intelligence Research Institute','Outreach Coordinator','2013-11-01','month',NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2013-11-30','2015-05-07',NULL)
    ,('Nick Bostrom','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Max Tegmark','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Gary Drescher','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Robin Hanson','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Steve Omohundro','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Moshe Looks','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Roman Yampolskiy','Machine Intelligence Research Institute','Research Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Peter Thiel','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Christine Peterson','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Liron Shapira','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Jed McCaleb','Machine Intelligence Research Institute','General Advisor',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Stuart Armstrong','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Mihaly Barasz','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Tsvi Benson-Tilsen','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Abram Demski','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Scott Garrabrant','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Marcello Herreshoff','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Bill Hibbard','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Kaj Sotala','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Nisan Stiennon','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Jessica Taylor','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Nate Thomas','Machine Intelligence Research Institute','Research Associate',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20150507152542/https://intelligence.org/team/',NULL,NULL,'2015-05-07','2015-05-07',NULL)
    ,('Jessica Taylor','Machine Intelligence Research Institute','Research Fellow','2015-08-01','month',NULL,NULL,'https://web.archive.org/web/20151123012900/https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Critch','Machine Intelligence Research Institute','Research Fellow','2015-09-01','month',NULL,NULL,'https://web.archive.org/web/20151123012900/https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Andrew Lapinski-Barker','Machine Intelligence Research Institute','Office Manager','2015-09-01','month',NULL,NULL,'https://web.archive.org/web/20151123012900/https://intelligence.org/team/',NULL,NULL,NULL,NULL,NULL)
    ,('Christopher Olah','Google Brain',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1606.06565.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Dario Amodei','Google Brain',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1606.06565.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Jacob Steinhardt','Stanford University',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1606.06565.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Paul Christiano','University of California, Berkeley',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1606.06565.pdf https://intelligence.org/files/ProgramEquilibrium.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Dan Mané','Google Brain',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1606.06565.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Jack Gallagher','Machine Intelligence Research Institute','Intern',NULL,NULL,NULL,NULL,'https://intelligence.org/2015/08/31/final-fundraiser-day-announcing-our-new-team/',NULL,NULL,NULL,NULL,NULL)
    ,('Kaya Stechly','Machine Intelligence Research Institute','Intern',NULL,NULL,NULL,NULL,'https://intelligence.org/2015/08/31/final-fundraiser-day-announcing-our-new-team/',NULL,NULL,NULL,NULL,NULL)
    ,('Marcello Herreshoff','Google',NULL,NULL,NULL,NULL,NULL,'https://intelligence.org/files/ProgramEquilibrium.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Mihaly Barasz','Nilcons',NULL,NULL,NULL,NULL,NULL,'https://intelligence.org/files/ProgramEquilibrium.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Patrick LaVictoire','Quixey',NULL,NULL,NULL,NULL,NULL,'https://intelligence.org/files/ProgramEquilibrium.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Louie Helm','Machine Intelligence Research Institute','Director of Development',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20120506220247/http://singinst.org:80/aboutus/team',NULL,NULL,'2012-05-06','2012-05-06',NULL)
    ,('Amy Willey','Machine Intelligence Research Institute','Chief Operating Officer',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20120506220247/http://singinst.org:80/aboutus/team',NULL,NULL,'2011-07-28','2012-05-06',NULL)
    ,('Ray Kurzweil','Machine Intelligence Research Institute','Singularity Summit Co-Founder',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20120506220247/http://singinst.org:80/aboutus/team',NULL,NULL,'2011-07-28','2012-05-06',NULL)
    ,('Anna Salamon','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20120506220247/http://singinst.org:80/aboutus/team',NULL,NULL,'2011-07-28','2012-05-06',NULL)
    ,('Carl Shulman','Machine Intelligence Research Institute',NULL,NULL,NULL,NULL,NULL,'https://web.archive.org/web/20120506220247/http://singinst.org:80/aboutus/team',NULL,NULL,'2012-05-06','2012-05-06',NULL)
    ,('Michael Anissimov','Machine Intelligence Research Institute','Media Director',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20120506220247/http://singinst.org:80/aboutus/team',NULL,NULL,'2011-07-28','2012-05-06',NULL)
    ,('Michael Vassar','Machine Intelligence Research Institute','President',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20110728030001/http://singinst.org/aboutus/team/ https://web.archive.org/web/20100317235453/http://www.singinst.org:80/aboutus/team',NULL,NULL,'2010-03-17','2011-07-28',NULL)
    ,('Steve Rayhawk','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20110728030001/http://singinst.org/aboutus/team/',NULL,NULL,'2011-07-28','2011-07-28',NULL)
    ,('Peter de Blanc','Machine Intelligence Research Institute','Research Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20110728030001/http://singinst.org/aboutus/team/',NULL,NULL,'2011-07-28','2011-07-28',NULL)
    ,('Jasen Murray','Machine Intelligence Research Institute','Program Manager of Visiting Fellows Program',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20110728030001/http://singinst.org/aboutus/team/',NULL,NULL,'2011-07-28','2011-07-28',NULL)
    ,('Pejman Makhfi','Machine Intelligence Research Institute','Director of Venture Development',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20110728030001/http://singinst.org/aboutus/team/',NULL,NULL,'2011-07-28','2011-07-28',NULL)
    ,('David Hart','Machine Intelligence Research Institute','Director of Open Source Projects',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20100317235453/http://www.singinst.org:80/aboutus/team',NULL,NULL,'2010-03-17','2010-03-17',NULL)
    ,('Ben Goertzel','Machine Intelligence Research Institute','Director of Applied Research',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20100317235453/http://www.singinst.org:80/aboutus/team',NULL,NULL,'2010-03-17','2010-03-17',NULL)
    ,('Yoshua Bengio','Montreal Institute for Learning Algorithms',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research',NULL,NULL,'2017-07-01','2017-07-31',NULL)
    ,('Joelle Pineau','Montreal Institute for Learning Algorithms',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research',NULL,NULL,'2017-07-01','2017-07-31',NULL)
    ,('Doina Precup','Montreal Institute for Learning Algorithms',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research',NULL,NULL,'2017-07-01','2017-07-31',NULL)
    ,('Sergey Levine','University of California, Berkeley',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/uc-berkeley-ai-safety-levine-dragan',NULL,NULL,'2017-10-01','2017-10-31',NULL)
    ,('Anca Dragan','University of California, Berkeley',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/uc-berkeley-ai-safety-levine-dragan https://arxiv.org/pdf/1711.02827.pdf',NULL,NULL,'2017-10-01','2017-10-31',NULL)
    ,('Allan Dafoe','Yale University','Assistant Professor of Political Science',NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/yale-university-global-politics-of-ai-dafoe',NULL,NULL,'2017-09-01','2017-09-30',NULL)
    ,('Percy Liang','Stanford University',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/stanford-university-support-percy-liang https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/stanford-university-percy-liang-planning-grant',NULL,NULL,'2017-05-01','2017-05-31',NULL)
    ,('Edward Parson','UCLA School of Law',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/ucla-artificial-intelligence-governance',NULL,NULL,'2017-05-01','2017-05-31',NULL)
    ,('Richard Re','UCLA School of Law',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/ucla-artificial-intelligence-governance',NULL,NULL,'2017-05-01','2017-05-31',NULL)
    ,('Peter Eckersley','Electronic Frontier Foundation',NULL,NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/electronic-frontier-foundation-ai-social',NULL,NULL,'2016-11-01','2016-11-30',NULL)
    ,('Robin Hanson','George Mason University','Associate Professor of Economics',NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios',NULL,NULL,'2016-06-01','2016-06-30',NULL)
    ,('Zac Kenton','Montreal Institute for Learning Algorithms',NULL,NULL,NULL,NULL,NULL,'https://docs.google.com/spreadsheets/d/1iBy--zMyIiTgybYRUQZIm11WKGQZcixaCmIaysRmGvk',NULL,NULL,NULL,NULL,NULL)
    ,('Vladimir Shakirov','Moscow Institute of Physics and Technology',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/abs/1605.04232',NULL,NULL,NULL,NULL,NULL)
    ,('Jim Babcock','Cornell University',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1604.00545v3.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Janos Kramar','University of Montreal',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1604.00545v3.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Bas R. Steunebrink','IDSIA',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Bas R. Steunebrink','Università della Svizzera italiana',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Bas R. Steunebrink','SUPSI',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Kristinn R. Thórisson','Center for Analysis & Design of Intelligent Agents',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Kristinn R. Thórisson','Icelandic Institute for Intelligent Machines',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Jürgen Schmidhuber','IDSIA',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Jürgen Schmidhuber','Università della Svizzera italiana',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Jürgen Schmidhuber','SUPSI',NULL,NULL,NULL,NULL,NULL,'http://people.idsia.ch/~steunebrink/Publications/AGI16_growing_recursive_self-improvers.pdf http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/',NULL,NULL,NULL,NULL,NULL)
    ,('Dylan Hadfield-Menell','University of California, Berkeley',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1711.02827.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Smitha Milli','University of California, Berkeley',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1711.02827.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Pieter Abbeel','University of California, Berkeley',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1711.02827.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Stuart Russell','University of California, Berkeley',NULL,NULL,NULL,NULL,NULL,'https://arxiv.org/pdf/1711.02827.pdf',NULL,NULL,NULL,NULL,NULL)
    ,('Smitha Milli','OpenAI','Intern',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20171122004535/http://smithamilli.com:80/',NULL,'2017-06-01',NULL,NULL,'2017-09-01')
    ,('Felix Berkenkamp','ETH Zurich','PhD student',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20171104132257/http://wrai.org/',NULL,NULL,NULL,NULL,NULL)
    ,('Will Sawin','Institute for Theoretical Studies at ETH Zurich','Junior Fellow',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20171104132257/http://wrai.org/',NULL,NULL,NULL,NULL,NULL)
    ,('Bas R. Steunebrink','NNAISENSE','Co-Founder',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20171104132257/http://wrai.org/',NULL,NULL,NULL,NULL,NULL)
    ,('Max Daniel','Effective Altruism Foundation','Researcher',NULL,NULL,NULL,NULL,'https://web.archive.org/web/20171104132257/http://wrai.org/',NULL,NULL,NULL,NULL,NULL)
    ,('Holden Karnofsky','Open Philanthropy Project','Executive Director',NULL,NULL,NULL,NULL,'https://www.openphilanthropy.org/blog/potential-risks-advanced-artificial-intelligence-philanthropic-opportunity https://www.openphilanthropy.org/blog/some-background-our-views-regarding-advanced-artificial-intelligence',NULL,NULL,NULL,NULL,NULL)
;
